extract: 

get:
	wget http://www.cse.chalmers.se/~hallgren/CactusExample/Haskell.bnf
	wget http://www.cse.chalmers.se/~hallgren/CactusExample/Haskell/HaskellAbsSyn.hs
	wget http://www.cse.chalmers.se/~hallgren/CactusExample/Haskell/HaskellParser.y
	wget http://www.cse.chalmers.se/~hallgren/CactusExample/Haskell/HaskellLexer.x

include ../../Makefile.grammar
