extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/e5526f14814ecd948bd33b1589221f8b02c4378c/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
