<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="Table">
    <eClassifiers xsi:type="ecore:EClass" name="Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rows" lowerBound="1" upperBound="-1" eType="/1/Row" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Row">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1" eType="/1/Cell" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cell">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
