<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="J2SE5">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractTypeDeclaration" abstract="true" eSuperTypes="/0/NamedElement /0/BodyDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalFileContent" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="package" ordered="false" lowerBound="1" eType="/0/PackageDeclaration" eOpposite="/0/PackageDeclaration/ownedElements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyDeclarations" ordered="false" upperBound="-1" eType="/0/BodyDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superInterfaces" ordered="false" upperBound="-1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="commentsAfterBody" ordered="false" upperBound="-1" eType="/0/Comment" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" ordered="false" upperBound="-1" eType="/0/ImportDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="commentsBeforeBody" ordered="false" upperBound="-1" eType="/0/Comment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" ordered="false" upperBound="-1" eType="/0/AnnotationMemberValuePair" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationMemberValuePair" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="member" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeDeclaration" eSuperTypes="/0/AbstractTypeDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationTypeMemberDeclaration" eSuperTypes="/0/NamedElement /0/BodyDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" ordered="false" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClassDeclaration" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyDeclarations" ordered="false" upperBound="-1" eType="/0/BodyDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayAccess" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="index" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="array" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayCreation" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" ordered="false" eType="/0/ArrayInitializer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayInitializer" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayLengthAccess" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="array" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightHandSide" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftHandSide" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ASTNode" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="comments" ordered="false" upperBound="-1" eType="/0/Comment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BodyDeclaration" abstract="true" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" ordered="false" upperBound="-1" eType="/0/Annotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" ordered="false" upperBound="-1" eType="/0/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockComment" eSuperTypes="/0/Comment"/>
    <eClassifiers xsi:type="ecore:EClass" name="BreakStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CastExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CatchClause" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exception" ordered="false" lowerBound="1" eType="/0/SingleVariableDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInstanceCreation" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousClassDeclaration" ordered="false" eType="/0/AnonymousClassDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comment" abstract="true" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnclosedByParent" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrefixOfParent" ordered="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContinueStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstructorInvocation" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmptyStatement" eSuperTypes="/0/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnhancedForStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false" lowerBound="1" eType="/0/SingleVariableDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumConstantDeclaration" eSuperTypes="/0/BodyDeclaration /0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousClassDeclaration" ordered="false" eType="/0/AnonymousClassDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumDeclaration" eSuperTypes="/0/AbstractTypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumConstants" ordered="false" upperBound="-1" eType="/0/EnumConstantDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="/0/ASTNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccess" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="field" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldDeclaration" eSuperTypes="/0/BodyDeclaration /0/MultipleValuedNamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializers" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="updaters" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InfixExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extendedOperands" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatement" ordered="false" eType="/0/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatement" ordered="false" lowerBound="1" eType="/0/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImportDeclaration" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="importedElement" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Initializer" eSuperTypes="/0/BodyDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceofExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Javadoc" eSuperTypes="/0/Comment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tags" ordered="false" upperBound="-1" eType="/0/TagElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LabeledStatement" eSuperTypes="/0/Statement /0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LineComment" eSuperTypes="/0/Comment"/>
    <eClassifiers xsi:type="ecore:EClass" name="MemberRef" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="member" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodDeclaration" eSuperTypes="/0/NamedElement /0/BodyDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraArrayDimensions" ordered="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructor" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="varargs" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" eType="/0/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false" upperBound="-1" eType="/0/SingleVariableDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" ordered="false" upperBound="-1" eType="/0/TypeParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thrownExceptions" ordered="false" upperBound="-1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodRef" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false" upperBound="-1" eType="/0/MethodRefParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodRefParameter" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVarargs" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Model">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" ordered="false" upperBound="-1" eType="/0/PackageDeclaration" containment="true" eOpposite="/0/PackageDeclaration/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="orphanTypes" ordered="false" upperBound="-1" eType="/0/OrphanType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultipleValuedNamedElement" abstract="true" eSuperTypes="/0/ValuedNamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" ordered="false" upperBound="-1" eType="/0/SingleVariableDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" ordered="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElementRef" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraArrayDimensions" ordered="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" ordered="false" eType="/0/NamedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrphanType" eSuperTypes="/0/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PackageDeclaration" eSuperTypes="/0/ASTNode /0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/ownedElements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" ordered="false" upperBound="-1" eType="/0/AbstractTypeDeclaration" containment="true" eOpposite="/0/AbstractTypeDeclaration/package"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedType" eSuperTypes="/0/ASTNode /0/OrphanType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" ordered="false" upperBound="-1" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParenthesizedExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PostfixExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrefixExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="/0/ASTNode /0/OrphanType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThrowStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleVariableDeclaration" eSuperTypes="/0/ASTNode /0/ValuedNamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVarargs" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="/0/ASTNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="SuperConstructorInvocation" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperFieldAccess" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="field" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuperMethodInvocation" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false" eType="/0/NamedElementRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchCase" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionInitialized" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" ordered="false" upperBound="-1" eType="/0/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SynchronizedStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TagElement" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" ordered="false" upperBound="-1" eType="/0/ASTNode" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextElement" eSuperTypes="/0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThisExpression" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TryStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="finally" ordered="false" eType="/0/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catchClauses" ordered="false" upperBound="-1" eType="/0/CatchClause" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="/0/AbstractTypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInterface" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" ordered="false" upperBound="-1" eType="/0/TypeParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superclass" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeclarationStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" ordered="false" lowerBound="1" eType="/0/AbstractTypeDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeLiteral" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeParameter" eSuperTypes="/0/ASTNode /0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bounds" ordered="false" upperBound="-1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedItem" eSuperTypes="/0/NamedElement /0/ASTNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="ValuedNamedElement" abstract="true" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraArrayDimensions" ordered="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" ordered="false" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationExpression" eSuperTypes="/0/Expression /0/MultipleValuedNamedElement /0/ValuedNamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationStatement" eSuperTypes="/0/Statement /0/MultipleValuedNamedElement /0/ValuedNamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WildCardType" eSuperTypes="/0/OrphanType /0/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUpperBound" ordered="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bound" ordered="false" eType="/0/NamedElementRef" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="/0/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Statement" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveType">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
</xmi:XMI>
