#ifndef CWMCOMPLETE_MODULE_IDL
#define CWMCOMPLETE_MODULE_IDL
#pragma prefix "org.omg.cwm"
#include "Reflective.idl"
#include "DataTypesModule.idl"
#include "ApproximationModule.idl"
#include "BusinessNomenclatureModule.idl"
#include "KeysIndexesModule.idl"
#include "AssociationRulesModule.idl"
#include "BehavioralModule.idl"
#include "BusinessInformationModule.idl"
#include "RelationalModule.idl"
#include "OlapModule.idl"
#include "CoreModule.idl"
#include "WarehouseProcessModule.idl"
#include "MultidimensionalModule.idl"
#include "TransformationModule.idl"
#include "AttributeImportanceModule.idl"
#include "MiningCoreModule.idl"
#include "RelationshipsModule.idl"
#include "ExpressionsModule.idl"
#include "TypeMappingModule.idl"
#include "WarehouseOperationModule.idl"
#include "InstanceModule.idl"
#include "XMLModule.idl"
#include "RecordModule.idl"
#include "ClassificationModule.idl"
#include "SupervisedModule.idl"
#include "ClusteringModule.idl"
#include "InformationVisualizationModule.idl"
#include "SoftwareDeploymentModule.idl"

module CWMCompleteModule
{
   interface CWMCompleteModulePackage;

   interface CWMCompleteModulePackageFactory
   {
      CWMCompleteModulePackage create_cwmcomplete_module_package ()
         raises (Reflective::MofError);
   };

   interface CWMCompleteModulePackage : Reflective::RefPackage
   {
      readonly attribute CoreModule::CoreModulePackage core_ref;
      readonly attribute BehavioralModule::BehavioralModulePackage behavioral_ref;
      readonly attribute RelationshipsModule::RelationshipsModulePackage relationships_ref;
      readonly attribute InstanceModule::InstanceModulePackage instance_ref;
      readonly attribute BusinessInformationModule::BusinessInformationModulePackage business_information_ref;
      readonly attribute DataTypesModule::DataTypesModulePackage data_types_ref;
      readonly attribute ExpressionsModule::ExpressionsModulePackage expressions_ref;
      readonly attribute KeysIndexesModule::KeysIndexesModulePackage keys_indexes_ref;
      readonly attribute SoftwareDeploymentModule::SoftwareDeploymentModulePackage software_deployment_ref;
      readonly attribute TypeMappingModule::TypeMappingModulePackage type_mapping_ref;
      readonly attribute RelationalModule::RelationalModulePackage relational_ref;
      readonly attribute RecordModule::RecordModulePackage record_ref;
      readonly attribute MultidimensionalModule::MultidimensionalModulePackage multidimensional_ref;
      readonly attribute XMLModule::XMLModulePackage xml_ref;
      readonly attribute TransformationModule::TransformationModulePackage transformation_ref;
      readonly attribute OlapModule::OlapModulePackage olap_ref;
      readonly attribute BusinessNomenclatureModule::BusinessNomenclatureModulePackage business_nomenclature_ref;
      readonly attribute MiningCoreModule::MiningCoreModulePackage mining_core_ref;
      readonly attribute ClusteringModule::ClusteringModulePackage clustering_ref;
      readonly attribute AssociationRulesModule::AssociationRulesModulePackage association_rules_ref;
      readonly attribute SupervisedModule::SupervisedModulePackage supervised_ref;
      readonly attribute ClassificationModule::ClassificationModulePackage classification_ref;
      readonly attribute ApproximationModule::ApproximationModulePackage approximation_ref;
      readonly attribute AttributeImportanceModule::AttributeImportanceModulePackage attribute_importance_ref;
      readonly attribute InformationVisualizationModule::InformationVisualizationModulePackage information_visualization_ref;
      readonly attribute WarehouseProcessModule::WarehouseProcessModulePackage warehouse_process_ref;
      readonly attribute WarehouseOperationModule::WarehouseOperationModulePackage warehouse_operation_ref;
   };
};

#endif
