build:
	cd ecma-334-1 && make build
	cd ecma-334-2 && make build
	cd ecma-334-3 && make build
	cd ecma-334-4 && make build
	cd iso-23270-2003 && make build
	cd iso-23270-2006 && make build
	cd msft-ls-1.0 && make build
	cd msft-ls-1.2 && make build
	cd msft-ls-3.0 && make build
	cd msft-ls-4.0 && make build

clean:
	cd ecma-334-1 && make clean
	cd ecma-334-2 && make clean
	cd ecma-334-3 && make clean
	cd ecma-334-4 && make clean
	cd iso-23270-2003 && make clean
	cd iso-23270-2006 && make clean
	cd msft-ls-1.0 && make clean
	cd msft-ls-1.2 && make clean
	cd msft-ls-3.0 && make clean
	cd msft-ls-4.0 && make clean

test:
	cd ecma-334-1 && make test
	cd ecma-334-2 && make test
	cd ecma-334-3 && make test
	cd ecma-334-4 && make test
	cd iso-23270-2003 && make test
	cd iso-23270-2006 && make test
	cd msft-ls-1.0 && make test
	cd msft-ls-1.2 && make test
	cd msft-ls-3.0 && make test
	cd msft-ls-4.0 && make test
