extract:
	../../hunter.py src.the.syntax.txt config.edd eiffel.raw.bgf
	${tooldir}/xbgf post-extract.xbgf eiffel.raw.bgf eiffel.ext.bgf
	${tooldir}/xbgf complete.xbgf eiffel.ext.bgf eiffel.bgf

include ../../Makefile.include
