extract:
	${tooldir}/antlr2bgf fetched/src.api2mol.prepared.g extracted/grammar.bgf

get:
	wget http://modelum.es/trac/api2mol/raw-attachment/wiki/WikiStart/api2mol.g

include ../../../Makefile.grammar
