<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bmm">
  <eClassifiers xsi:type="ecore:EClass" name="Assessment" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="motivatedDirective" ordered="false" upperBound="-1" eType="//Directive" eOpposite="//Directive/motivatingAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedEnd" ordered="false" upperBound="-1" eType="//End" eOpposite="//End/judgingAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="judgedInfluencer" ordered="false" lowerBound="1" upperBound="-1" eType="//Influencer" eOpposite="//Influencer/judgingAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessingOrganizationUnit" ordered="false" lowerBound="1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/madeAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedMeans" ordered="false" upperBound="-1" eType="//Means" eOpposite="//Means/judgingAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifiedPotentialImpact" ordered="false" upperBound="-1" eType="//PotentialImpact" eOpposite="//PotentialImpact/identifyingAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/usingAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usingAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/usedAssessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizingAssessmentCategory" ordered="false" upperBound="-1" eType="//AssessmentCategory" eOpposite="//AssessmentCategory/categorizedAssessment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotivationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directive" eSuperTypes="//Means">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedDesiredResult" ordered="false" upperBound="-1" eType="//DesiredResult" eOpposite="//DesiredResult/supportingDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governedCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/governingDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/baseDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governedAsset" ordered="false" upperBound="-1" eType="//Asset" eOpposite="//Asset/governingDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motivatingPotentialImpact" ordered="false" upperBound="-1" eType="//PotentialImpact" eOpposite="//PotentialImpact/motivatedDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="directiveRegulation" ordered="false" upperBound="-1" eType="//Regulation" eOpposite="//Regulation/regulatingDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motivatingAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/motivatedDirective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Means" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="establishingOrganizationUnit" ordered="false" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/establishedMeans"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="judgingAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/affectedMeans"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnit" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedEnd" ordered="false" upperBound="-1" eType="//End" eOpposite="//End/definingOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedBusinessProces" ordered="false" upperBound="-1" eType="//BusinessProcess" eOpposite="//BusinessProcess/responsibleOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedLiability" ordered="false" upperBound="-1" eType="//Liability" eOpposite="//Liability/responsibleOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedAsset" ordered="false" upperBound="-1" eType="//Asset" eOpposite="//Asset/responsibleOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="determiningStrategy" ordered="false" upperBound="-1" eType="//Strategy" eOpposite="//Strategy/determinedOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recognizedInfluencer" ordered="false" upperBound="-1" eType="//Influencer" eOpposite="//Influencer/recognizingOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalInfluencingOrganization" ordered="false" upperBound="-1" eType="//InfluencingOrganization" eOpposite="//InfluencingOrganization/influencingOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="madeAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/assessingOrganizationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="establishedMeans" ordered="false" upperBound="-1" eType="//Means" eOpposite="//Means/establishingOrganizationUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="judgingAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/affectedEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingOrganizationUnit" ordered="false" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/definedEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcess" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveredOffering" ordered="false" upperBound="-1" eType="//Offering" eOpposite="//Offering/deliveringBusinessProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/realizingBusinessProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedAsset" ordered="false" upperBound="-1" eType="//Asset" eOpposite="//Asset/managingBusinessProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governingBusinessPolicy" ordered="false" upperBound="-1" eType="//BusinessPolicy" eOpposite="//BusinessPolicy/governedBusinessProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guidingBusinessRule" ordered="false" lowerBound="1" eType="//BusinessRule" eOpposite="//BusinessRule/guidedBusinessProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleOrganizationUnit" ordered="false" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/managedBusinessProces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offering" eSuperTypes="//FixedAsset //Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/definedOffering"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedAsset" ordered="false" upperBound="-1" eType="//FixedAsset" eOpposite="//FixedAsset/usingOffering"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredResource" ordered="false" upperBound="-1" eType="//Resource" eOpposite="//Resource/requiringOffering"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveringBusinessProcess" ordered="false" upperBound="-1" eType="//BusinessProcess" eOpposite="//BusinessProcess/deliveredOffering"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployingCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/deployedAsset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governingDirective" ordered="false" upperBound="-1" eType="//Directive" eOpposite="//Directive/governedAsset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleOrganizationUnit" ordered="false" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/managedAsset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managingBusinessProcess" ordered="false" upperBound="-1" eType="//BusinessProcess" eOpposite="//BusinessProcess/managedAsset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseOfAction" eSuperTypes="//Means">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/enablingCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enablingCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/enabledCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moreSpecficCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/broaderCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="broaderCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/moreSpecficCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedDesiredResult" ordered="false" upperBound="-1" eType="//DesiredResult" eOpposite="//DesiredResult/supportingCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedOffering" ordered="false" upperBound="-1" eType="//Offering" eOpposite="//Offering/definingCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dischargedLiability" ordered="false" upperBound="-1" eType="//Liability" eOpposite="//Liability/dischargingCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizingBusinessProcess" ordered="false" lowerBound="1" eType="//BusinessProcess" eOpposite="//BusinessProcess/realizedCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governingDirective" ordered="false" upperBound="-1" eType="//Directive" eOpposite="//Directive/governedCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseDirective" ordered="false" upperBound="-1" eType="//Directive" eOpposite="//Directive/derivedCourseOfAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedAsset" ordered="false" upperBound="-1" eType="//Asset" eOpposite="//Asset/deployingCourseOfAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesiredResult" eSuperTypes="//End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moreSpecificDesiredResult" ordered="false" upperBound="-1" eType="//DesiredResult" eOpposite="//DesiredResult/broaderDesiredResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="broaderDesiredResult" ordered="false" upperBound="-1" eType="//DesiredResult" eOpposite="//DesiredResult/moreSpecificDesiredResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportingDirective" ordered="false" upperBound="-1" eType="//Directive" eOpposite="//Directive/supportedDesiredResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportingCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/supportedDesiredResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Liability" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="claimedResource" ordered="false" upperBound="-1" eType="//Resource" eOpposite="//Resource/claimingLiability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleOrganizationUnit" ordered="false" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/managedLiability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dischargingCourseOfAction" ordered="false" upperBound="-1" eType="//CourseOfAction" eOpposite="//CourseOfAction/dischargedLiability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providingFixedAsset" ordered="false" upperBound="-1" eType="//FixedAsset" eOpposite="//FixedAsset/providedResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiringOffering" ordered="false" upperBound="-1" eType="//Offering" eOpposite="//Offering/requiredResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claimingLiability" ordered="false" upperBound="-1" eType="//Liability" eOpposite="//Liability/claimedResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedAsset" eSuperTypes="//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usingOffering" ordered="false" upperBound="-1" eType="//Offering" eOpposite="//Offering/usedAsset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedResource" ordered="false" upperBound="-1" eType="//Resource" eOpposite="//Resource/providingFixedAsset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPolicy" eSuperTypes="//Directive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moreSpecificBusinessPolicy" ordered="false" upperBound="-1" eType="//BusinessPolicy" eOpposite="//BusinessPolicy/broaderBusinessPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="broaderBusinessPolicy" ordered="false" upperBound="-1" eType="//BusinessPolicy" eOpposite="//BusinessPolicy/moreSpecificBusinessPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedBusinessRule" ordered="false" upperBound="-1" eType="//BusinessRule" eOpposite="//BusinessRule/baseBusinessPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="governedBusinessProcess" ordered="false" upperBound="-1" eType="//BusinessProcess" eOpposite="//BusinessProcess/governingBusinessPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRule" eSuperTypes="//Directive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effectingTactic" ordered="false" upperBound="-1" eType="//Tactic" eOpposite="//Tactic/enforcedBusinessRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guidedBusinessProcess" ordered="false" upperBound="-1" eType="//BusinessProcess" eOpposite="//BusinessProcess/guidingBusinessRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseBusinessPolicy" ordered="false" upperBound="-1" eType="//BusinessPolicy" eOpposite="//BusinessPolicy/derivedBusinessRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tactic" eSuperTypes="//CourseOfAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedStrategy" ordered="false" upperBound="-1" eType="//Strategy" eOpposite="//Strategy/implementingTactic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enforcedBusinessRule" ordered="false" upperBound="-1" eType="//BusinessRule" eOpposite="//BusinessRule/effectingTactic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="//CourseOfAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="determinedOrganizationUnit" ordered="false" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/determiningStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plannedMission" ordered="false" upperBound="-1" eType="//Mission" eOpposite="//Mission/componentStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementingTactic" ordered="false" upperBound="-1" eType="//Tactic" eOpposite="//Tactic/implementedStrategy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mission" eSuperTypes="//Means">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operativeVision" ordered="false" eType="//Vision" eOpposite="//Vision/deliveringMission"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentStrategy" ordered="false" upperBound="-1" eType="//Strategy" eOpposite="//Strategy/plannedMission"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vision" eSuperTypes="//End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="amplifyingGoal" ordered="false" upperBound="-1" eType="//Goal" eOpposite="//Goal/amplifiedVision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveringMission" ordered="false" upperBound="-1" eType="//Mission" eOpposite="//Mission/operativeVision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="//DesiredResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quantifyingObjective" ordered="false" upperBound="-1" eType="//Objective" eOpposite="//Objective/quantifiedGoal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="amplifiedVision" ordered="false" eType="//Vision" eOpposite="//Vision/amplifyingGoal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objective" eSuperTypes="//DesiredResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quantifiedGoal" ordered="false" upperBound="-1" eType="//Goal" eOpposite="//Goal/quantifyingObjective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Influencer" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizingInfluencerCategory" ordered="false" upperBound="-1" eType="//InfluencerCategory" eOpposite="//InfluencerCategory/categorizedInfluencer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceInfluencingOrganization" ordered="false" upperBound="-1" eType="//InfluencingOrganization" eOpposite="//InfluencingOrganization/providedInfluencer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="judgingAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/judgedInfluencer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recognizingOrganizationUnit" ordered="false" lowerBound="1" upperBound="-1" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/recognizedInfluencer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfluencerCategory" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizedInfluencer" ordered="false" upperBound="-1" eType="//Influencer" eOpposite="//Influencer/categorizingInfluencerCategory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfluencingOrganization" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizingOrganizationCategory" ordered="false" upperBound="-1" eType="//OrganizationCategory" eOpposite="//OrganizationCategory/categorizedInfluencingOrganization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="influencingOrganizationUnit" ordered="false" eType="//OrganizationUnit" eOpposite="//OrganizationUnit/internalInfluencingOrganization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInfluencer" ordered="false" upperBound="-1" eType="//Influencer" eOpposite="//Influencer/sourceInfluencingOrganization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationCategory" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizedInfluencingOrganization" ordered="false" upperBound="-1" eType="//InfluencingOrganization" eOpposite="//InfluencingOrganization/categorizingOrganizationCategory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PotentialImpact" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifyingAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/identifiedPotentialImpact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motivatedDirective" ordered="false" upperBound="-1" eType="//Directive" eOpposite="//Directive/motivatingPotentialImpact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Regulation" eSuperTypes="//Influencer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regulatingDirective" ordered="false" eType="//Directive" eOpposite="//Directive/directiveRegulation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentCategory" eSuperTypes="//MotivationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizedAssessment" ordered="false" upperBound="-1" eType="//Assessment" eOpposite="//Assessment/categorizingAssessmentCategory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PotentialReward" eSuperTypes="//PotentialImpact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Risk" eSuperTypes="//PotentialImpact"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String"/>
</ecore:EPackage>
