extract:

fetch:
	curl 'https://fisheye.codehaus.org/browse/~raw,r=1/zoneinfo-tz/trunk/Zoneinfo%20TZ/src/main/antlr3/com/classactionpl/tz/Zoneinfo.g' > fetched/Zoneinfo.g
	curl 'https://fisheye.codehaus.org/browse/~raw,r=1/zoneinfo-tz/trunk/Zoneinfo%20TZ/src/main/antlr3/com/classactionpl/tz/ZoneinfoWalker.g' > fetched/ZoneinfoWalker.g

