[Version ( "2.15.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "A communication point from which data can be sent or received. "
       "ProtocolEndpoints link system or computer interfaces to "
       "LogicalNetworks." )]
class testValuesButNoValueMap {

      [Override ( "NameFormat" ), 
       Description ( 
          "A string with Values but no ValueMap." ), 
       Values { "Other", "Autonomous System", 
          "Network Access Provider", "Network Operations Center", 
          "Point of Presence", "Regional Network Provider", "IP", 
          "IPX", "SNA", "Dial", "WAN", "LAN", "ISDN", "Frame Relay", 
          "ATM", "E.164", "Infiniband", "Fibre Channel", 
          "Policy Repository", "Fibre Channel Worldwide Name" }, 
       ModelCorrespondence { "CIM_AdminDomain.Name" }]
   string NameFormat;

};
