	[Version ( "2.15.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "meaningless comment" )]
class testCantReadIncludeFile {

      [Override ( "Description" ), 
       MappingStrings { "blah blah" }]
   string Description;

};
