extract:
	cat ready.lst | xargs -n1 -I _ make _.extract

%.extract:
	cd $* && make extract

diff:
	make extract
	cat ready.lst | xargs -n1 -I _ make _.diff

%.diff:
	gdts $*.bgf $*/grammar.bgf

get:
	cat ready.lst | xargs -n1 -I _ make _.get

%.get:
	cd $* && make get

clean:
	cat ready.lst | xargs -n1 -I _ make _.clean

%.clean:
	cd $* && make clean

test:
	ls -1 */*.bgf | xargs -n1 ../../../shared/tools/validate bgf

