tooldir   = ../../../../shared/tools
sdflibdir = ../../../../../sdf-library/trunk/library/languages
hunter    = ../../hunter.py

clean:
	rm -f *.bgf *.bnf *.html intermediate.lll tmp.xml *prepared*

test:
	ls -1 *.bgf | xargs -n1 ${tooldir}/validate bgf
