tooldir    = ../../../../shared/tools
gendir     = ../../../../shared/generators
dialectdir = ../../../../shared/edd
sdflibdir  = ../../../../../sdf-library/trunk/library/languages
hunter     = ../../../recovery/hunter/hunter.py
rascaldir  = ../../../../../rascal/trunk/src/org/rascalmpl/library/lang

clean:
	rm -f *.bgf *.bnf *.html intermediate.lll tmp.xml *prepared*

test:
	ls -1 *.bgf | xargs -n1 ${tooldir}/validate bgf
