extract:
	cat ready.lst | xargs -n1 -I _ make _.extract

%.extract:
	cd $* && make extract

diff:
	make extract
	cat ready.lst | xargs -n1 -I _ make _.diff

%.diff:
	gdts $*.bgf $*/grammar.bgf

save:
	cat ready.lst | xargs -n1 -I _ make _.save

%.save:
	make $*.extract
	cp $*/grammar.bgf $*.bgf

clean:
	cat ready.lst | xargs -n1 -I _ make _.clean

%.clean:
	cd $* && make clean

test:
	ls -1 *.bgf */*.bgf | xargs -n1 ../../../shared/tools/validate bgf

