extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/0cd1094d22596dc388e3c7f71575124684743ad9/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
