extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/9bb1f0ebd8d1ca1b9fafe58af16437e9579d42d5/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
