<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="type">
    <eClassifiers xsi:type="ecore:EDataType" name="AnySimpleType"/>
    <eClassifiers xsi:type="ecore:EDataType" name="AnyURI"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Base64Binary"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="BooleanObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Byte"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ByteObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Date"/>
    <eClassifiers xsi:type="ecore:EDataType" name="DateTime"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Decimal"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
    <eClassifiers xsi:type="ecore:EDataType" name="DoubleObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Duration"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ENTITIES"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ENTITIESBase"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ENTITY"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Float"/>
    <eClassifiers xsi:type="ecore:EDataType" name="FloatObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="GDay"/>
    <eClassifiers xsi:type="ecore:EDataType" name="GMonth"/>
    <eClassifiers xsi:type="ecore:EDataType" name="GMonthDay"/>
    <eClassifiers xsi:type="ecore:EDataType" name="GYear"/>
    <eClassifiers xsi:type="ecore:EDataType" name="GYearMonth"/>
    <eClassifiers xsi:type="ecore:EDataType" name="HexBinary"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ID"/>
    <eClassifiers xsi:type="ecore:EDataType" name="IDREF"/>
    <eClassifiers xsi:type="ecore:EDataType" name="IDREFS"/>
    <eClassifiers xsi:type="ecore:EDataType" name="IDREFSBase"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Int"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="IntObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Language"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Long"/>
    <eClassifiers xsi:type="ecore:EDataType" name="LongObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Name"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NCName"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NegativeInteger"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NMTOKEN"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NMTOKENS"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NMTOKENSBase"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NonNegativeInteger"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NonPositiveInteger"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NormalizedString"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NOTATION"/>
    <eClassifiers xsi:type="ecore:EDataType" name="PositiveInteger"/>
    <eClassifiers xsi:type="ecore:EDataType" name="QName"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Short"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ShortObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Time"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Token"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedByte"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedByteObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedInt"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedIntObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedLong"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedShort"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedShortObject"/>
  </ecore:EPackage>
  <ecore:EPackage name="bpmn">
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="/1/Vertex /1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="orderedMessages" upperBound="-1" eType="/1/MessagingEdge" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingMessages" upperBound="-1" eType="/1/MessagingEdge" eOpposite="/1/MessagingEdge/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingMessages" upperBound="-1" eType="/1/MessagingEdge" eOpposite="/1/MessagingEdge/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1" eType="/1/Group" eOpposite="/1/Group/activities"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityType" ordered="false" unique="false" eType="/1/ActivityType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventHandlerFor" ordered="false" eType="/1/SubProcess" eOpposite="/1/SubProcess/eventHandlers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lane" ordered="false" eType="/1/Lane" eOpposite="/1/Lane/activities"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="looping" ordered="false" unique="false" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ActivityType">
      <eLiterals name="SubProcess" value="1"/>
      <eLiterals name="EventEndMultiple" value="2"/>
      <eLiterals name="EventEndMessage" value="3"/>
      <eLiterals name="EventIntermediateMessage" value="4"/>
      <eLiterals name="EventStartMultiple" value="5"/>
      <eLiterals name="EventIntermediateMultiple" value="6"/>
      <eLiterals name="GatewayParallel" value="7"/>
      <eLiterals name="EventStartTimer" value="8"/>
      <eLiterals name="EventStartEmpty" value="9"/>
      <eLiterals name="EventIntermediateCancel" value="10"/>
      <eLiterals name="EventEndError" value="11"/>
      <eLiterals name="EventStartRule" value="12"/>
      <eLiterals name="EventEndTerminate" value="13"/>
      <eLiterals name="EventStartLink" value="14"/>
      <eLiterals name="EventIntermediateLink" value="15"/>
      <eLiterals name="EventEndCancel" value="16"/>
      <eLiterals name="EventEndLink" value="17"/>
      <eLiterals name="EventIntermediateEmpty" value="18"/>
      <eLiterals name="EventIntermediateCompensation" value="19"/>
      <eLiterals name="Task" value="20"/>
      <eLiterals name="GatewayDataBasedExclusive" value="21"/>
      <eLiterals name="GatewayComplex" value="22"/>
      <eLiterals name="EventEndEmpty" value="23"/>
      <eLiterals name="EventIntermediateError" value="24"/>
      <eLiterals name="EventIntermediateTimer" value="25"/>
      <eLiterals name="EventEndCompensation" value="26"/>
      <eLiterals name="EventStartMessage" value="27"/>
      <eLiterals name="GatewayDataBasedInclusive" value="28"/>
      <eLiterals name="GatewayEventBasedExclusive" value="29"/>
      <eLiterals name="EventIntermediateRule" value="30"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ActivityTypeObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="/1/Identifiable /1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1" eType="/1/Association" containment="true" eOpposite="/1/Association/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifactsContainer" ordered="false" eType="/1/ArtifactsContainer" eOpposite="/1/ArtifactsContainer/artifacts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtifactsContainer" eSuperTypes="/1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1" eType="/1/Artifact" containment="true" eOpposite="/1/Artifact/artifactsContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false" unique="false" eType="/1/DirectionType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/1/Artifact" eOpposite="/1/Artifact/associations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" eType="/1/IdentifiableNode" eOpposite="/1/IdentifiableNode/associations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BpmnDiagram" eSuperTypes="/1/Identifiable /1/ArtifactsContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pools" upperBound="-1" eType="/1/Pool" containment="true" eOpposite="/1/Pool/bpmnDiagram"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1" eType="/1/MessagingEdge" containment="true" eOpposite="/1/MessagingEdge/bpmnDiagram"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="/1/Artifact"/>
    <eClassifiers xsi:type="ecore:EEnum" name="DirectionType">
      <eLiterals name="Both" value="1"/>
      <eLiterals name="From" value="2"/>
      <eLiterals name="To" value="3"/>
      <eLiterals name="None" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="DirectionTypeObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="/1/IdentifiableNode /1/ArtifactsContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" upperBound="-1" eType="/1/Vertex" containment="true" eOpposite="/1/Vertex/graph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceEdges" upperBound="-1" eType="/1/SequenceEdge" containment="true" eOpposite="/1/SequenceEdge/graph"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="/1/Artifact">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1" eType="/1/Activity" eOpposite="/1/Activity/groups"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identifiable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" ordered="false" unique="false" eType="/0/ID"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdentifiableNode" eSuperTypes="/1/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1" eType="/1/Association" eOpposite="/1/Association/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="/1/Identifiable /1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1" eType="/1/Activity" eOpposite="/1/Activity/lane"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pool" ordered="false" eType="/1/Pool" eOpposite="/1/Pool/lanes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessagingEdge" eSuperTypes="/1/Identifiable /1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bpmnDiagram" ordered="false" eType="/1/BpmnDiagram" eOpposite="/1/BpmnDiagram/messages"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/1/Activity" eOpposite="/1/Activity/outgoingMessages"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" eType="/1/Activity" eOpposite="/1/Activity/incomingMessages"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ncname" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="/1/Graph /1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lanes" upperBound="-1" eType="/1/Lane" containment="true" eOpposite="/1/Lane/pool"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bpmnDiagram" ordered="false" eType="/1/BpmnDiagram" eOpposite="/1/BpmnDiagram/pools"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceEdge" eSuperTypes="/1/Identifiable /1/NamedBpmnObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" ordered="false" eType="/1/Graph" eOpposite="/1/Graph/sequenceEdges"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/1/Vertex" eOpposite="/1/Vertex/outgoingEdges"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" eType="/1/Vertex" eOpposite="/1/Vertex/incomingEdges"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubProcess" eSuperTypes="/1/Activity /1/Graph">
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventHandlers" upperBound="-1" eType="/1/Activity" containment="true" eOpposite="/1/Activity/eventHandlerFor"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransaction" ordered="false" unique="false" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextAnnotation" eSuperTypes="/1/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="Vertex" eSuperTypes="/1/IdentifiableNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1" eType="/1/SequenceEdge" eOpposite="/1/SequenceEdge/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1" eType="/1/SequenceEdge" eOpposite="/1/SequenceEdge/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" ordered="false" eType="/1/Graph" eOpposite="/1/Graph/vertices"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
