extract:
	${slpsdir}/topics/recovery/hunter/hunter.py fetched/ibm-transformed.lll lll2.edd extracted/grammar.bgf

lll2.edd:
	cp ${slpsdir}/shared/edd/lll2.edd .

fetch:
	cp ${slpsdir}/topics/recovery/grk/grammars/vscobolii/ibm-transformed.lll fetched/

include ../../../Makefile.grammar