<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="CDE">
    <eClassifiers xsi:type="ecore:EClass" name="IUmlType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" ordered="false" upperBound="-1" eType="/0/IUmlMember"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICdeComponentSpec" eSuperTypes="/0/IUmlType"/>
    <eClassifiers xsi:type="ecore:EClass" name="IUmlClass" eSuperTypes="/0/IUmlType"/>
    <eClassifiers xsi:type="ecore:EClass" name="IUmlComponent" eSuperTypes="/0/IUmlClass"/>
    <eClassifiers xsi:type="ecore:EClass" name="ICdeServer" eSuperTypes="/0/IUmlComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" ordered="false" upperBound="-1" eType="/0/ICdeComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICdeComponent" eSuperTypes="/0/IUmlComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="IUmlMember"/>
    <eClassifiers xsi:type="ecore:EClass" name="ICdeMember" eSuperTypes="/0/IUmlMember"/>
    <eClassifiers xsi:type="ecore:EClass" name="ICdeMemberExe">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionPerformance" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceNeeded" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionDetails" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
