extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/f1ecdf001b85cd23abd4ac500716ce23584a87aa/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
