extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/cd57a0ac232de1c6cfea0c12eeadbf35f9b341a1/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
