extract:
	${tooldir}/rng2bgf atom.rng.xml ext.bgf
	${tooldir}/normbgf ext.bgf grammar.bgf

get:
	wget http://gist.github.com/tjdett/4617547/raw/e223befbbf04fe4a625152d59c0853fd9b88ec7e/atom.rng.xml

include ../../Makefile.grammar
