<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="CORBAComponent">
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceDef"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationDef"/>
    <eClassifiers xsi:type="ecore:EClass" name="ValueDef"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentDef" eSuperTypes="/0/InterfaceDef">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBasic" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="facets" ordered="false" upperBound="-1" eType="/0/ProvidesDef" containment="true" eOpposite="/0/ProvidesDef/prd_home"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receptacles" ordered="false" upperBound="-1" eType="/0/UsesDef" containment="true" eOpposite="/0/UsesDef/ud_home"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="supports" ordered="false" upperBound="-1" eType="/0/InterfaceDef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="emits" ordered="false" upperBound="-1" eType="/0/EmitsDef" containment="true" eOpposite="/0/EmitsDef/ed_home"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="publishes" ordered="false" upperBound="-1" eType="/0/PublishesDef" containment="true" eOpposite="/0/PublishesDef/pud_home"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumes" ordered="false" upperBound="-1" eType="/0/ConsumesDef" containment="true" eOpposite="/0/ConsumesDef/cd_home"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidesDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provides" ordered="false" lowerBound="1" eType="/0/InterfaceDef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="prd_home" ordered="false" lowerBound="1" eType="/0/ComponentDef" eOpposite="/0/ComponentDef/facets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UsesDef">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="uses" ordered="false" lowerBound="1" eType="/0/InterfaceDef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ud_home" ordered="false" lowerBound="1" eType="/0/ComponentDef" eOpposite="/0/ComponentDef/receptacles"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/ValueDef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmitsDef" eSuperTypes="/0/EventDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ed_home" ordered="false" lowerBound="1" eType="/0/ComponentDef" eOpposite="/0/ComponentDef/emits"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PublishesDef" eSuperTypes="/0/EventDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pud_home" ordered="false" lowerBound="1" eType="/0/ComponentDef" eOpposite="/0/ComponentDef/publishes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumesDef" eSuperTypes="/0/EventDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cd_home" ordered="false" lowerBound="1" eType="/0/ComponentDef" eOpposite="/0/ComponentDef/consumes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HomeDef" eSuperTypes="/0/InterfaceDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="manages" ordered="false" lowerBound="1" eType="/0/ComponentDef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="factories" ordered="false" upperBound="-1" eType="/0/FactoryDef" containment="true" eOpposite="/0/FactoryDef/fa_home"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="finders" ordered="false" upperBound="-1" eType="/0/FinderDef" containment="true" eOpposite="/0/FinderDef/fi_home"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" eType="/0/PrimaryKeyDef" containment="true" eOpposite="/0/PrimaryKeyDef/pkd_home"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FactoryDef" eSuperTypes="/0/OperationDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fa_home" ordered="false" lowerBound="1" eType="/0/HomeDef" eOpposite="/0/HomeDef/factories"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FinderDef" eSuperTypes="/0/OperationDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fi_home" ordered="false" lowerBound="1" eType="/0/HomeDef" eOpposite="/0/HomeDef/finders"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimaryKeyDef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pkd_home" ordered="false" lowerBound="1" eType="/0/HomeDef" eOpposite="/0/HomeDef/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/ValueDef"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
