extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/884624bfd65d28e92f6c7ea41ee12bf2e2f91b1b/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
