extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/ceea54484d47294da6b8051065ac2e9a9f3891b2/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
