extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/c4678f8bcc9b033fec134662c3c9b6f59def9428/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
