extract:

fetch:
	curl https://sparkle-g.googlecode.com/svn/trunk/sparkle-grammar/src/main/antlr3/com/googlecode/sparkleg/SparqlT.g > fetched/SparqlT.g
	curl https://sparkle-g.googlecode.com/svn/trunk/sparkle-grammar/src/main/antlr3/com/googlecode/sparkleg/SparqlT.g4t > fetched/SparqlT.g4t
