extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/f0d5b4e113293415e811a28e5d230b3428813f57/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
