extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/f52f8be1511cc40f130e9aee8474b72e320fb9f9/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
