import: recover
	${hunter} recovered/Final.lll ${dialectdir}/lll2.edd imported/grammar.bgf

recover:
	cp ${slpsdir}/topics//recovery/csharp/grammars/Final.lll recovered/

extract: fetch
	${hunter} fetched/CSHARP1.0.LLL ${dialectdir}/lll2.edd extracted/grammar.bgf

fetch:
	cp ${slpsdir}/topics//recovery/csharp/CSHARP1.0.LLL fetched/

include ../../../Makefile.grammar
