extract:
	${tooldir}/xsd2bgf fetched/RSS20.xsd extracted/grammar.bgf

fetch:
	wget http://web.archive.org/web/20071018075709/http://www.westinkriebel.com/Public/RSS20.xsd
	mv RSS20.xsd fetched/

include ../../Makefile.grammar
