extract:

fetch:
	rm -f fetched/*.g4
	curl https://raw.githubusercontent.com/antlr/grammars-v4/master/scss/ScssLexer.g4 > fetched/ScssLexer.g4
	curl https://raw.githubusercontent.com/antlr/grammars-v4/master/scss/ScssParser.g4 > fetched/ScssParser.g4
