extract:
	${tooldir}/txl2bgf XML/Txl/XML.Grammar ext.1.bgf
	${tooldir}/txl2bgf XML/Txl/XML_DTD.Grammar ext.2.bgf
	${tooldir}/txl2bgf XML/Txl/XML_Element.Grammar ext.3.bgf
	${tooldir}/mergebgf ext.1.bgf ext.2.bgf ext.3.bgf grammar.bgf

include ../../Makefile.grammar
