<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="WordprocessingMLTableElts">
    <eClassifiers xsi:type="ecore:EClass" name="DateTimeType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VersionType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nn" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueType" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FloatValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateTimeTypeValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/DateTimeType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DocumentPropertiesCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dp_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/wd_docProperties"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastAuthor" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="manager" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="company" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hyperlinkBase" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentationFormat" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appName" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="version" ordered="false" eType="/0/VersionType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalTime" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lastPrinted" ordered="false" eType="/0/DateTimeType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="created" ordered="false" eType="/0/DateTimeType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lastSaved" ordered="false" eType="/0/DateTimeType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="words" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="characters" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="charactersWithSpaces" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lines" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paragraphs" ordered="false" unique="false" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomDocumentPropertiesCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cdp_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/wd_customDocProperties"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="customDocumentProperties" ordered="false" lowerBound="1" upperBound="-1" eType="/0/CustomDocumentProperty" containment="true" eOpposite="/0/CustomDocumentProperty/customDocumentProperty_cdpe"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomDocumentProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="customDocumentProperty_cdpe" ordered="false" lowerBound="1" eType="/0/CustomDocumentPropertiesCollection" eOpposite="/0/CustomDocumentPropertiesCollection/customDocumentProperties"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/ValueType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmartTagType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="smartTagType_ste" ordered="false" lowerBound="1" eType="/0/SmartTagsCollection" eOpposite="/0/SmartTagsCollection/smartTagTypes"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceuri" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmartTagsCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="st_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/wd_smartTags"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="smartTagTypes" ordered="false" upperBound="-1" eType="/0/SmartTagType" containment="true" eOpposite="/0/SmartTagType/smartTagType_ste"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="/0/StringType"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BreakType">
      <eLiterals name="bt_page" value="1"/>
      <eLiterals name="bt_column" value="2"/>
      <eLiterals name="bt_text_wrapping" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NoteValue">
      <eLiterals name="ftn_normal" value="1"/>
      <eLiterals name="ftn_separator" value="2"/>
      <eLiterals name="ftn_continuation_separator" value="3"/>
      <eLiterals name="ftn_continuation_notice" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OnOffType">
      <eLiterals name="oot_on" value="1"/>
      <eLiterals name="oot_off" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FldCharTypeProperty">
      <eLiterals name="fctp_begin" value="1"/>
      <eLiterals name="fctp_separate" value="2"/>
      <eLiterals name="fctp_end" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WordDocument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wd_smartTags" ordered="false" eType="/0/SmartTagsCollection" containment="true" eOpposite="/0/SmartTagsCollection/st_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wd_docProperties" ordered="false" eType="/0/DocumentPropertiesCollection" containment="true" eOpposite="/0/DocumentPropertiesCollection/dp_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wd_customDocProperties" ordered="false" eType="/0/CustomDocumentPropertiesCollection" containment="true" eOpposite="/0/CustomDocumentPropertiesCollection/cdp_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ignoreSubtree" ordered="false" eType="/0/StringProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ignoreElements" ordered="false" eType="/0/StringProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fonts" ordered="false" eType="/0/FontsListElt" containment="true" eOpposite="/0/FontsListElt/fle_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lists" ordered="false" eType="/0/ListsElt" containment="true" eOpposite="/0/ListsElt/le_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="styles" ordered="false" eType="/0/StylesElt" containment="true" eOpposite="/0/StylesElt/se_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="docPr" ordered="false" eType="/0/DocPrElt" containment="true" eOpposite="/0/DocPrElt/dpe_wordDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/BodyElt" containment="true" eOpposite="/0/BodyElt/be_wordDocument"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DocPrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dpe_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/docPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BodyElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="be_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/body"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="blockLevelElts" upperBound="-1" eType="/0/BlockLevelElt" containment="true" eOpposite="/0/BlockLevelElt/ble_bodyElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sectPr" ordered="false" eType="/0/SectPrElt" containment="true" eOpposite="/0/SectPrElt/spe_bodyElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockLevelElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ble_bodyElt" ordered="false" lowerBound="1" eType="/0/BodyElt" eOpposite="/0/BodyElt/blockLevelElts"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ble_note" ordered="false" lowerBound="1" eType="/0/NoteElt" eOpposite="/0/NoteElt/n_blockLevelElts"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ble_tableCellElt" ordered="false" lowerBound="1" eType="/0/TableCellElt" eOpposite="/0/TableCellElt/tce_content"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockLevelChunkElt" abstract="true" eSuperTypes="/0/BlockLevelElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParaElt" eSuperTypes="/0/BlockLevelChunkElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pPr" ordered="false" eType="/0/ParaPrElt" containment="true" eOpposite="/0/ParaPrElt/ppe_pElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pContentElts" upperBound="-1" eType="/0/ParaContentElt" containment="true" eOpposite="/0/ParaContentElt/pce_pElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParaPrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ppe_pElt" ordered="false" lowerBound="1" eType="/0/ParaElt" eOpposite="/0/ParaElt/pPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParaContentElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pce_pElt" ordered="false" lowerBound="1" eType="/0/ParaElt" eOpposite="/0/ParaElt/pContentElts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunElt" eSuperTypes="/0/ParaContentElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rPr" ordered="false" eType="/0/RunPrElt" containment="true" eOpposite="/0/RunPrElt/rpe_rElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rContentElts" upperBound="-1" eType="/0/RunContentElt" containment="true" eOpposite="/0/RunContentElt/rce_rElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunPrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rpe_rElt" ordered="false" lowerBound="1" eType="/0/RunElt" eOpposite="/0/RunElt/rPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunContentElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rce_rElt" ordered="false" lowerBound="1" eType="/0/RunElt" eOpposite="/0/RunElt/rContentElts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BreakElt" eSuperTypes="/0/RunContentElt">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/0/BreakType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="/0/RunContentElt /0/StringType"/>
    <eClassifiers xsi:type="ecore:EClass" name="DelText" eSuperTypes="/0/RunContentElt /0/StringType"/>
    <eClassifiers xsi:type="ecore:EClass" name="InstrText" eSuperTypes="/0/RunContentElt /0/StringType"/>
    <eClassifiers xsi:type="ecore:EClass" name="DelInstrText" eSuperTypes="/0/RunContentElt /0/StringType"/>
    <eClassifiers xsi:type="ecore:EClass" name="NoBreakHyphen" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="SoftHyphen" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotationRef" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="FootnoteRef" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="EndnoteRef" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Separator" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContinuationSeparator" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="PgNum" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cr" eSuperTypes="/0/RunContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Footnote" eSuperTypes="/0/RunContentElt /0/NoteElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Endnote" eSuperTypes="/0/RunContentElt /0/NoteElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="NoteElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="n_blockLevelElts" lowerBound="1" upperBound="-1" eType="/0/BlockLevelElt" containment="true" eOpposite="/0/BlockLevelElt/ble_note"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/0/NoteValue"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppressRef" ordered="false" unique="false" eType="/0/OnOffType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Picture" eSuperTypes="/0/RunContentElt /0/PictureType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="/0/RunContentElt /0/SymElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="SymElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" lowerBound="1" eType="/0/StringType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="char" ordered="false" lowerBound="1" eType="/0/StringType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tab" eSuperTypes="/0/RunContentElt /0/TabElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="FldChar" eSuperTypes="/0/RunContentElt /0/FldCharElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="FldCharElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fldData" ordered="false" eType="/0/StringType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fldCharType" ordered="false" unique="false" lowerBound="1" eType="/0/FldCharTypeProperty"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fldLock" ordered="false" unique="false" lowerBound="1" eType="/0/OnOffType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableElt" eSuperTypes="/0/BlockLevelChunkElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tblPr" ordered="false" lowerBound="1" eType="/0/TablePrElt" containment="true" eOpposite="/0/TablePrElt/tpe_tblElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tblGrid" ordered="false" lowerBound="1" eType="/0/TableGridElt" containment="true" eOpposite="/0/TableGridElt/tge_tblElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tblContent" lowerBound="1" upperBound="-1" eType="/0/TableContentElt" containment="true" eOpposite="/0/TableContentElt/tce_tblElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TablePrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tpe_tblElt" ordered="false" lowerBound="1" eType="/0/TableElt" eOpposite="/0/TableElt/tblPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableGridElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tge_tblElt" ordered="false" lowerBound="1" eType="/0/TableElt" eOpposite="/0/TableElt/tblGrid"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableContentElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tce_tblElt" ordered="false" lowerBound="1" eType="/0/TableElt" eOpposite="/0/TableElt/tblContent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tr" upperBound="-1" eType="/0/RowElt" containment="true" eOpposite="/0/RowElt/re_tblContentElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tce_runLevelElts" ordered="false" eType="/0/RunLevelElt" containment="true" eOpposite="/0/RunLevelElt/rle_tblContentElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RowElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="re_tblContentElt" ordered="false" lowerBound="1" eType="/0/TableContentElt" eOpposite="/0/TableContentElt/tr"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tblPrEx" ordered="false" eType="/0/TablePrExElt" containment="true" eOpposite="/0/TablePrExElt/tpee_rowElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="trPr" ordered="false" eType="/0/TableRowPrElt" containment="true" eOpposite="/0/TableRowPrElt/tpe_rowElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowContent" lowerBound="1" upperBound="-1" eType="/0/RowContentElt" containment="true" eOpposite="/0/RowContentElt/rce_rowElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TablePrExElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tpee_rowElt" ordered="false" lowerBound="1" eType="/0/RowElt" eOpposite="/0/RowElt/tblPrEx"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableRowPrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tpe_rowElt" ordered="false" lowerBound="1" eType="/0/RowElt" eOpposite="/0/RowElt/trPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RowContentElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rce_rowElt" ordered="false" lowerBound="1" eType="/0/RowElt" eOpposite="/0/RowElt/rowContent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tc" upperBound="-1" eType="/0/TableCellElt" containment="true" eOpposite="/0/TableCellElt/tce_rowContentElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rce_runLevelElts" ordered="false" eType="/0/RunLevelElt" containment="true" eOpposite="/0/RunLevelElt/rle_rowContentElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableCellElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tce_rowContentElt" ordered="false" lowerBound="1" eType="/0/RowContentElt" eOpposite="/0/RowContentElt/tc"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tcPr" ordered="false" eType="/0/TableCellPrElt" containment="true" eOpposite="/0/TableCellPrElt/tcpe_tableCellElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tce_content" lowerBound="1" upperBound="-1" eType="/0/BlockLevelElt" containment="true" eOpposite="/0/BlockLevelElt/ble_tableCellElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableCellPrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tcpe_tableCellElt" ordered="false" lowerBound="1" eType="/0/TableCellElt" eOpposite="/0/TableCellElt/tcPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FontsListElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fle_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/fonts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ListsElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="le_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/lists"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StylesElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="se_wordDocument" ordered="false" lowerBound="1" eType="/0/WordDocument" eOpposite="/0/WordDocument/styles"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SectPrElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="spe_bodyElt" ordered="false" lowerBound="1" eType="/0/BodyElt" eOpposite="/0/BodyElt/sectPr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunLevelElt" eSuperTypes="/0/BlockLevelChunkElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rle_tblContentElt" ordered="false" lowerBound="1" eType="/0/TableContentElt" eOpposite="/0/TableContentElt/tce_runLevelElts"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rle_rowContentElt" ordered="false" lowerBound="1" eType="/0/RowContentElt" eOpposite="/0/RowContentElt/rce_runLevelElts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CfChunk" eSuperTypes="/0/BlockLevelElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleFieldElt" eSuperTypes="/0/ParaContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="HLinkElt" eSuperTypes="/0/ParaContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubDocElt" eSuperTypes="/0/ParaContentElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="PictureType"/>
    <eClassifiers xsi:type="ecore:EClass" name="TabElt"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
