<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="SCADE">
    <eClassifiers xsi:type="ecore:EClass" name="ListString">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ListInteger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="/0/Object /0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathname" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" ordered="false" eType="/0/Descriptor" eOpposite="/0/Descriptor/modelD"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" ordered="false" eType="/0/Project"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fileRef" ordered="false" eType="/0/FileRef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="storageUnitM" ordered="false" upperBound="-1" eType="/0/StorageUnit" containment="true" eOpposite="/0/StorageUnit/modelS"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumsBlock" ordered="false" lowerBound="1" eType="/0/ConstBlock" containment="true" eOpposite="/0/ConstBlock/modelC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="importedOperator" ordered="false" upperBound="-1" eType="/0/Operator" eOpposite="/0/Operator/modelO"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false" upperBound="-1" eType="/0/Model" eOpposite="/0/Model/libraries"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" ordered="false" upperBound="-1" eType="/0/Model" eOpposite="/0/Model/client"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allLibry" ordered="false" upperBound="-1" eType="/0/Model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeM" ordered="false" upperBound="-1" eType="/0/Type" containment="true" eOpposite="/0/Type/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false" lowerBound="1" eType="/0/Model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coverageFileM" ordered="false" lowerBound="1" eType="/0/CoverageFile" eOpposite="/0/CoverageFile/modelCov"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criterionFileM" ordered="false" lowerBound="1" eType="/0/CriterionFile" eOpposite="/0/CriterionFile/modelCri"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="root" ordered="false" lowerBound="1" eType="/0/Instance" containment="true" eOpposite="/0/Instance/modelI"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="all" ordered="false" upperBound="-1" eType="/0/Operator" containment="true" eOpposite="/0/Operator/modelOp"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="application" ordered="false" lowerBound="1" eType="/0/MtcApplication" eOpposite="/0/MtcApplication/modelM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" ordered="false" upperBound="-1" eType="/0/Reference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tmpNode" ordered="false" upperBound="-1" eType="/0/Node" containment="true" eOpposite="/0/Node/modelN"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constBlockK" ordered="false" eType="/0/ConstBlock" containment="true" eOpposite="/0/ConstBlock/keyC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" eType="/0/Node" containment="true" eOpposite="/0/Node/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="varBlockK" ordered="false" eType="/0/VarBlock" containment="true" eOpposite="/0/VarBlock/keyVB"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeBlock" ordered="false" eType="/0/TypeBlock" containment="true" eOpposite="/0/TypeBlock/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refinement" ordered="false" eType="/0/NamedType" containment="true" eOpposite="/0/NamedType/keyM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" ordered="false" eType="/0/Implementation" containment="true" eOpposite="/0/Implementation/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" eType="/0/Constant"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allConstant" ordered="false" eType="/0/Constant"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allvariable" ordered="false" eType="/0/GlobalVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/0/GlobalVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allConstVar" ordered="false" eType="/0/ConstVar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constVar" ordered="false" eType="/0/ConstVar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constBlock" ordered="false" eType="/0/ConstBlock" containment="true" eOpposite="/0/ConstBlock/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="varBlock" ordered="false" eType="/0/VarBlock" containment="true" eOpposite="/0/VarBlock/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allNamedType" ordered="false" eType="/0/NamedType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namedType" ordered="false" eType="/0/NamedType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Implementation" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/implementation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namedTypeI" ordered="false" lowerBound="1" upperBound="-1" eType="/0/NamedType" eOpposite="/0/NamedType/implementation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstBlock" eSuperTypes="/0/ModelBlock">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelC" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/enumsBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyC" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/constBlockK"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/constBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" eType="/0/Constant" containment="true" eOpposite="/0/Constant/key"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VarBlock" eSuperTypes="/0/ModelBlock">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/0/GlobalVariable" containment="true" eOpposite="/0/GlobalVariable/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyVB" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/varBlockK"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/varBlock"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GlobalVariable" eSuperTypes="/0/Variable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" eType="/0/VarBlock" eOpposite="/0/VarBlock/variable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeBlock" eSuperTypes="/0/ModelBlock">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/NamedType" containment="true" eOpposite="/0/NamedType/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/typeBlock"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Session">
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" ordered="false" lowerBound="1" eType="/0/Descriptor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false" eType="/0/Model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadsModel" ordered="false" upperBound="-1" eType="/0/Model"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefinedIn" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loader" ordered="false" lowerBound="1" eType="/0/Loader" containment="true" eOpposite="/0/Loader/session"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Descriptor" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelFileName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sernFileName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sernPersistAs" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rnetFileName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rnetPersistAs" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="occBase" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVerify" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checked" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="libraryModels" ordered="false" upperBound="-1" eType="/0/ListString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annTypeFiles" ordered="false" upperBound="-1" eType="/0/ListString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelD" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/descriptor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StorageUnit" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="saoFileName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annFileName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistAs" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="loaded" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="saoModified" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annModified" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fileRef" ordered="false" lowerBound="1" eType="/0/FileRef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelS" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/storageUnitM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" ordered="false" upperBound="-1" eType="/0/StorageElement" eOpposite="/0/StorageElement/storageUnitE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StorageElement" abstract="true" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="storageUnitE" ordered="false" lowerBound="1" eType="/0/StorageUnit" eOpposite="/0/StorageUnit/element"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="runLine" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" eSuperTypes="/0/StorageElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoomCoeff" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromat" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lanscape" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPageFormat" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeBlock" eSuperTypes="/0/Block">
      <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" lowerBound="1" eType="/0/Node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelBlock" abstract="true" eSuperTypes="/0/Block">
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnsSize" upperBound="-1" eType="/0/ListInteger" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false" lowerBound="1" eType="/0/Model"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" eType="/0/Label" containment="true" eOpposite="/0/Label/expression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprContactE" ordered="false" lowerBound="1" eType="/0/ExprContact" eOpposite="/0/ExprContact/initValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprCallE" ordered="false" eType="/0/ExprCall" eOpposite="/0/ExprCall/parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependance" ordered="false" eType="/0/ConstVar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subExprId" ordered="false" upperBound="-1" eType="/0/ExprId"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paramArray" ordered="false" eType="/0/ParamArray" eOpposite="/0/ParamArray/value"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" eType="/0/Constant" eOpposite="/0/Constant/value"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="equationE" ordered="false" eType="/0/Equation" eOpposite="/0/Equation/right"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assertionE" ordered="false" eType="/0/Assertion" eOpposite="/0/Assertion/expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" eOpposite="/0/Expression/label"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExprNull" eSuperTypes="/0/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstValue" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kind" ordered="false" lowerBound="1" eType="/0/Object"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExprContact" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boolAct" ordered="false" lowerBound="1" eType="/0/ExprId" containment="true" eOpposite="/0/ExprId/exprContactEI"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initValue" upperBound="-1" eType="/0/Expression" containment="true" eOpposite="/0/Expression/exprContactE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledOpr" ordered="false" lowerBound="1" eType="/0/ExprCall" containment="true" eOpposite="/0/ExprCall/exprContactEC"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExprCall" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOcc" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefOpr" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1" eType="/0/Expression" containment="true" eOpposite="/0/Expression/exprCallE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprContactEC" ordered="false" lowerBound="1" eType="/0/ExprContact" eOpposite="/0/ExprContact/calledOpr"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operator" ordered="false" eType="/0/Operator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operator" eSuperTypes="/0/StorageElement /0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversion" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/0/LocalVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="/0/LocalVariable" containment="true" eOpposite="/0/LocalVariable/operatorI"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="/0/LocalVariable" containment="true" eOpposite="/0/LocalVariable/operatorO"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hidden" upperBound="-1" eType="/0/LocalVariable" containment="true" eOpposite="/0/LocalVariable/operatorH"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false" upperBound="-1" eType="/0/EqBlock" eOpposite="/0/EqBlock/calledOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelO" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/importedOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelOp" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/all"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criterionO" ordered="false" eType="/0/Criterion" eOpposite="/0/Criterion/operatorC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="intanceO" ordered="false" upperBound="-1" eType="/0/Instance" eOpposite="/0/Instance/operatorI"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operator" ordered="false" lowerBound="1" eType="/0/Operator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExprId" eSuperTypes="/0/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprContactEI" ordered="false" lowerBound="1" eType="/0/ExprContact" eOpposite="/0/ExprContact/boolAct"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" ordered="false" lowerBound="1" eType="/0/ConstVar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="/0/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="probe" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pure" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initValue" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorI" ordered="false" eType="/0/Operator" eOpposite="/0/Operator/input"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorO" ordered="false" eType="/0/Operator" eOpposite="/0/Operator/output"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorH" ordered="false" eType="/0/Operator" eOpposite="/0/Operator/hidden"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeL" ordered="false" eType="/0/Node" eOpposite="/0/Node/local"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeI" ordered="false" eType="/0/Node" eOpposite="/0/Node/internal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="/0/Operator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeKind" ordered="false" lowerBound="1" eType="/0/Object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eqBlock" ordered="false" eType="/0/EqBlock" containment="true" eOpposite="/0/EqBlock/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paramBlock" ordered="false" eType="/0/ParamBlock" containment="true" eOpposite="/0/ParamBlock/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="local" ordered="false" upperBound="-1" eType="/0/LocalVariable" containment="true" eOpposite="/0/LocalVariable/nodeL"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internal" ordered="false" upperBound="-1" eType="/0/LocalVariable" containment="true" eOpposite="/0/LocalVariable/nodeI"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" ordered="false" eType="/0/StateMachine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelN" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/tmpNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParamBlock" eSuperTypes="/0/NodeBlock">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Node" eOpposite="/0/Node/paramBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnsSize" upperBound="-1" eType="/0/ListInteger" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="array" lowerBound="1" upperBound="-1" eType="/0/ParamArray" containment="true" eOpposite="/0/ParamArray/paramBlock"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParamArray" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1" eType="/0/ListString" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paramBlock" ordered="false" lowerBound="1" eType="/0/ParamBlock" eOpposite="/0/ParamBlock/array"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operator" ordered="false" lowerBound="1" eType="/0/Operator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1" eType="/0/Expression" containment="true" eOpposite="/0/Expression/paramArray"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstVar" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="kind" ordered="false" lowerBound="1" eType="/0/Object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/Type" eOpposite="/0/Type/constVar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false" upperBound="-1" eType="/0/EqBlock" eOpposite="/0/EqBlock/referencedId"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="/0/ConstVar">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imported" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="/0/Expression" containment="true" eOpposite="/0/Expression/constant"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" ordered="false" eType="/0/Enumeration" eOpposite="/0/Enumeration/value"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" eType="/0/ConstBlock" eOpposite="/0/ConstBlock/constant"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="/0/ConstVar">
      <eStructuralFeatures xsi:type="ecore:EReference" name="clock" ordered="false" eType="/0/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false" upperBound="-1" eType="/0/Equation" eOpposite="/0/Equation/left"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="usedType" ordered="false" upperBound="-1" eType="/0/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/typeM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namedTypeT" ordered="false" upperBound="-1" eType="/0/NamedType" eOpposite="/0/NamedType/definition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tableT" ordered="false" upperBound="-1" eType="/0/Table" eOpposite="/0/Table/typeT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compositeElementT" ordered="false" upperBound="-1" eType="/0/CompositeElement" eOpposite="/0/CompositeElement/typeC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constVar" ordered="false" upperBound="-1" eType="/0/ConstVar" eOpposite="/0/ConstVar/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeT" ordered="false" eType="/0/Type" eOpposite="/0/Type/tableT"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedType" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="kind" ordered="false" lowerBound="1" eType="/0/Object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refinement" ordered="false" upperBound="-1" eType="/0/NamedType" eOpposite="/0/NamedType/refined"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refined" ordered="false" upperBound="-1" eType="/0/NamedType" eOpposite="/0/NamedType/refinement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" eType="/0/Operator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false" eType="/0/Operator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" ordered="false" eType="/0/Implementation" eOpposite="/0/Implementation/namedTypeI"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" ordered="false" eType="/0/Type" eOpposite="/0/Type/namedTypeT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyM" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/refinement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/TypeBlock" eOpposite="/0/TypeBlock/type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" upperBound="-1" eType="/0/Constant" containment="true" eOpposite="/0/Constant/enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Composite" abstract="true" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" ordered="false" eType="/0/CompositeElement" containment="true" eOpposite="/0/CompositeElement/key"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeElement" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeC" ordered="false" eType="/0/Type" eOpposite="/0/Type/compositeElementT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Composite" eOpposite="/0/Composite/element"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="/0/Composite"/>
    <eClassifiers xsi:type="ecore:EClass" name="Tuple" eSuperTypes="/0/Composite"/>
    <eClassifiers xsi:type="ecore:EClass" name="EqBlock" eSuperTypes="/0/NodeBlock">
      <eStructuralFeatures xsi:type="ecore:EReference" name="equation" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Equation" containment="true" eOpposite="/0/Equation/eqBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assertion" ordered="false" eType="/0/Assertion" containment="true" eOpposite="/0/Assertion/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/Node" eOpposite="/0/Node/eqBlock"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledOperator" ordered="false" upperBound="-1" eType="/0/Operator" eOpposite="/0/Operator/client"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedId" ordered="false" upperBound="-1" eType="/0/ConstVar" eOpposite="/0/ConstVar/client"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Equation" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symetrical" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminator" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eqBlock" ordered="false" lowerBound="1" eType="/0/EqBlock" eOpposite="/0/EqBlock/equation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" upperBound="-1" eType="/0/Variable" eOpposite="/0/Variable/definition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" ordered="false" eType="/0/Expression" containment="true" eOpposite="/0/Expression/equationE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outEdge" ordered="false" upperBound="-1" eType="/0/Edge" containment="true" eOpposite="/0/Edge/dstEquation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" ordered="false" eType="/0/RPoint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="size" ordered="false" eType="/0/RSize" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" eType="/0/EqBlock" eOpposite="/0/EqBlock/assertion"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true" eOpposite="/0/Expression/assertionE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="edge" ordered="false" eType="/0/Edge" eOpposite="/0/Edge/assertion"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" ordered="false" eType="/0/RPoint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Annotable" abstract="true" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="propA" upperBound="-1" eType="/0/Prop" containment="true" eOpposite="/0/Prop/entity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefinedIn" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Prop">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1" eType="/0/ListString" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" ordered="false" lowerBound="1" eType="/0/Annotable" eOpposite="/0/Annotable/propA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="configurationP" ordered="false" eType="/0/Configuration" eOpposite="/0/Configuration/propC"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propC" upperBound="-1" eType="/0/Prop" containment="true" eOpposite="/0/Prop/configurationP"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="projectC" ordered="false" lowerBound="1" eType="/0/Project" containment="true" eOpposite="/0/Project/configuration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="/0/Annotable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathname" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" upperBound="-1" eType="/0/Configuration" containment="true" eOpposite="/0/Configuration/projectC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fileRef" ordered="false" upperBound="-1" eType="/0/FileRef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" upperBound="-1" eType="/0/Element" containment="true" eOpposite="/0/Element/root"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="/0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="root" ordered="false" eType="/0/Project" eOpposite="/0/Project/owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="folder" ordered="false" eType="/0/Folder" eOpposite="/0/Folder/element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criterionE" ordered="false" lowerBound="1" eType="/0/Criterion" eOpposite="/0/Criterion/element"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FileRef" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathname" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistAs" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefinedIn" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extensions" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1" eType="/0/Element" containment="true" eOpposite="/0/Element/folder"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeReference" eSuperTypes="/0/Reference"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperatorReference" eSuperTypes="/0/Reference"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="/0/Reference"/>
    <eClassifiers xsi:type="ecore:EClass" name="Error"/>
    <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftVarIndex" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelOrientation" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftVar" ordered="false" lowerBound="1" eType="/0/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" ordered="false" lowerBound="1" eType="/0/ExprId"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="srcEquation" ordered="false" lowerBound="1" eType="/0/Equation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assertion" ordered="false" eType="/0/Assertion" containment="true" eOpposite="/0/Assertion/edge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" ordered="false" upperBound="-1" eType="/0/RPoint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dstEquation" ordered="false" lowerBound="1" eType="/0/Equation" eOpposite="/0/Equation/outEdge"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RPoint"/>
    <eClassifiers xsi:type="ecore:EClass" name="RSize"/>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefinedIn" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateObj" abstract="true" eSuperTypes="/0/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="GraphicalObject" abstract="true" eSuperTypes="/0/StateObj"/>
    <eClassifiers xsi:type="ecore:EClass" name="StInputOutput" abstract="true" eSuperTypes="/0/GraphicalObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="clock" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StInitInput" eSuperTypes="/0/StInputOutput"/>
    <eClassifiers xsi:type="ecore:EClass" name="StInput" eSuperTypes="/0/StInputOutput"/>
    <eClassifiers xsi:type="ecore:EClass" name="StOutput" eSuperTypes="/0/StInputOutput"/>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="/0/GraphicalObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditions" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transKind" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="state1" ordered="false" lowerBound="1" eType="/0/State" eOpposite="/0/State/transition1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="state2" ordered="false" lowerBound="1" eType="/0/State" eOpposite="/0/State/transition2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="/0/GraphicalObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cx" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cy" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transition1" upperBound="-1" eType="/0/Transition" eOpposite="/0/Transition/state1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transition2" ordered="false" upperBound="-1" eType="/0/Transition" eOpposite="/0/Transition/state2"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stOutput" ordered="false" lowerBound="1" eType="/0/StOutput"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InitialStPtr" eSuperTypes="/0/GraphicalObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cx" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cy" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false" lowerBound="1" eType="/0/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="/0/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialStPtr" ordered="false" lowerBound="1" eType="/0/InitialStPtr"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false" upperBound="-1" eType="/0/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transition" ordered="false" upperBound="-1" eType="/0/Transition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Base" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefineIn" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateBase" eSuperTypes="/0/Base"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnNote">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modified" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annNoteType" ordered="false" lowerBound="1" eType="/0/AnnNoteType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotable" ordered="false" lowerBound="1" eType="/0/Annotable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annAttValue" lowerBound="1" upperBound="-1" eType="/0/AnnAttValue" containment="true" eOpposite="/0/AnnAttValue/annNote"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttValue" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annNote" ordered="false" lowerBound="1" eType="/0/AnnNote" eOpposite="/0/AnnNote/annAttValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annAttDefinition" ordered="false" lowerBound="1" eType="/0/AnnAttDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnNoteType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annAttDefinition" ordered="false" eType="/0/AnnAttDefinition" containment="true" eOpposite="/0/AnnAttDefinition/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annAttGroup" ordered="false" eType="/0/AnnAttGroup" containment="true" eOpposite="/0/AnnAttGroup/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/AnnotSchema" eOpposite="/0/AnnotSchema/annNoteType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttDefinition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annAttGroup" ordered="false" lowerBound="1" eType="/0/AnnAttGroup"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/AnnNoteType" eOpposite="/0/AnnNoteType/annAttDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annProperty" ordered="false" eType="/0/AnnProperty" containment="true" eOpposite="/0/AnnProperty/key"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttIntValue" eSuperTypes="/0/AnnAttValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttBoolValue" eSuperTypes="/0/AnnAttValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttCharValue" eSuperTypes="/0/AnnAttValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Char"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttRealValue" eSuperTypes="/0/AnnAttValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttStringValue" eSuperTypes="/0/AnnAttValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttFileValue" eSuperTypes="/0/AnnAttStringValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttDateValue" eSuperTypes="/0/AnnAttStringValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttOidValue" eSuperTypes="/0/AnnAttStringValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttEnumValue" eSuperTypes="/0/AnnAttStringValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/AnnAttDefinition" eOpposite="/0/AnnAttDefinition/annProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnPropertyInt" eSuperTypes="/0/AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnPropertyBool" eSuperTypes="/0/AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnPropertyChar" eSuperTypes="/0/AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Char"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnPropertyReal" eSuperTypes="/0/AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnPropertyString" eSuperTypes="/0/AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnPropertyEnum" eSuperTypes="/0/AnnProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/Object"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnotSchema">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathname" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annNoteType" ordered="false" lowerBound="1" eType="/0/AnnNoteType" containment="true" eOpposite="/0/AnnNoteType/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annCategory" ordered="false" lowerBound="1" eType="/0/AnnCategory" containment="true" eOpposite="/0/AnnCategory/key"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnCategory">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/AnnotSchema" eOpposite="/0/AnnotSchema/annCategory"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="anootability" ordered="false" upperBound="-1" eType="/0/Annotability" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Annotability">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultNote" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annNoteType" ordered="false" lowerBound="1" eType="/0/AnnNoteType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnnAttGroup">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/AnnNoteType" eOpposite="/0/AnnNoteType/annAttGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="File" abstract="true" eSuperTypes="/0/MtcEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="MtcApplication">
      <eStructuralFeatures xsi:type="ecore:EReference" name="coverageFileCov" ordered="false" upperBound="-1" eType="/0/CoverageFile" containment="true" eOpposite="/0/CoverageFile/application"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criterionFileCri" ordered="false" upperBound="-1" eType="/0/CriterionFile" containment="true" eOpposite="/0/CriterionFile/application"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelM" ordered="false" lowerBound="1" eType="/0/Model" containment="true" eOpposite="/0/Model/application"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoverageFile" eSuperTypes="/0/File">
      <eStructuralFeatures xsi:type="ecore:EReference" name="record" ordered="false" eType="/0/Record" containment="true" eOpposite="/0/Record/key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelCov" ordered="false" lowerBound="1" eType="/0/Model" containment="true" eOpposite="/0/Model/coverageFileM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="application" ordered="false" lowerBound="1" eType="/0/MtcApplication" eOpposite="/0/MtcApplication/coverageFileCov"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recordCov" ordered="false" eType="/0/Record" containment="true" eOpposite="/0/Record/coverageFileR"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CriterionFile" eSuperTypes="/0/File">
      <eStructuralFeatures xsi:type="ecore:EReference" name="application" ordered="false" lowerBound="1" eType="/0/MtcApplication" eOpposite="/0/MtcApplication/criterionFileCri"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelCri" ordered="false" lowerBound="1" eType="/0/Model" containment="true" eOpposite="/0/Model/criterionFileM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criterionC" ordered="false" upperBound="-1" eType="/0/Criterion" containment="true" eOpposite="/0/Criterion/criterionFileC"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MtcEntity" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="file" ordered="false" eType="/0/File"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HistoryEntry" eSuperTypes="/0/MtcEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Criterion" eSuperTypes="/0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criterionFileC" ordered="false" lowerBound="1" eType="/0/CriterionFile" eOpposite="/0/CriterionFile/criterionC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorC" ordered="false" lowerBound="1" eType="/0/Operator" eOpposite="/0/Operator/criterionO"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1" eType="/0/Element" containment="true" eOpposite="/0/Element/criterionE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="/0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="occ" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelI" ordered="false" lowerBound="1" eType="/0/Model" eOpposite="/0/Model/root"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operatorI" ordered="false" lowerBound="1" eType="/0/Operator" eOpposite="/0/Operator/intanceO"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationClassI" ordered="false" lowerBound="1" eType="/0/AssociationClass" eOpposite="/0/AssociationClass/instanceA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="caller" ordered="false" lowerBound="1" eType="/0/Instance" eOpposite="/0/Instance/called"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="called" ordered="false" upperBound="-1" eType="/0/Instance" containment="true" eOpposite="/0/Instance/caller"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" ordered="false" eType="/0/Instance" eOpposite="/0/Instance/related"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="related" ordered="false" upperBound="-1" eType="/0/Instance" eOpposite="/0/Instance/origin"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssociationClass">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultA" ordered="false" lowerBound="1" eType="/0/Result" eOpposite="/0/Result/associationClassRs"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recordA" ordered="false" upperBound="-1" eType="/0/Record" eOpposite="/0/Record/associationClassRc"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instanceA" ordered="false" upperBound="-1" eType="/0/Instance" eOpposite="/0/Instance/associationClassI"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Result" eSuperTypes="/0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementCount" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationClassRs" ordered="false" lowerBound="1" eType="/0/AssociationClass" eOpposite="/0/AssociationClass/resultA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="record" ordered="false" lowerBound="1" eType="/0/Record" eOpposite="/0/Record/result"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="/0/MtcEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creator" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" lowerBound="1" eType="/0/CoverageFile" eOpposite="/0/CoverageFile/record"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationClassRc" ordered="false" lowerBound="1" eType="/0/AssociationClass" eOpposite="/0/AssociationClass/recordA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coverageFileR" ordered="false" lowerBound="1" eType="/0/CoverageFile" eOpposite="/0/CoverageFile/recordCov"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" ordered="false" upperBound="-1" eType="/0/Result" containment="true" eOpposite="/0/Result/record"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Loader">
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" ordered="false" eType="/0/Descriptor" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="session" ordered="false" lowerBound="1" eType="/0/Session" eOpposite="/0/Session/loader"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Char"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
