extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/6002b57ae67d48913271c7885d826916cac297d6/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
