extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/b4f8cd2c03a7f3637e062219cf265d67e8eb1ebe/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
