build:
	cd iso-9899-1999 && make build
	cd iso-9899-tc2 && make build
	cd iso-9899-tc3 && make build

clean:
	cd iso-9899-1999 && make clean
	cd iso-9899-tc2 && make clean
	cd iso-9899-tc3 && make clean

test:
	cd iso-9899-1999 && make test
	cd iso-9899-tc2 && make test
	cd iso-9899-tc3 && make test
