<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="JavaSource">
    <eClassifiers xsi:type="ecore:EClass" name="JavaSource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" ordered="false" lowerBound="1" upperBound="-1" eType="/0/ClassDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="superclass" ordered="false" eType="/0/ClassDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" ordered="false" upperBound="-1" eType="/0/MethodDefinition" containment="true" eOpposite="/0/MethodDefinition/class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodDefinition" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" ordered="false" lowerBound="1" eType="/0/ClassDeclaration" eOpposite="/0/ClassDeclaration/methods"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" ordered="false" upperBound="-1" eType="/0/MethodInvocation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false" lowerBound="1" eType="/0/MethodDefinition"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
