extract:
	${tooldir}/rng2bgf ../source/grammar/pt-hlpng.pntd ext.bgf
	${tooldir}/mergebgf ext.bgf ../booleans/grammar.bgf ../dots/grammar.bgf ../multisets/grammar.bgf ../terms/grammar.bgf ../pnmlcoremodel/grammar.bgf ../hlcorestructure/grammar.bgf grammar.bgf

include ../../Makefile.grammar
