extract:
	${hunter} src.ldta.2002.txt ${dialectdir}/lll.edd raw.bgf
	${gendir}/reroot2top raw.bgf reroot.prepared.xbgf
	${tooldir}/xbgf reroot.prepared.xbgf raw.bgf grammar.bgf

include ../../Makefile.grammar
