build:
	cd iso-14882-1998 && make build
	cd iso-n2723 && make build

clean:
	cd iso-14882-1998 && make clean
	cd iso-n2723 && make clean

test:
	cd iso-14882-1998 && make test
	cd iso-n2723 && make test
