fetch:
	wget http://www.omg.org/spec/SPEM/20070801/SPEM2-Process-Behavior-Content.merged.cmof
	wget http://www.omg.org/spec/SPEM/20070801/Infrastructure.cmof
	wget http://www.omg.org/spec/SPEM/20070801/LM.cmof
	wget http://www.omg.org/spec/SPEM/20070801/SoftwareProcessEngineeringMetamodel.cmof
	wget http://www.omg.org/spec/SPEM/20070801/SPEM2-Method-Content.cmof
	wget http://www.omg.org/spec/SPEM/20070801/SPEM2-Process-Behavior-Content.cmof
	wget http://www.omg.org/spec/SPEM/20070801/SPEM2.cmof
	wget http://www.omg.org/spec/SPEM/20070801/SPEM2.merged.cmof
	wget http://www.omg.org/spec/SPEM/20070801/SPEM2-Method-Content.merged.cmof
	mv *.cmof fetched

