<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="USECASE1">
    <eClassifiers xsi:type="ecore:EClass" name="Task">
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Service" eOpposite="/0/Service/task"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="User">
      <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" ordered="false" lowerBound="1" upperBound="-1" eType="/0/UseCase" eOpposite="/0/UseCase/user"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actor" ordered="false" upperBound="-1" eType="/0/Actor" eOpposite="/0/Actor/user"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Actor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" ordered="false" lowerBound="1" upperBound="-1" eType="/0/UseCase" eOpposite="/0/UseCase/actor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="goal" ordered="false" upperBound="-1" eType="/0/Goal" eOpposite="/0/Goal/actor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false" upperBound="-1" eType="/0/User" eOpposite="/0/User/actor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Goal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Service" eOpposite="/0/Service/goal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actor" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Actor" eOpposite="/0/Actor/goal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UseCase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false" eType="/0/Context" containment="true" eOpposite="/0/Context/useCase"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false" upperBound="-1" eType="/0/Service" eOpposite="/0/Service/useCase"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false" upperBound="-1" eType="/0/User" eOpposite="/0/User/useCase"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actor" ordered="false" upperBound="-1" eType="/0/Actor" eOpposite="/0/Actor/useCase"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" ordered="false" lowerBound="1" upperBound="-1" eType="/0/UseCase" eOpposite="/0/UseCase/service"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="goal" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Goal" eOpposite="/0/Goal/service"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="task" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Task" eOpposite="/0/Task/service"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Scenario"/>
    <eClassifiers xsi:type="ecore:EClass" name="Context">
      <eStructuralFeatures xsi:type="ecore:EReference" name="preCondition" ordered="false" lowerBound="1" upperBound="-1" eType="/0/PreCondition" eOpposite="/0/PreCondition/context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" ordered="false" lowerBound="1" upperBound="-1" eType="/0/PostCondition" eOpposite="/0/PostCondition/context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" ordered="false" lowerBound="1" upperBound="-1" eType="/0/UseCase" eOpposite="/0/UseCase/context"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false" upperBound="-1" eType="/0/Context" eOpposite="/0/Context/preCondition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PostCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false" upperBound="-1" eType="/0/Context" eOpposite="/0/Context/postCondition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Episode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" upperBound="-1" eType="/0/Event" eOpposite="/0/Event/episode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event">
      <eStructuralFeatures xsi:type="ecore:EReference" name="episode" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Episode" eOpposite="/0/Episode/event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="/0/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="Responce" eSuperTypes="/0/Event">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false" upperBound="-1" eType="/0/Parameter" containment="true" eOpposite="/0/Parameter/responce"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stimilus" eSuperTypes="/0/Event">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false" upperBound="-1" eType="/0/Parameter" containment="true" eOpposite="/0/Parameter/stimilus"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stimilus" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Stimilus" eOpposite="/0/Stimilus/parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="responce" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Responce" eOpposite="/0/Responce/parameter"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
</xmi:XMI>
