<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="XAML">
    <eClassifiers xsi:type="ecore:EClass" name="Page">
      <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" ordered="false" upperBound="-1" eType="/0/NameSpace" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graphContainer" ordered="false" lowerBound="1" eType="/0/GraphicalContainer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pageResources" ordered="false" lowerBound="1" eType="/0/PageResource" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NameSpace">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PageResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dictionaries" ordered="false" upperBound="-1" eType="/0/ResourceDictionary" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GraphicalContainer" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="WinFXElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false" lowerBound="1" eType="/0/NameSpace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PerspectiveElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false" lowerBound="1" eType="/0/NameSpace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceDictionary">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Grid" eSuperTypes="/0/GraphicalContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="object3D" ordered="false" upperBound="-1" eType="/0/Object3D" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object3D" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Workshop3D" eSuperTypes="/0/Object3D /0/PerspectiveElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements3D" ordered="false" upperBound="-1" eType="/0/Element3D" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element3D"/>
    <eClassifiers xsi:type="ecore:EClass" name="UI3Delement" eSuperTypes="/0/Element3D">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transform" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="material" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" lowerBound="1" eType="/0/Name" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XyzAxis3D" eSuperTypes="/0/Element3D /0/PerspectiveElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Box3D" eSuperTypes="/0/UI3Delement /0/PerspectiveElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Square3D" eSuperTypes="/0/UI3Delement /0/PerspectiveElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Name" eSuperTypes="/0/WinFXElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
