<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
  </ecore:EPackage>
  <ecore:EPackage name="DataTypes">
    <eClassifiers xsi:type="ecore:EEnum" name="AssociationDirectionKind">
      <eLiterals name="None" value="1"/>
      <eLiterals name="To" value="2"/>
      <eLiterals name="From" value="3"/>
      <eLiterals name="Both" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OrientationKind">
      <eLiterals name="Horizontal" value="1"/>
      <eLiterals name="Vertical" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AccessLevelKind">
      <eLiterals name="Public" value="1"/>
      <eLiterals name="Private" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ProcessTypeKind">
      <eLiterals name="None" value="1"/>
      <eLiterals name="Private" value="2"/>
      <eLiterals name="Abstract" value="3"/>
      <eLiterals name="Collaboration" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="StatusKind">
      <eLiterals name="None" value="1"/>
      <eLiterals name="Ready" value="2"/>
      <eLiterals name="Active" value="3"/>
      <eLiterals name="Cancelled" value="4"/>
      <eLiterals name="Aborting" value="5"/>
      <eLiterals name="Aborted" value="6"/>
      <eLiterals name="Completing" value="7"/>
      <eLiterals name="Completed" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AdHocOrderingKind">
      <eLiterals name="Sequential" value="1"/>
      <eLiterals name="Parallel" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ModeKind">
      <eLiterals name="Automatic" value="1"/>
      <eLiterals name="Manual" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GatewayTypeKind">
      <eLiterals name="Xor" value="1"/>
      <eLiterals name="Or" value="2"/>
      <eLiterals name="Complex" value="3"/>
      <eLiterals name="And" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ExecutionKind">
      <eLiterals name="Asynchr" value="1"/>
      <eLiterals name="Synchr" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TriggerKind">
      <eLiterals name="None" value="1"/>
      <eLiterals name="Message" value="2"/>
      <eLiterals name="Timer" value="3"/>
      <eLiterals name="Rule" value="4"/>
      <eLiterals name="Link" value="5"/>
      <eLiterals name="Error" value="6"/>
      <eLiterals name="Cancel" value="7"/>
      <eLiterals name="Compensation" value="8"/>
      <eLiterals name="Terminate" value="9"/>
      <eLiterals name="Multiple" value="10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ImplementationKind">
      <eLiterals name="WebService" value="1"/>
      <eLiterals name="Other" value="2"/>
      <eLiterals name="Unspecified" value="3"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="XPDL">
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false" eType="/2/Script" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalPackages" ordered="false" upperBound="-1" eType="/2/ExternalPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeclarations" ordered="false" upperBound="-1" eType="/2/TypeDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participants" ordered="false" upperBound="-1" eType="/2/Participant" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="applications" ordered="false" upperBound="-1" eType="/2/Application" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFields" ordered="false" upperBound="-1" eType="/2/DataField" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pools" ordered="false" upperBound="-1" eType="/2/Pool" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageFlows" ordered="false" upperBound="-1" eType="/2/MessageFlow" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associations" ordered="false" upperBound="-1" eType="/2/Association" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" ordered="false" upperBound="-1" eType="/2/Artifact" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="workflowProcesses" ordered="false" upperBound="-1" eType="/2/Process" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageFlow" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetActivity" ordered="false" eType="/2/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceActivity" ordered="false" eType="/2/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetPool" ordered="false" eType="/2/Pool"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePool" ordered="false" eType="/2/Pool"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationDirection" ordered="false" unique="false" eType="/1/AssociationDirectionKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetArtifact" ordered="false" eType="/2/Artifact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceArtifact" ordered="false" eType="/2/Artifact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetPool" ordered="false" eType="/2/Pool"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePool" ordered="false" eType="/2/Pool"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetActivity" ordered="false" eType="/2/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceActivity" ordered="false" eType="/2/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" ordered="false" unique="false" eType="/1/OrientationKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boundaryVisible" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lanes" ordered="false" upperBound="-1" eType="/2/Lane" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participant" ordered="false" eType="/2/Participant"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="process" ordered="false" eType="/2/Process"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentLane" ordered="false" eType="/2/Lane"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentPool" ordered="false" eType="/2/Pool"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="/2/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAnnotation" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataObject" ordered="false" eType="/2/DataObject" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="/2/Artifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredForStart" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="producedAtCompletion" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFields" ordered="false" upperBound="-1" eType="/2/DataField" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="/2/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="/2/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" eSuperTypes="/2/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="/2/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParametrizedApplication" eSuperTypes="/2/Application"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReferencedApplication" eSuperTypes="/2/Application">
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalReference" ordered="false" eType="/2/ExternalReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStartActivity" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false" unique="false" eType="/1/StatusKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startMode" ordered="false" unique="false" lowerBound="1" eType="/1/ModeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishMode" ordered="false" unique="false" lowerBound="1" eType="/1/ModeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startQuantity" ordered="false" unique="false" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isATransaction" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFields" ordered="false" upperBound="-1" eType="/2/DataField" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" eSuperTypes="/2/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaskService" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" ordered="false" unique="false" eType="/1/ImplementationKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskReceive" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instantiate" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" ordered="false" unique="false" eType="/1/ImplementationKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskManual" eSuperTypes="/2/Task"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaskReference" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EReference" name="taskRef" ordered="false" lowerBound="1" eType="/2/Task"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskScript" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false" lowerBound="1" eType="/2/Script" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskSend" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" ordered="false" unique="false" eType="/1/ImplementationKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskUser" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" ordered="false" unique="false" eType="/1/ImplementationKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskApplication" eSuperTypes="/2/Task">
      <eStructuralFeatures xsi:type="ecore:EReference" name="packageRef" ordered="false" eType="/2/Package"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Route" eSuperTypes="/2/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gatewayType" ordered="false" unique="false" eType="/1/GatewayTypeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instantiate" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerVisiable" ordered="false" unique="false" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubFlow" eSuperTypes="/2/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="execution" ordered="false" unique="false" eType="/1/ExecutionKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceDataField" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="packageRef" ordered="false" eType="/2/Package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startActivitySet" ordered="false" eType="/2/ActivitySet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startActivity" ordered="false" eType="/2/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockActivity" eSuperTypes="/2/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activitySet" ordered="false" lowerBound="1" eType="/2/ActivitySet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startActivity" ordered="false" eType="/2/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="/2/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerKind" ordered="false" unique="false" lowerBound="1" eType="/1/TriggerKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" ordered="false" unique="false" eType="/1/ImplementationKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" ordered="false" eType="/2/Trigger" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResultCompensation" eSuperTypes="/2/Trigger">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" eType="/2/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResultError" eSuperTypes="/2/Trigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorCode" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResultMultiple" eSuperTypes="/2/Trigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerResultLink" eSuperTypes="/2/Trigger">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processRef" ordered="false" lowerBound="1" eType="/2/Process"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerResultMessage" eSuperTypes="/2/Trigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerIntermediateMultiple" eSuperTypes="/2/Trigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerMultiple" eSuperTypes="/2/Trigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerRule" eSuperTypes="/2/Trigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleName" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TriggerTimer" eSuperTypes="/2/Trigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeDate" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeCycle" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="/2/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntermediateEvent" eSuperTypes="/2/Event">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" eType="/2/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="/2/Event"/>
    <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="/2/Route"/>
    <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" ordered="false" unique="false" eType="/1/AccessLevelKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processType" ordered="false" unique="false" eType="/1/ProcessTypeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false" unique="false" eType="/1/StatusKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppressJoinFailure" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableInstanceCompensation" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adHoc" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adHocOrdering" ordered="false" unique="false" eType="/1/AdHocOrderingKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adHocCompletionCondition" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participant" ordered="false" upperBound="-1" eType="/2/Participant" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="applications" ordered="false" upperBound="-1" eType="/2/Application" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataField" ordered="false" lowerBound="1" eType="/2/DataField" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activitySets" ordered="false" upperBound="-1" eType="/2/ActivitySet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" ordered="false" upperBound="-1" eType="/2/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" ordered="false" upperBound="-1" eType="/2/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultStartActivitySet" ordered="false" eType="/2/ActivitySet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultStartActivity" ordered="false" eType="/2/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" ordered="false" unique="false" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" lowerBound="1" eType="/2/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false" lowerBound="1" eType="/2/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivitySet" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adHoc" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adHocOrdering" ordered="false" unique="false" eType="/1/AdHocOrderingKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adHocCompletionCondition" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultStartActivity" ordered="false" eType="/2/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" ordered="false" upperBound="-1" eType="/2/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" ordered="false" upperBound="-1" eType="/2/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false" eType="/2/Object" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xref" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="categories" ordered="false" upperBound="-1" eType="/2/Category" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalPackage" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="/2/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataField" eSuperTypes="/2/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isArray" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="correlation" ordered="false" unique="false" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" ordered="false" lowerBound="1" eType="/2/TypeDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Script">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="grammar" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
