<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
  <ecore:EPackage name="Bugzilla">
    <eClassifiers xsi:type="ecore:EEnum" name="ErrorType">
      <eLiterals name="et_null" value="1"/>
      <eLiterals name="et_NotFound" value="2"/>
      <eLiterals name="et_NotPermitted" value="3"/>
      <eLiterals name="et_InvalidBugId" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SeverityType">
      <eLiterals name="st_null" value="1"/>
      <eLiterals name="st_blocker" value="2"/>
      <eLiterals name="st_critical" value="3"/>
      <eLiterals name="st_major" value="4"/>
      <eLiterals name="st_normal" value="5"/>
      <eLiterals name="st_minor" value="6"/>
      <eLiterals name="st_trivial" value="7"/>
      <eLiterals name="st_enhancement" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="StatusType">
      <eLiterals name="st_null" value="1"/>
      <eLiterals name="st_UNCONFIRMED" value="2"/>
      <eLiterals name="st_NEW" value="3"/>
      <eLiterals name="st_ASSIGNED" value="4"/>
      <eLiterals name="st_REOPENED" value="5"/>
      <eLiterals name="st_RESOLVED" value="6"/>
      <eLiterals name="st_VERIFIED" value="7"/>
      <eLiterals name="st_CLOSED" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OperatingSystemType">
      <eLiterals name="ost_null" value="1"/>
      <eLiterals name="ost_all" value="2"/>
      <eLiterals name="ost_Windows 3.1" value="3"/>
      <eLiterals name="ost_Windows 95" value="4"/>
      <eLiterals name="ost_Windows 98" value="5"/>
      <eLiterals name="ost_Windows ME" value="6"/>
      <eLiterals name="ost_Windows 2000" value="7"/>
      <eLiterals name="ost_Windows NT" value="8"/>
      <eLiterals name="ost_Windows XP" value="9"/>
      <eLiterals name="ost_Windows Vista" value="10"/>
      <eLiterals name="ost_Windows Server 2003" value="11"/>
      <eLiterals name="ost_MacSystem 7" value="12"/>
      <eLiterals name="ost_MacSystem 7.5" value="13"/>
      <eLiterals name="ost_MacSystem 7.6.1" value="14"/>
      <eLiterals name="ost_MacSystem 8.0" value="15"/>
      <eLiterals name="ost_MacSystem 8.5" value="16"/>
      <eLiterals name="ost_MacSystem 8.6" value="17"/>
      <eLiterals name="ost_MacSystem 9.x" value="18"/>
      <eLiterals name="ost_Mac OS X 10.0" value="19"/>
      <eLiterals name="ost_Mac OS X 10.1" value="20"/>
      <eLiterals name="ost_Mac OS X 10.2" value="21"/>
      <eLiterals name="ost_Mac OS X 10.3" value="22"/>
      <eLiterals name="ost_Linux" value="23"/>
      <eLiterals name="ost_BDS/OS" value="24"/>
      <eLiterals name="ost_FreeBSD" value="25"/>
      <eLiterals name="ost_NetBSD" value="26"/>
      <eLiterals name="ost_OpenBSD" value="27"/>
      <eLiterals name="ost_AIX" value="28"/>
      <eLiterals name="ost_BeOS" value="29"/>
      <eLiterals name="ost_HP-UX" value="30"/>
      <eLiterals name="ost_IRIX" value="31"/>
      <eLiterals name="ost_Neutrino" value="32"/>
      <eLiterals name="ost_OpenVMS" value="33"/>
      <eLiterals name="ost_OS/2" value="34"/>
      <eLiterals name="ost_OSF/1" value="35"/>
      <eLiterals name="ost_Solaris" value="36"/>
      <eLiterals name="ost_SunOS" value="37"/>
      <eLiterals name="ost_other" value="38"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PriorityType">
      <eLiterals name="pt_null" value="1"/>
      <eLiterals name="pt_P1" value="2"/>
      <eLiterals name="pt_P2" value="3"/>
      <eLiterals name="pt_P3" value="4"/>
      <eLiterals name="pt_P4" value="5"/>
      <eLiterals name="pt_P5" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ReportedPlatformType">
      <eLiterals name="rpt_null" value="1"/>
      <eLiterals name="rpt_all" value="2"/>
      <eLiterals name="rpt_DEC" value="3"/>
      <eLiterals name="rpt_HP" value="4"/>
      <eLiterals name="rpt_Macintosh" value="5"/>
      <eLiterals name="rpt_PC" value="6"/>
      <eLiterals name="rpt_SGI" value="7"/>
      <eLiterals name="rpt_Sun" value="8"/>
      <eLiterals name="rpt_other" value="9"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ResolutionType">
      <eLiterals name="rt_null" value="1"/>
      <eLiterals name="rt_FIXED" value="2"/>
      <eLiterals name="rt_INVALID" value="3"/>
      <eLiterals name="rt_WONTFIX" value="4"/>
      <eLiterals name="rt_LATER" value="5"/>
      <eLiterals name="rt_REMIND" value="6"/>
      <eLiterals name="rt_DUPLICATE" value="7"/>
      <eLiterals name="rt_WORKSFORME" value="8"/>
      <eLiterals name="rt_MOVED" value="9"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BugzillaRoot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlbase" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintainer" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exporter" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bugs" lowerBound="1" upperBound="-1" eType="/1/Bug" containment="true" eOpposite="/1/Bug/bug_bugzillaRoot"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bug">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bug_bugzillaRoot" ordered="false" lowerBound="1" eType="/1/BugzillaRoot" eOpposite="/1/BugzillaRoot/bugs"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" ordered="false" unique="false" eType="/1/ErrorType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exporter" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlbase" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_status" ordered="false" unique="false" lowerBound="1" eType="/1/StatusType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" ordered="false" unique="false" eType="/1/ResolutionType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="product" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" ordered="false" unique="false" lowerBound="1" eType="/1/PriorityType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rep_platform" ordered="false" unique="false" lowerBound="1" eType="/1/ReportedPlatformType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="assigned_to" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delta_ts" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reporter" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_milestone" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_severity" ordered="false" unique="false" lowerBound="1" eType="/1/SeverityType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creation_ts" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qa_contact" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status_whiteboard" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="op_sys" ordered="false" unique="false" lowerBound="1" eType="/1/OperatingSystemType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_file_loc" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="short_desc" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keywords" upperBound="-1" eType="/1/Keywords" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependson" upperBound="-1" eType="/1/Dependson" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1" eType="/1/Blocks" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cc" upperBound="-1" eType="/1/Cc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="long_desc" upperBound="-1" eType="/1/LongDesc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachment" upperBound="-1" eType="/1/Attachment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Keywords" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Dependson" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Blocks" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cc" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="LongDesc">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrivate" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="who" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_when" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thetext" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attachment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isObsolete" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPatch" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrivate" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
