extract:
	../../hunter.py src.8.3.txt config.edd ebnf-iso-3.raw.bgf
	${tooldir}/xbgf post-extraction.xbgf ebnf-iso-3.raw.bgf ebnf-iso-3.ext.bgf
	${tooldir}/xbgf refactor.xbgf ebnf-iso-3.ext.bgf ebnf-iso-3.bgf

include ../../Makefile.include
