<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="JavaProject">
    <eClassifiers xsi:type="ecore:EClass" name="JavaProject" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackageFragment" upperBound="-1" eType="/0/PackageFragment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageFragment" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCompilationUnit" upperBound="-1" eType="/0/CompilationUnit" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclaration" upperBound="-1" eType="/0/ImportDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" upperBound="-1" eType="/0/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" ordered="false" eType="/0/PackageDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImportDeclaration" eSuperTypes="/0/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="/0/JavaElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nestedType" upperBound="-1" eType="/0/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSuperType" upperBound="-1" eType="/0/Type"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="member_kind" ordered="false" unique="false" eType="/0/MEMBER_KIND"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1" eType="/0/Method" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1" eType="/0/Field" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="/0/JavaElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="/0/JavaElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametersName" upperBound="-1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametersType" upperBound="-1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaElement" abstract="true" eSuperTypes="/0/NamedElement"/>
    <eClassifiers xsi:type="ecore:EEnum" name="MEMBER_KIND">
      <eLiterals name="class" value="1"/>
      <eLiterals name="enum" value="2"/>
      <eLiterals name="interface" value="3"/>
      <eLiterals name="Annotation" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageDeclaration" eSuperTypes="/0/NamedElement"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
