<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ADELFE">
  <eClassifiers xsi:type="ecore:EClass" name="Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Environnement" eSuperTypes="//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" ordered="false" lowerBound="1" eType="//Element" containment="true" eOpposite="//Element/environnement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="environnement" ordered="false" lowerBound="1" eType="//Environnement" eOpposite="//Environnement/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/elementA"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perception" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/elementP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CooperativeAgent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementA" ordered="false" lowerBound="1" eType="//Element" eOpposite="//Element/action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementP" ordered="false" lowerBound="1" eType="//Element" eOpposite="//Element/perception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representation" ordered="false" lowerBound="1" upperBound="-1" eType="//Representation" containment="true" eOpposite="//Representation/cooperativeAgentR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skill" ordered="false" lowerBound="1" upperBound="-1" eType="//Skill" containment="true" eOpposite="//Skill/cooperativeAgentS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aptitude" ordered="false" upperBound="-1" eType="//Aptitude" containment="true" eOpposite="//Aptitude/cooperativeAgentA"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristic" ordered="false" upperBound="-1" eType="//Characteristic" containment="true" eOpposite="//Characteristic/cooperativeAgentCha"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communication" ordered="false" upperBound="-1" eType="//Communication" containment="true" eOpposite="//Communication/cooperativeAgentCom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observes" ordered="false" lowerBound="1" upperBound="-1" eType="//CooperationRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Representation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooperativeAgentR" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/representation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" ordered="false" lowerBound="1" eType="//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Skill">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooperativeAgentS" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/skill"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aptitude">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooperativeAgentA" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/aptitude"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Characteristic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooperativeAgentCha" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/characteristic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooperativeAgentCom" ordered="false" lowerBound="1" eType="//CooperativeAgent" eOpposite="//CooperativeAgent/communication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aip" ordered="false" upperBound="-1" eType="//AIP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AIP"/>
  <eClassifiers xsi:type="ecore:EClass" name="CooperationRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="detects" ordered="false" lowerBound="1" upperBound="-1" eType="//NCS" eOpposite="//NCS/cooperationRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cooperationRules" ordered="false" lowerBound="1" eType="//CooperationRules" eOpposite="//CooperationRules/detects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Incomprehension" eSuperTypes="//NCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ambiguity" eSuperTypes="//NCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Incompetence" eSuperTypes="//NCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unproductiveness" eSuperTypes="//NCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Concurrency" eSuperTypes="//NCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conflict" eSuperTypes="//NCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Uselessness" eSuperTypes="//NCS"/>
</ecore:EPackage>
