extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/24e8c3a79150f61175436e891c283153c27b2265/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
