fetch:
	wget https://raw.githubusercontent.com/gosu-lang/gosu-lang/master/gosu-core/src/main/java/gw/internal/gosu/parser/ebnf/Gosu.g
	wget https://raw.githubusercontent.com/gosu-lang/gosu-lang/master/gosu-core/src/main/java/gw/internal/gosu/parser/ebnf/GosuProg.g
	mv *.g fetched/
