extract:
	rm -f ext.*.bgf
	${tooldir}/rng2bgf fetched/svg11-tiny.rng ext.svg.bgf
	${tooldir}/rng2bgf fetched/svg-datatypes.rng ext.datatypes.bgf
	${tooldir}/rng2bgf fetched/svg-default-attrib.rng ext.default-attrib.bgf
	${tooldir}/rng2bgf fetched/svg-core-attrib.rng ext.core-attrib.bgf
	${tooldir}/rng2bgf fetched/svg-basic-paint-attrib.rng ext.basic-paint-attrib.bgf
	${tooldir}/rng2bgf fetched/svg-basic-graphics-attrib.rng ext.basic-graphics-attrib.bgf
	${tooldir}/rng2bgf fetched/svg-xlink-attrib.rng ext.xlink-attrib.bgf
	${tooldir}/rng2bgf fetched/svg-extresources-attrib.rng ext.extresources-attrib.bgf
	${tooldir}/rng2bgf fetched/svg-tiny-model.rng ext.tiny-model.bgf
	${tooldir}/rng2bgf fetched/svg-basic-structure.rng ext.basic-structure.bgf
	${tooldir}/rng2bgf fetched/svg-conditional.rng ext.conditional.bgf
	${tooldir}/rng2bgf fetched/svg-image.rng ext.image.bgf
	${tooldir}/rng2bgf fetched/svg-style.rng ext.style.bgf
	${tooldir}/rng2bgf fetched/svg-shape.rng ext.shape.bgf
	${tooldir}/rng2bgf fetched/svg-basic-text.rng ext.basic-text.bgf
	${tooldir}/rng2bgf fetched/svg-hyperlink.rng ext.hyperlink.bgf
	${tooldir}/rng2bgf fetched/svg-view.rng ext.view.bgf
	${tooldir}/rng2bgf fetched/svg-script.rng ext.script.bgf
	${tooldir}/rng2bgf fetched/svg-animation.rng ext.animation.bgf
	${tooldir}/rng2bgf fetched/svg-basic-font.rng ext.basic-font.bgf
	${tooldir}/rng2bgf fetched/svg-extensibility.rng ext.extensibility.bgf
	${tooldir}/mergebgf ext.*.bgf grammar.bgf

fetch:
	cp ../furubayashi/fetched/svg11-tiny.rng fetched/
	cp ../furubayashi/fetched/svg-datatypes.rng fetched/
	cp ../furubayashi/fetched/svg-default-attrib.rng fetched/
	cp ../furubayashi/fetched/svg-core-attrib.rng fetched/
	cp ../furubayashi/fetched/svg-basic-paint-attrib.rng fetched/
	cp ../furubayashi/fetched/svg-basic-graphics-attrib.rng fetched/
	cp ../furubayashi/fetched/svg-xlink-attrib.rng fetched/
	cp ../furubayashi/fetched/svg-extresources-attrib.rng fetched/
	cp ../furubayashi/fetched/svg-tiny-model.rng fetched/
	cp ../furubayashi/fetched/svg-basic-structure.rng fetched/
	cp ../furubayashi/fetched/svg-conditional.rng fetched/
	cp ../furubayashi/fetched/svg-image.rng fetched/
	cp ../furubayashi/fetched/svg-style.rng fetched/
	cp ../furubayashi/fetched/svg-shape.rng fetched/
	cp ../furubayashi/fetched/svg-basic-text.rng fetched/
	cp ../furubayashi/fetched/svg-hyperlink.rng fetched/
	cp ../furubayashi/fetched/svg-view.rng fetched/
	cp ../furubayashi/fetched/svg-script.rng fetched/
	cp ../furubayashi/fetched/svg-animation.rng fetched/
	cp ../furubayashi/fetched/svg-basic-font.rng fetched/
	cp ../furubayashi/fetched/svg-extensibility.rng fetched/

include ../../../../Makefile.grammar
