extract:
	${tooldir}/lll2bgf ../../../recovery/csharp/CSHARP1.0.LLL csharp.raw.bgf
	${tooldir}/normbgf csharp.raw.bgf csharp.ext.bgf
	${tooldir}/lll2bgf ../../../recovery/csharp/grammars/Final.lll csharp.raw.2.bgf
	${tooldir}/normbgf csharp.raw.2.bgf csharp.bgf

include ../../Makefile.include
