extract:
	# ${tooldir}/rscd2bgf ../../../../shared/rascal/src/language/XBGF.rsc ext.xbgf.bgf
	# ${tooldir}/rscd2bgf ../../../../shared/rascal/src/language/XScope.rsc ext.scope.bgf
	${tooldir}/mergebgf aliases.bgf ext.*.bgf grammar.bgf

include ../../Makefile.grammar
