extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/d407113aca1f3d6584e8888371ec843952aabe77/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
