extract:

fetch:
	rm -f fetched/*.g4
	curl https://raw.githubusercontent.com/antlr/grammars-v4/master/xml/XMLLexer.g4 > fetched/XMLLexer.g4
	curl https://raw.githubusercontent.com/antlr/grammars-v4/master/xml/XMLParser.g4 > fetched/XMLParser.g4
