extract:

fetch:
	curl https://raw.githubusercontent.com/ChristianWulf/CSharpGrammar/master/grammars/CSharp4.g > fetched/CSharp4.g
	curl https://raw.githubusercontent.com/ChristianWulf/CSharpGrammar/master/grammars/CSharp4Lexer.g > fetched/CSharp4Lexer.g
	curl https://raw.githubusercontent.com/ChristianWulf/CSharpGrammar/master/grammars/CSharp4PreProcessor.g > fetched/CSharp4PreProcessor.g
	curl https://raw.githubusercontent.com/ChristianWulf/CSharpGrammar/master/grammars/Unicode.g > fetched/Unicode.g
