extract:
	${tooldir}/rng2bgf ../source/grammar/symmetricnet.pntd ext.bgf
	${tooldir}/mergebgf ext.bgf ../partitions/grammar.bgf ../cyclicenumerations/grammar.bgf ../finiteenumerations/grammar.bgf ../finiteintranges/grammar.bgf ../booleans/grammar.bgf ../multisets/grammar.bgf ../dots/grammar.bgf ../integers/grammar.bgf ../hlcorestructure/grammar.bgf ../terms/grammar.bgf ../pnmlcoremodel/grammar.bgf grammar.bgf	

include ../../Makefile.grammar
