<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="XHTML">
    <eClassifiers xsi:type="ecore:EClass" name="ValuedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CDATA" eSuperTypes="/0/ValuedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PCDATA" eSuperTypes="/0/ValuedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="NMTOKEN" eSuperTypes="/0/ValuedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="IDREF" eSuperTypes="/0/ValuedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="IDREFS">
      <eStructuralFeatures xsi:type="ecore:EReference" name="idrefs" ordered="false" upperBound="-1" eType="/0/IDREF"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ID" eSuperTypes="/0/ValuedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMPTY"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContentType" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContentTypes">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contentTypes" ordered="false" lowerBound="2" upperBound="-1" eType="/0/ContentType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Charset" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="Charsets">
      <eStructuralFeatures xsi:type="ecore:EReference" name="charsets" ordered="false" lowerBound="2" upperBound="-1" eType="/0/Charset" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LanguageCode" eSuperTypes="/0/NMTOKEN"/>
    <eClassifiers xsi:type="ecore:EClass" name="Character" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkTypes" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="MediaDesc" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="URI" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="UriList">
      <eStructuralFeatures xsi:type="ecore:EReference" name="uris" ordered="false" lowerBound="2" upperBound="-1" eType="/0/URI"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Datetime" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="ScriptExpression" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="StyleSheet" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="Length" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="MultiLength" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pixels" eSuperTypes="/0/CDATA"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Shape">
      <eLiterals name="rect" value="1"/>
      <eLiterals name="circle" value="2"/>
      <eLiterals name="poly" value="3"/>
      <eLiterals name="default" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Coords">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lengths" ordered="false" lowerBound="2" upperBound="-1" eType="/0/Length" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoreAttrs" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false" eType="/0/StyleSheet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="title" ordered="false" eType="/0/Text" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Direction">
      <eLiterals name="ltr" value="1"/>
      <eLiterals name="rtl" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="I18n" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lang" ordered="false" eType="/0/LanguageCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xml:lang" ordered="false" eType="/0/LanguageCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" ordered="false" unique="false" eType="/0/Direction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Events" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="onclick" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ondblclick" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onmousedown" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onmouseup" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onmouseover" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onmousemove" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onmouseout" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onkeypress" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onkeydown" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onkeyup" ordered="false" eType="/0/ScriptExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attrs" abstract="true" eSuperTypes="/0/CoreAttrs /0/I18n /0/Events"/>
    <eClassifiers xsi:type="ecore:EClass" name="Focus" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="accesskey" ordered="false" eType="/0/Character" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tabindex" ordered="false" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onfocus" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onblur" ordered="false" eType="/0/ScriptExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Specialpre" abstract="true" eSuperTypes="/0/Special /0/PreContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Special" abstract="true" eSuperTypes="/0/inline /0/ButtonContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fontstyle" abstract="true" eSuperTypes="/0/inline /0/AContent /0/PreContent /0/ButtonContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Phrase" abstract="true" eSuperTypes="/0/inline /0/AContent /0/PreContent /0/ButtonContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Inlineforms" abstract="true" eSuperTypes="/0/inline /0/AContent /0/PreContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Miscinline" abstract="true" eSuperTypes="/0/Misc /0/Inline /0/AContent /0/PreContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Misc" abstract="true" eSuperTypes="/0/Block /0/Flow /0/FormContent /0/ButtonContent /0/ObjectElement /0/MapElementContent /0/FieldsetElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="inline" abstract="true" eSuperTypes="/0/Inline"/>
    <eClassifiers xsi:type="ecore:EClass" name="Inline" abstract="true" eSuperTypes="/0/Flow /0/ObjectElement /0/FieldsetElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pcdataInline" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Heading" abstract="true" eSuperTypes="/0/block /0/ButtonContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Lists" abstract="true" eSuperTypes="/0/block /0/ButtonContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Blocktext" abstract="true" eSuperTypes="/0/block /0/ButtonContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="block" abstract="true" eSuperTypes="/0/Block /0/Flow /0/FormContent /0/ObjectElement /0/MapElementContent /0/FieldsetElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pcdataFlow" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AContent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pcdataAContent" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreContent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pcdataPreContent" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FormContent" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ButtonContent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pcdataButtonContent" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Html">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i18n" ordered="false" lowerBound="1" eType="/0/I18n" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xmlns" ordered="false" lowerBound="1" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="head" ordered="false" lowerBound="1" eType="/0/Head" containment="true" eOpposite="/0/Head/html"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/0/Body" containment="true" eOpposite="/0/Body/html"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HeadMisc" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Head">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i18n" ordered="false" lowerBound="1" eType="/0/I18n" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="profile" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headmisc" ordered="false" upperBound="-1" eType="/0/HeadMisc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headelement" ordered="false" lowerBound="1" eType="/0/HeadElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="html" ordered="false" lowerBound="1" eType="/0/Html" eOpposite="/0/Html/head"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HeadElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TitleHeadElement" eSuperTypes="/0/HeadElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="title" ordered="false" lowerBound="1" eType="/0/Title" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headmisc" ordered="false" upperBound="-1" eType="/0/HeadMisc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseTitleHeadElement" ordered="false" lowerBound="1" upperBound="-1" eType="/0/BaseTitleHeadElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BaseTitleHeadElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1" eType="/0/Base" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headmisc" ordered="false" upperBound="-1" eType="/0/HeadMisc" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BaseHeadElement" eSuperTypes="/0/HeadElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1" eType="/0/Base" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headmisc" ordered="false" upperBound="-1" eType="/0/HeadMisc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="titleBaseHeadElement" ordered="false" lowerBound="1" upperBound="-1" eType="/0/TitleBaseHeadElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TitleBaseHeadElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="title" ordered="false" lowerBound="1" eType="/0/Title" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headmisc" ordered="false" upperBound="-1" eType="/0/HeadMisc" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Title" eSuperTypes="/0/PCDATA">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i18n" ordered="false" lowerBound="1" eType="/0/I18n" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Base" eSuperTypes="/0/EMPTY">
      <eStructuralFeatures xsi:type="ecore:EReference" name="href" ordered="false" lowerBound="1" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Meta" eSuperTypes="/0/EMPTY /0/HeadMisc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i18n" ordered="false" lowerBound="1" eType="/0/I18n" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="httpequiv" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scheme" ordered="false" eType="/0/CDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="/0/EMPTY /0/Attrs /0/HeadMisc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="charset" ordered="false" eType="/0/Charset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="href" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hreflang" ordered="false" eType="/0/LanguageCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rel" ordered="false" eType="/0/LinkTypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rev" ordered="false" eType="/0/LinkTypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="media" ordered="false" eType="/0/MediaDesc" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="/0/PCDATA /0/HeadMisc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i18n" ordered="false" lowerBound="1" eType="/0/I18n" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="media" ordered="false" eType="/0/MediaDesc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="title" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml:space" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Script" eSuperTypes="/0/PCDATA /0/Miscinline /0/HeadMisc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="charset" ordered="false" eType="/0/Charset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defer" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml:space" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Noscript" eSuperTypes="/0/Attrs /0/Misc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="block" ordered="false" lowerBound="1" eType="/0/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="/0/Attrs">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyElements" ordered="false" upperBound="-1" eType="/0/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onload" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onunload" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="html" ordered="false" lowerBound="1" eType="/0/Html" eOpposite="/0/Html/body"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="/0/Attrs /0/block /0/ButtonContent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="divElements" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="P" eSuperTypes="/0/Attrs /0/block /0/ButtonContent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H1" eSuperTypes="/0/Attrs /0/Heading">
      <eStructuralFeatures xsi:type="ecore:EReference" name="h1Elements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H2" eSuperTypes="/0/Attrs /0/Heading">
      <eStructuralFeatures xsi:type="ecore:EReference" name="h2Elements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H3" eSuperTypes="/0/Attrs /0/Heading">
      <eStructuralFeatures xsi:type="ecore:EReference" name="h3Elements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H4" eSuperTypes="/0/Attrs /0/Heading">
      <eStructuralFeatures xsi:type="ecore:EReference" name="h4Elements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H5" eSuperTypes="/0/Attrs /0/Heading">
      <eStructuralFeatures xsi:type="ecore:EReference" name="h5Elements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H6" eSuperTypes="/0/Attrs /0/Heading">
      <eStructuralFeatures xsi:type="ecore:EReference" name="h6Elements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ul" eSuperTypes="/0/Attrs /0/Lists">
      <eStructuralFeatures xsi:type="ecore:EReference" name="li" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Li" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ol" eSuperTypes="/0/Attrs /0/Lists">
      <eStructuralFeatures xsi:type="ecore:EReference" name="li" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Li" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Li" eSuperTypes="/0/Attrs">
      <eStructuralFeatures xsi:type="ecore:EReference" name="liElements" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dl" eSuperTypes="/0/Attrs /0/Lists">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dlElements" ordered="false" lowerBound="1" upperBound="-1" eType="/0/DlElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DlElement" abstract="true" eSuperTypes="/0/Attrs"/>
    <eClassifiers xsi:type="ecore:EClass" name="Dt" eSuperTypes="/0/DlElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dtElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dd" eSuperTypes="/0/DlElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ddElements" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Address" eSuperTypes="/0/Attrs /0/Blocktext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="addressElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hr" eSuperTypes="/0/EMPTY /0/Attrs /0/Blocktext"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pre" eSuperTypes="/0/Attrs /0/Blocktext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="preElements" ordered="false" upperBound="-1" eType="/0/PreContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml:space" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Blockquote" eSuperTypes="/0/Attrs /0/Blocktext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="blockquoteElements" ordered="false" upperBound="-1" eType="/0/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cite" ordered="false" eType="/0/URI" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ins" eSuperTypes="/0/Attrs /0/Miscinline">
      <eStructuralFeatures xsi:type="ecore:EReference" name="flowelement" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cite" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datetime" ordered="false" eType="/0/Datetime" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Del" eSuperTypes="/0/Attrs /0/Miscinline">
      <eStructuralFeatures xsi:type="ecore:EReference" name="flowelement" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cite" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datetime" ordered="false" eType="/0/Datetime" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="/0/Attrs /0/Focus /0/inline /0/PreContent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="acontent" ordered="false" upperBound="-1" eType="/0/AContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="charset" ordered="false" eType="/0/Charset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/NMTOKEN" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="href" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hreflang" ordered="false" eType="/0/LanguageCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rel" ordered="false" eType="/0/LinkTypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rev" ordered="false" eType="/0/LinkTypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" ordered="false" unique="false" lowerBound="1" eType="/0/Shape"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coords" ordered="false" eType="/0/Coords" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Span" eSuperTypes="/0/Attrs /0/Specialpre">
      <eStructuralFeatures xsi:type="ecore:EReference" name="spanElements" ordered="false" upperBound="-1" eType="/0/Inline"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bdo" eSuperTypes="/0/CoreAttrs /0/Events /0/Specialpre">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bdoElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lang" ordered="false" eType="/0/LanguageCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xml:lang" ordered="false" eType="/0/LanguageCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" ordered="false" unique="false" lowerBound="1" eType="/0/Direction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Br" eSuperTypes="/0/EMPTY /0/CoreAttrs /0/Specialpre"/>
    <eClassifiers xsi:type="ecore:EClass" name="Em" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="emElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Strong" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="strongElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dfn" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dfnElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Code" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Samp" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sampElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Kbd" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="kbdElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Var" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="varElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cite" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citeElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Abbr" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="abbrElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Acronym" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="acronymElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Q" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="qElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cite" ordered="false" eType="/0/URI" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sub" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sup" eSuperTypes="/0/Attrs /0/Phrase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="supElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tt" eSuperTypes="/0/Attrs /0/Fontstyle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ttElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="I" eSuperTypes="/0/Attrs /0/Fontstyle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="iElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="/0/Attrs /0/Fontstyle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Big" eSuperTypes="/0/Attrs /0/Fontstyle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bigElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Small" eSuperTypes="/0/Attrs /0/Fontstyle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="smallElements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectpcdata" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="/0/Attrs /0/Special /0/HeadMisc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectelement" ordered="false" upperBound="-1" eType="/0/ObjectElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="declare" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classid" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codebase" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codetype" ordered="false" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="archive" ordered="false" eType="/0/UriList" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="standby" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="height" ordered="false" eType="/0/Length" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="width" ordered="false" eType="/0/Length" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usemap" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/NMTOKEN" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tabindex" ordered="false" eType="/0/Number" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ValueType">
      <eLiterals name="data" value="1"/>
      <eLiterals name="ref" value="2"/>
      <eLiterals name="object" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Param" eSuperTypes="/0/EMPTY /0/ObjectElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valuetype" ordered="false" unique="false" lowerBound="1" eType="/0/ValueType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/ContentType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Img" eSuperTypes="/0/EMPTY /0/Attrs /0/Special">
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false" lowerBound="1" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alt" ordered="false" lowerBound="1" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="longdesc" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="height" ordered="false" eType="/0/Length" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="width" ordered="false" eType="/0/Length" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usemap" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ismap" ordered="false" unique="false" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MapContent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapElements" ordered="false" lowerBound="1" upperBound="-1" eType="/0/MapElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MapElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="MapElementContent" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="/0/I18n /0/Events /0/Specialpre">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapelement" ordered="false" lowerBound="1" eType="/0/MapContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" ordered="false" lowerBound="1" eType="/0/ID" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false" eType="/0/StyleSheet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="title" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/NMTOKEN" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="/0/EMPTY /0/Attrs /0/Focus /0/MapElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" ordered="false" unique="false" lowerBound="1" eType="/0/Shape"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coords" ordered="false" eType="/0/Coords" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="href" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nohref" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alt" ordered="false" lowerBound="1" eType="/0/Text" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FomeMethod">
      <eLiterals name="get" value="1"/>
      <eLiterals name="post" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="/0/Attrs /0/Block /0/ObjectElement /0/MapElementContent /0/FieldsetElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="formelement" ordered="false" upperBound="-1" eType="/0/FormContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false" lowerBound="1" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" ordered="false" unique="false" lowerBound="1" eType="/0/FomeMethod"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enctype" ordered="false" lowerBound="1" eType="/0/ContentType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onsubmit" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onreset" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accept" ordered="false" eType="/0/ContentTypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accept-charset" ordered="false" eType="/0/Charsets" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="/0/Attrs /0/Inlineforms">
      <eStructuralFeatures xsi:type="ecore:EReference" name="labelelements" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="for" ordered="false" lowerBound="1" eType="/0/IDREF" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accesskey" ordered="false" eType="/0/Character" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onfocus" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onblur" ordered="false" eType="/0/ScriptExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="InputType">
      <eLiterals name="text" value="1"/>
      <eLiterals name="password" value="2"/>
      <eLiterals name="checkbox" value="3"/>
      <eLiterals name="radio" value="4"/>
      <eLiterals name="submit" value="5"/>
      <eLiterals name="reset" value="6"/>
      <eLiterals name="file" value="7"/>
      <eLiterals name="hidden" value="8"/>
      <eLiterals name="image" value="9"/>
      <eLiterals name="button" value="10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="/0/EMPTY /0/Attrs /0/Focus /0/Inlineforms">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/InputType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checked" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="size" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxlength" ordered="false" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alt" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usemap" ordered="false" eType="/0/URI" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onselect" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onchange" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accept" ordered="false" eType="/0/ContentTypes" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Select" eSuperTypes="/0/Attrs /0/Inlineforms">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectelement" ordered="false" lowerBound="1" upperBound="-1" eType="/0/SelectElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="size" ordered="false" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tabindex" ordered="false" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onfocus" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onblur" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onchange" ordered="false" eType="/0/ScriptExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Optgroup" eSuperTypes="/0/SelectElement /0/Attrs">
      <eStructuralFeatures xsi:type="ecore:EReference" name="options" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Option" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" lowerBound="1" eType="/0/Text" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Option" eSuperTypes="/0/SelectElement /0/PCDATA /0/Attrs">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="optionvalue" ordered="false" eType="/0/CDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Textarea" eSuperTypes="/0/PCDATA /0/Attrs /0/Focus /0/Inlineforms">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rows" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cols" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onselect" ordered="false" eType="/0/ScriptExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onchange" ordered="false" eType="/0/ScriptExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldsetElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fieldsetpcdata" ordered="false" upperBound="-1" eType="/0/PCDATA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fieldset" eSuperTypes="/0/Attrs /0/block">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fieldsetelements" ordered="false" upperBound="-1" eType="/0/FieldsetElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Legend" eSuperTypes="/0/Attrs /0/FieldsetElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="legendelement" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accesskey" ordered="false" eType="/0/Character" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ButtonType">
      <eLiterals name="button" value="1"/>
      <eLiterals name="submit" value="2"/>
      <eLiterals name="reset" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="/0/Attrs /0/Focus /0/Inlineforms">
      <eStructuralFeatures xsi:type="ecore:EReference" name="buttoncontent" ordered="false" upperBound="-1" eType="/0/ButtonContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/ButtonType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" ordered="false" unique="false" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TFrame">
      <eLiterals name="void" value="1"/>
      <eLiterals name="above" value="2"/>
      <eLiterals name="below" value="3"/>
      <eLiterals name="hsides" value="4"/>
      <eLiterals name="lhs" value="5"/>
      <eLiterals name="rhs" value="6"/>
      <eLiterals name="vsides" value="7"/>
      <eLiterals name="box" value="8"/>
      <eLiterals name="border" value="9"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TRules">
      <eLiterals name="none" value="1"/>
      <eLiterals name="groups" value="2"/>
      <eLiterals name="rows" value="3"/>
      <eLiterals name="cols" value="4"/>
      <eLiterals name="all" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CellHAlign">
      <eLiterals name="left" value="1"/>
      <eLiterals name="center" value="2"/>
      <eLiterals name="right" value="3"/>
      <eLiterals name="justify" value="4"/>
      <eLiterals name="char" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cellhalign" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" eType="/0/CellHAlign"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="char" ordered="false" eType="/0/Character" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="charoff" ordered="false" eType="/0/Length" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CellVAlign">
      <eLiterals name="top" value="1"/>
      <eLiterals name="middle" value="2"/>
      <eLiterals name="bottom" value="3"/>
      <eLiterals name="baseline" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cellvalign" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valign" ordered="false" unique="false" eType="/0/CellVAlign"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="/0/Attrs /0/block /0/ButtonContent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="caption" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Caption" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="colelement" ordered="false" lowerBound="1" eType="/0/ColElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thead" ordered="false" lowerBound="1" eType="/0/Thead" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tfoot" ordered="false" lowerBound="1" eType="/0/Tfoot" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tableelement" ordered="false" lowerBound="1" eType="/0/TableElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="summary" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="width" ordered="false" eType="/0/Length" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="border" ordered="false" eType="/0/Pixels" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="frame" ordered="false" unique="false" eType="/0/TFrame"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rules" ordered="false" unique="false" eType="/0/TRules"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cellspacing" ordered="false" eType="/0/Length" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cellpadding" ordered="false" eType="/0/Length" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ColElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cols" ordered="false" upperBound="-1" eType="/0/Col" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="colgroup" ordered="false" upperBound="-1" eType="/0/Colgroup" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tbody" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Tbody" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tr" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Tr" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Caption" eSuperTypes="/0/Attrs">
      <eStructuralFeatures xsi:type="ecore:EReference" name="captionelement" ordered="false" upperBound="-1" eType="/0/Inline" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Thead" eSuperTypes="/0/Attrs /0/Cellhalign /0/Cellvalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tr" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Tr" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tfoot" eSuperTypes="/0/Attrs /0/Cellhalign /0/Cellvalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tr" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Tr" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tbody" eSuperTypes="/0/Attrs /0/Cellhalign /0/Cellvalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tr" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Tr" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Colgroup" eSuperTypes="/0/Attrs /0/Cellhalign /0/Cellvalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cols" ordered="false" upperBound="-1" eType="/0/Col" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="span" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="width" ordered="false" eType="/0/MultiLength" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Col" eSuperTypes="/0/EMPTY /0/Attrs /0/Cellhalign /0/Cellvalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="span" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="width" ordered="false" eType="/0/MultiLength" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tr" eSuperTypes="/0/Attrs /0/Cellhalign /0/Cellvalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trelements" ordered="false" lowerBound="1" upperBound="-1" eType="/0/TrElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TrElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Scope">
      <eLiterals name="row" value="1"/>
      <eLiterals name="col" value="2"/>
      <eLiterals name="rowgroup" value="3"/>
      <eLiterals name="colgroup" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Th" eSuperTypes="/0/TrElement /0/Attrs /0/Cellvalign /0/Cellhalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="thelement" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="abbr" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="axis" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headers" ordered="false" eType="/0/IDREFS" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" ordered="false" unique="false" eType="/0/Scope"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowspan" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="colspan" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Td" eSuperTypes="/0/TrElement /0/Attrs /0/Cellvalign /0/Cellhalign">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tdelement" ordered="false" upperBound="-1" eType="/0/Flow" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="abbr" ordered="false" eType="/0/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="axis" ordered="false" eType="/0/CDATA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="headers" ordered="false" eType="/0/IDREFS" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" ordered="false" unique="false" eType="/0/Scope"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowspan" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="colspan" ordered="false" lowerBound="1" eType="/0/Number" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
  </ecore:EPackage>
</xmi:XMI>
