<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Trace">
    <eClassifiers xsi:type="ecore:EClass" name="Trace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1" eType="/0/Level" containment="true" eOpposite="/0/Level/trace"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Level">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trace" ordered="false" lowerBound="1" eType="/0/Trace" eOpposite="/0/Trace/levels"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1" eType="/0/Call" containment="true" eOpposite="/0/Call/level"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Call">
      <eStructuralFeatures xsi:type="ecore:EReference" name="level" ordered="false" lowerBound="1" eType="/0/Level" eOpposite="/0/Level/calls"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" lowerBound="1" upperBound="-1" eType="/0/Index" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DBAccessesNumber" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DBRowsNumber" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="CPUTime" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Index">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
