extract:
	${tooldir}/html2bgf src.htm raw.bgf
	${tooldir}/xbgf ../../../convergence/java/xbgf/correct-impl2.xbgf raw.bgf grammar.bgf

get:
	curl -k http://java.sun.com/docs/books/jls/second_edition/html/syntax.doc.html > src.htm

include ../../Makefile.grammar
