extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/c69c0f32cd92356261aa0f8174003a02efec6abb/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
