<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="BIBTEXML">
    <eClassifiers xsi:type="ecore:EClass" name="BibtexFile">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" ordered="false" upperBound="-1" eType="/0/Entry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Author">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entry" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AuthoredEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="authors" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Author" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BookTitledEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="booktitle" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstitutionEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="institution" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EditoredEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="editor" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DatedEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JournalEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="journal" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TitledEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NotedEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PublisheredEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SchoolEntry" abstract="true" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="school" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="/0/AuthoredEntry /0/DatedEntry /0/TitledEntry /0/JournalEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="/0/AuthoredEntry /0/EditoredEntry /0/PublisheredEntry /0/DatedEntry /0/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="series" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edition" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booklet" eSuperTypes="/0/DatedEntry /0/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="authors" ordered="false" upperBound="-1" eType="/0/Author"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="howpublished" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InBook" eSuperTypes="/0/Book">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InCollection" eSuperTypes="/0/Book /0/BookTitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Manual" eSuperTypes="/0/TitledEntry /0/AuthoredEntry /0/DatedEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="organization" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edition" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TechReport" eSuperTypes="/0/AuthoredEntry /0/InstitutionEntry /0/DatedEntry /0/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThesisEntry" abstract="true" eSuperTypes="/0/AuthoredEntry /0/DatedEntry /0/TitledEntry /0/SchoolEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhdThesis" eSuperTypes="/0/ThesisEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="MastersThesis" eSuperTypes="/0/ThesisEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="Proceedings" eSuperTypes="/0/DatedEntry /0/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="editor" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="series" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="organization" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InProceedings" eSuperTypes="/0/AuthoredEntry /0/BookTitledEntry /0/Proceedings">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Conference" eSuperTypes="/0/InProceedings"/>
    <eClassifiers xsi:type="ecore:EClass" name="Unpublished" eSuperTypes="/0/AuthoredEntry /0/TitledEntry /0/NotedEntry /0/DatedEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="Misc" eSuperTypes="/0/Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="authors" ordered="false" upperBound="-1" eType="/0/Author"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="howpublished" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
