extract:

fetch:
	wget http://www.omg.org/spec/CWM/20020503/ApproximationModule.idl
	wget http://www.omg.org/spec/CWM/20020503/AssociationRulesModule.idl
	wget http://www.omg.org/spec/CWM/20020503/AttributeImportanceModule.idl
	wget http://www.omg.org/spec/CWM/20020503/BehavioralModule.idl
	wget http://www.omg.org/spec/CWM/20020503/BusinessInformationModule.idl
	wget http://www.omg.org/spec/CWM/20020503/BusinessNomenclatureModule.idl
	wget http://www.omg.org/spec/CWM/20020503/CWMCompleteModule.idl
	wget http://www.omg.org/spec/CWM/20020503/ClassificationModule.idl
	wget http://www.omg.org/spec/CWM/20020503/ClusteringModule.idl
	wget http://www.omg.org/spec/CWM/20020503/CoreModule.idl
	wget http://www.omg.org/spec/CWM/20020503/DataTypesModule.idl
	wget http://www.omg.org/spec/CWM/20020503/ExpressionsModule.idl
	wget http://www.omg.org/spec/CWM/20020503/InformationVisualizationModule.idl
	wget http://www.omg.org/spec/CWM/20020503/InstanceModule.idl
	wget http://www.omg.org/spec/CWM/20020503/KeysIndexesModule.idl
	wget http://www.omg.org/spec/CWM/20020503/MiningCoreModule.idl
	wget http://www.omg.org/spec/CWM/20020503/MultidimensionalModule.idl
	wget http://www.omg.org/spec/CWM/20020503/OlapModule.idl
	wget http://www.omg.org/spec/CWM/20020503/RecordModule.idl
	wget http://www.omg.org/spec/CWM/20020503/RelationalModule.idl
	wget http://www.omg.org/spec/CWM/20020503/RelationshipsModule.idl
	wget http://www.omg.org/spec/CWM/20020503/SoftwareDeploymentModule.idl
	wget http://www.omg.org/spec/CWM/20020503/SupervisedModule.idl
	wget http://www.omg.org/spec/CWM/20020503/TransformationModule.idl
	wget http://www.omg.org/spec/CWM/20020503/TypeMappingModule.idl
	wget http://www.omg.org/spec/CWM/20020503/WarehouseOperationModule.idl
	wget http://www.omg.org/spec/CWM/20020503/WarehouseProcessModule.idl
	wget http://www.omg.org/spec/CWM/20020503/XMLModule.idl
	mv *.idl fetched/

