<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PetriNet" nsURI="PetriNetV4" nsPrefix="PetriNet">
    <eClassifiers xsi:type="ecore:EClass" name="Place">
      <eStructuralFeatures xsi:type="ecore:EReference" name="net" ordered="false"
          lowerBound="1" eType="#/0/Net" eOpposite="#/0/Net/place"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1"
          eType="#/0/PTArc" eOpposite="#/0/PTArc/src"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#/0/TPArc"
          eOpposite="#/0/TPArc/dst"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="net" ordered="false"
          lowerBound="1" eType="#/0/Net" eOpposite="#/0/Net/transition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" upperBound="-1"
          eType="#/0/PTArc" eOpposite="#/0/PTArc/dst"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out" lowerBound="1" upperBound="-1"
          eType="#/0/TPArc" eOpposite="#/0/TPArc/src"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Net">
      <eStructuralFeatures xsi:type="ecore:EReference" name="place" lowerBound="1"
          upperBound="-1" eType="#/0/Place" containment="true" eOpposite="#/0/Place/net"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
          upperBound="-1" eType="#/0/Transition" containment="true" eOpposite="#/0/Transition/net"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Arc" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
          unique="false" lowerBound="1" eType="#/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PTArc" eSuperTypes="#/0/Arc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dst" ordered="false"
          lowerBound="1" eType="#/0/Transition" eOpposite="#/0/Transition/in"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false"
          lowerBound="1" eType="#/0/Place" eOpposite="#/0/Place/out"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TPArc" eSuperTypes="#/0/Arc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false"
          lowerBound="1" eType="#/0/Transition" eOpposite="#/0/Transition/out"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dst" ordered="false"
          lowerBound="1" eType="#/0/Place" eOpposite="#/0/Place/in"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
  </ecore:EPackage>
</xmi:XMI>
