extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/a0ad95abd039a744d273b26468a9fdd0523247d4/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
