build:
	cd jls1 && make build
	cd jls2 && make build
	cd jls3 && make build

clean:
	cd jls1 && make clean
	cd jls2 && make clean
	cd jls3 && make clean

test:
	cd jls1 && make test
	cd jls2 && make test
	cd jls3 && make test
