<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="TextualPathExp">
    <eClassifiers xsi:type="ecore:EClass" name="TextualPathExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="path" ordered="false" lowerBound="1" eType="/0/Path" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Path">
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1" upperBound="-1" eType="/0/Transition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultiple" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AlternativeTrans" eSuperTypes="/0/Transition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="altPaths" lowerBound="1" upperBound="-1" eType="/0/Path" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTrans" eSuperTypes="/0/Transition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
  </ecore:EPackage>
</xmi:XMI>
