extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/fec9fad036349a603c14968e10dacbddda08947f/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
