<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="SpreadsheetMLBasicDef">
    <eClassifiers xsi:type="ecore:EClass" name="DateTimeType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VersionType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nn" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueType" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="vt_data" ordered="false" lowerBound="1" eType="/0/Data" eOpposite="/0/Data/value"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateTimeTypeValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/DateTimeType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="/0/ValueType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ErrorValue" eSuperTypes="/0/ValueType"/>
    <eClassifiers xsi:type="ecore:EClass" name="DocumentPropertiesCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dp_workbook" ordered="false" lowerBound="1" eType="/0/Workbook" eOpposite="/0/Workbook/wb_docProperties"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastAuthor" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="manager" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="company" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hyperlinkBase" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentationFormat" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appName" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="version" ordered="false" eType="/0/VersionType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalTime" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lastPrinted" ordered="false" eType="/0/DateTimeType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="created" ordered="false" eType="/0/DateTimeType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lastSaved" ordered="false" eType="/0/DateTimeType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="words" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="characters" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="charactersWithSpaces" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lines" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paragraphs" ordered="false" unique="false" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomDocumentPropertiesCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cdp_workbook" ordered="false" lowerBound="1" eType="/0/Workbook" eOpposite="/0/Workbook/wb_customDocProperties"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="customDocumentProperties" ordered="false" lowerBound="1" upperBound="-1" eType="/0/CustomDocumentProperty" containment="true" eOpposite="/0/CustomDocumentProperty/customDocumentProperty_cdpe"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomDocumentProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="customDocumentProperty_cdpe" ordered="false" lowerBound="1" eType="/0/CustomDocumentPropertiesCollection" eOpposite="/0/CustomDocumentPropertiesCollection/customDocumentProperties"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/ValueType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmartTagType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="smartTagType_ste" ordered="false" lowerBound="1" eType="/0/SmartTagsCollection" eOpposite="/0/SmartTagsCollection/smartTagTypes"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceuri" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmartTagsCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="st_workbook" ordered="false" lowerBound="1" eType="/0/Workbook" eOpposite="/0/Workbook/wb_smartTags"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="st_cell" ordered="false" lowerBound="1" eType="/0/Cell" eOpposite="/0/Cell/c_smartTags"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="smartTagTypes" ordered="false" upperBound="-1" eType="/0/SmartTagType" containment="true" eOpposite="/0/SmartTagType/smartTagType_ste"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Workbook">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wb_smartTags" ordered="false" eType="/0/SmartTagsCollection" containment="true" eOpposite="/0/SmartTagsCollection/st_workbook"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wb_docProperties" ordered="false" eType="/0/DocumentPropertiesCollection" containment="true" eOpposite="/0/DocumentPropertiesCollection/dp_workbook"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wb_customDocProperties" ordered="false" eType="/0/CustomDocumentPropertiesCollection" containment="true" eOpposite="/0/CustomDocumentPropertiesCollection/cdp_workbook"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wb_worksheets" upperBound="-1" eType="/0/Worksheet" containment="true" eOpposite="/0/Worksheet/ws_workbook"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Worksheet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ws_workbook" ordered="false" lowerBound="1" eType="/0/Workbook" eOpposite="/0/Workbook/wb_worksheets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ws_table" ordered="false" eType="/0/Table" containment="true" eOpposite="/0/Table/t_worksheet"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StyledElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="/0/StyledElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="t_worksheet" ordered="false" lowerBound="1" eType="/0/Worksheet" eOpposite="/0/Worksheet/ws_table"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="t_cols" upperBound="-1" eType="/0/Column" containment="true" eOpposite="/0/Column/c_table"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="t_rows" upperBound="-1" eType="/0/Row" containment="true" eOpposite="/0/Row/r_table"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultColumnWidth" ordered="false" unique="false" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultRowHeight" ordered="false" unique="false" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expandedColumnCount" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expandedRowCount" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftCell" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="topCell" ordered="false" unique="false" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullColumns" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullRows" ordered="false" unique="false" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableElement" abstract="true" eSuperTypes="/0/StyledElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false" unique="false" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ColOrRowElement" abstract="true" eSuperTypes="/0/TableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" ordered="false" unique="false" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="/0/ColOrRowElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="c_table" ordered="false" lowerBound="1" eType="/0/Table" eOpposite="/0/Table/t_cols"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoFitWidth" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Row" eSuperTypes="/0/ColOrRowElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="r_table" ordered="false" lowerBound="1" eType="/0/Table" eOpposite="/0/Table/t_rows"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="r_cells" upperBound="-1" eType="/0/Cell" containment="true" eOpposite="/0/Cell/c_row"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoFitHeight" ordered="false" unique="false" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="/0/TableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="c_row" ordered="false" lowerBound="1" eType="/0/Row" eOpposite="/0/Row/r_cells"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="c_smartTags" ordered="false" upperBound="-1" eType="/0/SmartTagsCollection" containment="true" eOpposite="/0/SmartTagsCollection/st_cell"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayRange" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hRef" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeAcross" ordered="false" unique="false" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeDown" ordered="false" unique="false" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="c_data" ordered="false" eType="/0/Data" containment="true" eOpposite="/0/Data/d_cell"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="c_comment" ordered="false" eType="/0/Comment" containment="true" eOpposite="/0/Comment/c_cell"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="c_cell" ordered="false" lowerBound="1" eType="/0/Cell" eOpposite="/0/Cell/c_comment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="com_data" ordered="false" lowerBound="1" eType="/0/Data" containment="true" eOpposite="/0/Data/d_comment"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="showAlways" ordered="false" unique="false" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Data">
      <eStructuralFeatures xsi:type="ecore:EReference" name="d_cell" ordered="false" lowerBound="1" eType="/0/Cell" eOpposite="/0/Cell/c_data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="d_comment" ordered="false" lowerBound="1" eType="/0/Comment" eOpposite="/0/Comment/com_data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/ValueType" containment="true" eOpposite="/0/ValueType/vt_data"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
