<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Mantis">
    <eClassifiers xsi:type="ecore:EEnum" name="RelationshipType">
      <eLiterals name="rt_related to" value="1"/>
      <eLiterals name="rt_parent of" value="2"/>
      <eLiterals name="rt_child of" value="3"/>
      <eLiterals name="rt_duplicate of" value="4"/>
      <eLiterals name="rt_has duplicate" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MantisRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1" eType="/0/Issue" containment="true" eOpposite="/0/Issue/i_mantisRoot"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdentifiedElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrivateElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="private" ordered="false" unique="false" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Issue" eSuperTypes="/0/IdentifiedElt /0/PrivateElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i_mantisRoot" ordered="false" lowerBound="1" eType="/0/MantisRoot" eOpposite="/0/MantisRoot/issues"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" ordered="false" lowerBound="1" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="priority" ordered="false" lowerBound="1" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="severity" ordered="false" lowerBound="1" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="status" ordered="false" lowerBound="1" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reporter" ordered="false" lowerBound="1" eType="/0/Person" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="build" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="osVersion" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reproducibility" ordered="false" lowerBound="1" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepsToReproduce" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalInfo" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateSubmitted" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" ordered="false" eType="/0/Person" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="projection" ordered="false" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eta" ordered="false" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolution" ordered="false" eType="/0/ValueWithId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedInVersion" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachments" upperBound="-1" eType="/0/Attachment" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1" eType="/0/Relationship" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1" eType="/0/Note" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastUpdate" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueWithId" eSuperTypes="/0/IdentifiedElt">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="/0/ValueWithId">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="/0/IdentifiedElt">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/RelationshipType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeStampedElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="/0/TimeStampedElt /0/PrivateElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="author" ordered="false" lowerBound="1" eType="/0/Person" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attachment" eSuperTypes="/0/TimeStampedElt">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="downloadUrl" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
