<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Float"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Long"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
  <ecore:EPackage name="Core">
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="/1/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false" eType="/1/Namespace" eOpposite="/1/Namespace/ownedElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/2/VisibilityKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpecification" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GeneralizableElement" abstract="true" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" ordered="false" upperBound="-1" eType="/1/Generalization" eOpposite="/1/Generalization/child"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" ordered="false" upperBound="-1" eType="/1/ModelElement" containment="true" eOpposite="/1/ModelElement/namespace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="/1/GeneralizableElement /1/Namespace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powertypeRange" ordered="false" upperBound="-1" eType="/1/Generalization" eOpposite="/1/Generalization/powertype"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1" eType="/1/Feature" containment="true" eOpposite="/1/Feature/owner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" eType="/1/Classifier" eOpposite="/1/Classifier/feature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerScope" ordered="false" unique="false" lowerBound="1" eType="/2/ScopeKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" abstract="true" eSuperTypes="/1/Feature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" ordered="false" eType="/2/Multiplicity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" ordered="false" unique="false" eType="/2/ChangeableKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" ordered="false" unique="false" eType="/2/ScopeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" ordered="false" unique="false" eType="/2/OrderingKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssociationEnd" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" ordered="false" lowerBound="1" eType="/1/Association" eOpposite="/1/Association/connection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false" upperBound="-1" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participant" ordered="false" lowerBound="1" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" upperBound="-1" eType="/1/Attribute" containment="true" eOpposite="/1/Attribute/associationEnd"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" ordered="false" unique="false" eType="/2/OrderingKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" ordered="false" unique="false" eType="/2/AggregationKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" ordered="false" unique="false" eType="/2/ScopeKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" ordered="false" eType="/2/Multiplicity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" ordered="false" unique="false" eType="/2/ChangeableKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true" eSuperTypes="/1/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="/1/GeneralizableElement /1/Relationship">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="2" upperBound="-1" eType="/1/AssociationEnd" containment="true" eOpposite="/1/AssociationEnd/association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="/1/StructuralFeature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" ordered="false" eType="/1/AssociationEnd" eOpposite="/1/AssociationEnd/qualifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" ordered="false" eType="/2/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehavioralFeature" abstract="true" eSuperTypes="/1/Feature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1" eType="/1/Parameter" containment="true" eOpposite="/1/Parameter/behavioralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="/1/BehavioralFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrency" ordered="false" unique="false" eType="/2/CallConcurrencyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavioralFeature" ordered="false" eType="/1/BehavioralFeature" eOpposite="/1/BehavioralFeature/parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" ordered="false" eType="/2/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" unique="false" lowerBound="1" eType="/2/ParameterDirectionKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="/1/Relationship">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false" lowerBound="1" eType="/1/GeneralizableElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="powertype" ordered="false" eType="/1/Classifier" eOpposite="/1/Classifier/powertypeRange"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="child" ordered="false" lowerBound="1" eType="/1/GeneralizableElement" eOpposite="/1/GeneralizableElement/generalization"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminator" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="Data_Types">
    <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
      <eLiterals name="ak_none" value="1"/>
      <eLiterals name="ak_aggregate" value="2"/>
      <eLiterals name="ak_composite" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ChangeableKind">
      <eLiterals name="ck_changeable" value="1"/>
      <eLiterals name="ck_frozen" value="2"/>
      <eLiterals name="ck_addOnly" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OrderingKind">
      <eLiterals name="ok_unordered" value="1"/>
      <eLiterals name="ok_ordered" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CallConcurrencyKind">
      <eLiterals name="cck_sequential" value="1"/>
      <eLiterals name="cck_guarded" value="2"/>
      <eLiterals name="cck_concurrent" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirectionKind">
      <eLiterals name="pdk_in" value="1"/>
      <eLiterals name="pdk_inout" value="2"/>
      <eLiterals name="pdk_out" value="3"/>
      <eLiterals name="pdk_return" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ScopeKind">
      <eLiterals name="sk_instance" value="1"/>
      <eLiterals name="sk_classifier" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
      <eLiterals name="vk_public" value="1"/>
      <eLiterals name="vk_protected" value="2"/>
      <eLiterals name="vk_private" value="3"/>
      <eLiterals name="vk_package" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="range" ordered="false" lowerBound="1" upperBound="-1" eType="/2/MultiplicityRange" containment="true" eOpposite="/2/MultiplicityRange/multiplicity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicityRange">
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" ordered="false" lowerBound="1" eType="/2/Multiplicity" eOpposite="/2/Multiplicity/range"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false" unique="false" lowerBound="1" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false" unique="false" lowerBound="1" eType="/0/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="/2/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectSetExpression" eSuperTypes="/2/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActionExpression" eSuperTypes="/2/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="IterationExpression" eSuperTypes="/2/Expression"/>
  </ecore:EPackage>
  <ecore:EPackage name="Common_Behavior">
    <eClassifiers xsi:type="ecore:EClass" name="Instance" abstract="true" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstance" ordered="false" upperBound="-1" eType="/3/Instance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkEnd" ordered="false" upperBound="-1" eType="/3/LinkEnd" eOpposite="/3/LinkEnd/instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false" lowerBound="1" upperBound="-1" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" ordered="false" eType="/3/ComponentInstance" eOpposite="/3/ComponentInstance/resident"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="slot" ordered="false" upperBound="-1" eType="/3/AttributeLink" containment="true" eOpposite="/3/AttributeLink/instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLink" ordered="false" upperBound="-1" eType="/3/Link" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="/1/Classifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actualArgument" upperBound="-1" eType="/3/Argument" containment="true" eOpposite="/3/Argument/action"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionSequence" ordered="false" eType="/3/ActionSequence" eOpposite="/3/ActionSequence/action"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="recurrence" ordered="false" eType="/2/IterationExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" eType="/2/ObjectSetExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAsynchronous" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false" eType="/2/ActionExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateAction" eSuperTypes="/3/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" ordered="false" lowerBound="1" eType="/1/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DestroyAction" eSuperTypes="/3/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="UninterpretedAction" eSuperTypes="/3/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeLink" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" ordered="false" eType="/3/Instance" eOpposite="/3/Instance/slot"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/3/Instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkEnd" ordered="false" eType="/3/LinkEnd" eOpposite="/3/LinkEnd/qualifiedValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false" lowerBound="1" eType="/1/Attribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="/3/Instance"/>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" ordered="false" lowerBound="1" eType="/1/Association"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connection" ordered="false" lowerBound="2" upperBound="-1" eType="/3/LinkEnd" containment="true" eOpposite="/3/LinkEnd/link"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkObject" eSuperTypes="/3/Object /3/Link"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataValue" eSuperTypes="/3/Instance"/>
    <eClassifiers xsi:type="ecore:EClass" name="CallAction" eSuperTypes="/3/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false" lowerBound="1" eType="/1/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SendAction" eSuperTypes="/3/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false" lowerBound="1" eType="/3/Signal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionSequence" eSuperTypes="/3/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1" eType="/3/Action" containment="true" eOpposite="/3/Action/actionSequence"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false" eType="/3/Action" eOpposite="/3/Action/actualArgument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/2/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reception" eSuperTypes="/1/BehavioralFeature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false" lowerBound="1" eType="/3/Signal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkEnd" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" ordered="false" lowerBound="1" eType="/3/Link" eOpposite="/3/Link/connection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedValue" upperBound="-1" eType="/3/AttributeLink" containment="true" eOpposite="/3/AttributeLink/linkEnd"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" ordered="false" lowerBound="1" eType="/3/Instance" eOpposite="/3/Instance/linkEnd"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" ordered="false" lowerBound="1" eType="/1/AssociationEnd"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnAction" eSuperTypes="/3/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="TerminateAction" eSuperTypes="/3/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="Stimulus" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1" eType="/3/Instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLink" ordered="false" eType="/3/Link"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" ordered="false" lowerBound="1" eType="/3/Instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dispatchAction" ordered="false" lowerBound="1" eType="/3/Action"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sender" ordered="false" lowerBound="1" eType="/3/Instance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Exception" eSuperTypes="/3/Signal"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="/3/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resident" ordered="false" upperBound="-1" eType="/3/Instance" eOpposite="/3/Instance/componentInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeInstance" ordered="false" eType="/3/NodeInstance" eOpposite="/3/NodeInstance/resident"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeInstance" eSuperTypes="/3/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resident" ordered="false" upperBound="-1" eType="/3/ComponentInstance" eOpposite="/3/ComponentInstance/nodeInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubsystemInstance" eSuperTypes="/3/Instance"/>
  </ecore:EPackage>
  <ecore:EPackage name="Collaborations">
    <eClassifiers xsi:type="ecore:EClass" name="Collaboration" eSuperTypes="/1/GeneralizableElement /1/Namespace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="usedCollaboration" ordered="false" upperBound="-1" eType="/4/Collaboration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="representedOperation" ordered="false" eType="/1/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="representedClassifier" ordered="false" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" ordered="false" upperBound="-1" eType="/4/Interaction" containment="true" eOpposite="/4/Interaction/context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainingElement" ordered="false" upperBound="-1" eType="/1/ModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassifierRole" eSuperTypes="/1/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="availableContents" ordered="false" upperBound="-1" eType="/1/ModelElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1" upperBound="-1" eType="/1/Classifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conformingInstance" ordered="false" upperBound="-1" eType="/3/Instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="availableFeature" ordered="false" upperBound="-1" eType="/1/Feature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" ordered="false" eType="/2/Multiplicity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssociationRole" eSuperTypes="/1/Association">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" eType="/1/Association"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conformingLink" ordered="false" upperBound="-1" eType="/3/Link"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false" upperBound="-1" eType="/4/Message" eOpposite="/4/Message/communicationConnection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" ordered="false" eType="/2/Multiplicity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssociationEndRole" eSuperTypes="/1/AssociationEnd">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" eType="/1/AssociationEnd"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="availableQualifier" ordered="false" upperBound="-1" eType="/1/Attribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collaborationMultiplicity" ordered="false" eType="/2/Multiplicity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" ordered="false" lowerBound="1" eType="/4/Interaction" eOpposite="/4/Interaction/message"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conformingStimulus" ordered="false" upperBound="-1" eType="/3/Stimulus"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false" lowerBound="1" eType="/3/Action"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationConnection" ordered="false" eType="/4/AssociationRole" eOpposite="/4/AssociationRole/message"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activator" ordered="false" eType="/4/Message"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" ordered="false" lowerBound="1" eType="/4/ClassifierRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sender" ordered="false" lowerBound="1" eType="/4/ClassifierRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" ordered="false" upperBound="-1" eType="/4/Message"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false" lowerBound="1" upperBound="-1" eType="/4/Message" containment="true" eOpposite="/4/Message/interaction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false" lowerBound="1" eType="/4/Collaboration" eOpposite="/4/Collaboration/interaction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionInstanceSet" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" ordered="false" eType="/4/Interaction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false" lowerBound="1" eType="/4/CollaborationInstanceSet" eOpposite="/4/CollaborationInstanceSet/interactionInstanceSet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participatingStimulus" ordered="false" lowerBound="1" upperBound="-1" eType="/3/Stimulus"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollaborationInstanceSet" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collaboration" ordered="false" eType="/4/Collaboration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainingElement" ordered="false" upperBound="-1" eType="/1/ModelElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participatingInstance" ordered="false" lowerBound="1" upperBound="-1" eType="/3/Instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactionInstanceSet" ordered="false" upperBound="-1" eType="/4/InteractionInstanceSet" containment="true" eOpposite="/4/InteractionInstanceSet/context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participatingLink" ordered="false" upperBound="-1" eType="/3/Link"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
