extract:
	${tooldir}/rng2bgf ../source/grammar/highlevelnet.pntd ext.bgf
	${tooldir}/mergebgf ext.bgf ../lists/grammar.bgf ../strings/grammar.bgf ../arbitrarydeclarations/grammar.bgf ../symmetricnet/grammar.bgf grammar.bgf

include ../../Makefile.grammar
