extract:

fetch:
	rm -f fetched/*.g4
	https://raw.githubusercontent.com/antlr/grammars-v4/master/r/R.g4 > fetched/R.g4
	https://raw.githubusercontent.com/antlr/grammars-v4/master/r/RFilter.g4 > fetched/RFilter.g4
