extract:
	${tooldir}/txl2bgf ../malton-dahn/C/Txl/C.Grm ext.bgf
	${tooldir}/txl2bgf ../malton-dahn/C/Txl/c.Txl root.bgf
	${tooldir}/mergebgf ext.bgf root.bgf grammar.bgf

include ../../Makefile.grammar
