<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="CFG">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="/0/AbstractNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inNode" ordered="false" eType="/0/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outNode" ordered="false" eType="/0/Node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalNode" eSuperTypes="/0/AbstractNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trueConditionNode" ordered="false" lowerBound="1" eType="/0/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="falseConditionNode" ordered="false" lowerBound="1" eType="/0/Node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
</xmi:XMI>
