extract:

fetch:
	rm -f fetched/*
	wget http://www.omg.org/spec/KDM/20080201/KDM.actionXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.buildXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.codeXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.conceptualXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.coreXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.dataXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.eventXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.kdmXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.platformXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.sourceXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.structureXMI.xsd
	wget http://www.omg.org/spec/KDM/20080201/KDM.uiXMI.xsd
	mv *.xsd fetched/
