<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="DoDAF">
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="view" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoDAFModel" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="document" ordered="false" upperBound="-1" eType="/0/Document" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sfd" ordered="false" upperBound="-1" eType="/0/SystemFunctionalityDescription" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="amSpecification" ordered="false" upperBound="-1" eType="/0/AMSpecification" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sd" ordered="false" upperBound="-1" eType="/0/SystemDocument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="task" ordered="false" upperBound="-1" eType="/0/Task" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iaDocument" ordered="false" upperBound="-1" eType="/0/InformationAssetDocument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" ordered="false" upperBound="-1" eType="/0/Position" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="occupation" ordered="false" upperBound="-1" eType="/0/Occupation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ad" ordered="false" upperBound="-1" eType="/0/ArchitectureDocument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" ordered="false" upperBound="-1" eType="/0/System" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="am" ordered="false" upperBound="-1" eType="/0/AM" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="spas" ordered="false" upperBound="-1" eType="/0/SystemPAStandard" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="its" ordered="false" upperBound="-1" eType="/0/InformationTechnologyStandard" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="orpa" ordered="false" upperBound="-1" eType="/0/OperationalRolePA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ptcn" ordered="false" upperBound="-1" eType="/0/PersonTypeCapabilityNorm" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cites" ordered="false" upperBound="-1" eType="/0/InformationAssetDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="describes" ordered="false" upperBound="-1" eType="/0/SystemDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="records" ordered="false" upperBound="-1" eType="/0/ArchitectureDocument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isTheReferenceFor" ordered="false" upperBound="-1" eType="/0/IE" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isThePrimaryReferenceFor" ordered="false" upperBound="-1" eType="/0/PA" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemFunctionalityDescription" eSuperTypes="/0/Document"/>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionalSpecification" eSuperTypes="/0/Document">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayBeA" ordered="false" lowerBound="1" eType="/0/SystemDocument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AMSpecification" eSuperTypes="/0/Document">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isUsedIn" ordered="false" upperBound="-1" eType="/0/FunctionalSpecification" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemDocument" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArchitectureDocument" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isDesignedToProvide" ordered="false" upperBound="-1" eType="/0/SystemPA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isDescribedBy" ordered="false" upperBound="-1" eType="/0/SystemDocument"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemPA" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isDefinedUsing" ordered="false" upperBound="-1" eType="/0/SystemPAStandard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IE" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isAssociatedWith" ordered="false" upperBound="-1" eType="/0/AMIERole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isOrdinateOf" ordered="false" upperBound="-1" eType="/0/IE" eOpposite="/0/IE/isSubordinateOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isSubordinateOf" ordered="false" upperBound="-1" eType="/0/IE" eOpposite="/0/IE/isOrdinateOf"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AMIERole" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="defines" ordered="false" upperBound="-1" eType="/0/AMPA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isRepresentedBy" ordered="false" upperBound="-1" eType="/0/AMIERoleGraphic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AMIERoleGraphic" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="/0/AMIERole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isTheInputThatIsDefinedBy" ordered="false" upperBound="-1" eType="/0/Output" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="information" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="/0/AMIERole">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="information" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InformationAssetDocument" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="AMPA" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isOrdinateOf" ordered="false" upperBound="-1" eType="/0/AMPA" eOpposite="/0/AMPA/isSubordinateOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isSubordinateOf" ordered="false" upperBound="-1" eType="/0/AMPA" eOpposite="/0/AMPA/isOrdinateOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defines" ordered="false" upperBound="-1" eType="/0/AMIERole" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isRepresentedBy" ordered="false" upperBound="-1" eType="/0/AMPAGraphic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AMPAGraphic" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="PA" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isParentFor" ordered="false" upperBound="-1" eType="/0/PA" eOpposite="/0/PA/isChildFor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isChildFor" ordered="false" upperBound="-1" eType="/0/PA" eOpposite="/0/PA/isParentFor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isIncludedIn" ordered="false" upperBound="-1" eType="/0/AMPA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isAssignedTo" ordered="false" upperBound="-1" eType="/0/SystemPA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="represents" ordered="false" upperBound="-1" eType="/0/ArchitectureBusinessSubFunction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correspondsTo" ordered="false" upperBound="-1" eType="/0/PATask"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="has" ordered="false" upperBound="-1" eType="/0/PACapability" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isPerformedBy" ordered="false" upperBound="-1" eType="/0/OperationalRolePA"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PACapability" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="AM" eSuperTypes="/0/InformationAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isCitedBy" ordered="false" upperBound="-1" eType="/0/PATask" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifies" ordered="false" upperBound="-1" eType="/0/AMSpecification"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includes" ordered="false" upperBound="-1" eType="/0/AMPA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isUsedToDescribe" ordered="false" upperBound="-1" eType="/0/SystemFunctionalityDescription"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defines" ordered="false" upperBound="-1" eType="/0/LineOfBusiness" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InformationAsset" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isCitedIn" ordered="false" upperBound="-1" eType="/0/InformationAssetDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="describes" ordered="false" upperBound="-1" eType="/0/DataStore" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataStore" eSuperTypes="/0/PA"/>
    <eClassifiers xsi:type="ecore:EClass" name="SystemFunction" eSuperTypes="/0/PA"/>
    <eClassifiers xsi:type="ecore:EClass" name="SystemPAStandard" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isUsedToDefine" ordered="false" upperBound="-1" eType="/0/InformationTechnologyStandard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InformationTechnologyStandard" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="isUsedToDefine" ordered="false" upperBound="-1" eType="/0/SystemPAStandard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LineOfBusiness" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliesToTask" ordered="false" upperBound="-1" eType="/0/Task"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliesToBS" ordered="false" upperBound="-1" eType="/0/BusinessSubfunction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelIdentifier" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="references" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correspondsTo" ordered="false" upperBound="-1" eType="/0/PATask"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="supports" ordered="false" upperBound="-1" eType="/0/TaskMissionArea"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HumanBehaviourTask" eSuperTypes="/0/Task"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalCapabilityTask" eSuperTypes="/0/Task"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaskMissionArea" eSuperTypes="/0/Task">
      <eStructuralFeatures xsi:type="ecore:EReference" name="hasContributionFrom" ordered="false" upperBound="-1" eType="/0/OperationalCapabilityTask" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PATask" eSuperTypes="/0/Task"/>
    <eClassifiers xsi:type="ecore:EClass" name="BusinessSubfunction" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliesTo" ordered="false" upperBound="-1" eType="/0/ArchitectureBusinessSubFunction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArchitectureBusinessSubFunction" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalRolePA" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalRole" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="performs" ordered="false" upperBound="-1" eType="/0/OperationalRolePA" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isPerformedByOTOR" ordered="false" upperBound="-1" eType="/0/OrganizationTypeOperationalRole" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isPerformedByOOR" ordered="false" upperBound="-1" eType="/0/OrganizationOperationalRole" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrganizationTypeOperationalRole" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrganizationOperationalRole" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Occupation" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayBeCitedForOR" ordered="false" upperBound="-1" eType="/0/OperationalRole" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayBeCitedForPT" ordered="false" upperBound="-1" eType="/0/PersonType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonType" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayBeCitedFor" ordered="false" upperBound="-1" eType="/0/OperationalRole" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="performsTo" ordered="false" upperBound="-1" eType="/0/PersonTypeCapabilityNorm" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="can" ordered="false" upperBound="-1" eType="/0/Skill" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonTypeCapabilityNorm" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Skill" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayBeCitedFor" ordered="false" upperBound="-1" eType="/0/OperationalRole" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mayBeCitedFor" ordered="false" upperBound="-1" eType="/0/OperationalRole" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
