extract:
	${tooldir}/rscd2bgf ${rascaldir}/logic/ast/Booleans.rsc ext.bool.bgf
	${tooldir}/rscd2bgf ${rascaldir}/logic/ast/Propositions.rsc ext.prop.bgf
	${tooldir}/mergebgf ext.*.bgf grammar.bgf

include ../../Makefile.grammar
