extract:

fetch:
	wget http://heanet.dl.sourceforge.net/project/translatecim/translatecim/0.9.1/translatecim-0.9.1.tar.gz
	gunzip translatecim-0.9.1.tar.gz
	tar xfv translatecim-0.9.1.tar
	mv translatecim-0.9.1/src/test/resources/*.mof fetched/
	mv translatecim-0.9.1/src/test/resources/Core/*.mof fetched/
	rm -rf translatecim-0.9.1 translatecim-0.9.1.tar
