<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="ExtendedUMLCorePackage">
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" lowerBound="1" eType="/0/Name"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Name"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssociationEnd" eSuperTypes="/0/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aggregation" ordered="false" lowerBound="1" eType="/0/AggregationKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" ordered="false" lowerBound="1" eType="/0/Multiplicity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="changeable" ordered="false" lowerBound="1" eType="/0/ChangeableKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TargetScope" ordered="false" lowerBound="1" eType="/0/ScopeKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rfIntegrety" ordered="false" lowerBound="1" eType="/0/RlIntegretyKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rlIntegrety" ordered="false" lowerBound="1" eType="/0/RlIntegretyKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AggregationKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="Multiplicity"/>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeableKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="ScopeKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="RfIntegretyKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="RlIntegretyKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="/0/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="GeneralizableElement" eSuperTypes="/0/Namespace"/>
    <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="/0/GeneralizableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="/0/Classifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mutliplicity" ordered="false" lowerBound="1" eType="/0/Multiplicity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" ordered="false" upperBound="-1" eType="/0/Key" containment="true" eOpposite="/0/Key/classOwner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Key" abstract="true" eSuperTypes="/0/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classOwner" ordered="false" lowerBound="1" eType="/0/Class" eOpposite="/0/Class/key"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="/0/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="StructureFeature" eSuperTypes="/0/Feature"/>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" eSuperTypes="/0/Feature"/>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="/0/StructureFeature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" ordered="false" lowerBound="1" eType="/0/Expression"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isKey" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
