extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/6f1fc98546a91981a7c60c23c4cf874479e8848d/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
