<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="DocBook">
    <eClassifiers xsi:type="ecore:EClass" name="DocBook">
      <eStructuralFeatures xsi:type="ecore:EReference" name="books" lowerBound="1" upperBound="-1" eType="/0/Book" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Book">
      <eStructuralFeatures xsi:type="ecore:EReference" name="articles" lowerBound="1" upperBound="-1" eType="/0/Article" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TitledElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="/0/TitledElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sections_1" lowerBound="1" upperBound="-1" eType="/0/Sect1" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sect1" eSuperTypes="/0/TitledElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="paras" lowerBound="1" upperBound="-1" eType="/0/Para" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Para">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
