extract: 

get:
	wget http://www.cse.chalmers.se/~hallgren/CactusExample/Haskell/HaskellParser.y
	wget http://www.cse.chalmers.se/~hallgren/CactusExample/Haskell/HaskellLexer.x
	mv Haskell* fetched/

include ../../Makefile.grammar
