<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="UIML">
    <eClassifiers xsi:type="ecore:EClass" name="UIML">
      <eStructuralFeatures xsi:type="ecore:EReference" name="head" ordered="false" eType="/0/Header" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templates" ordered="false" upperBound="-1" eType="/4/Template" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" ordered="false" upperBound="-1" eType="/2/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="peers" ordered="false" upperBound="-1" eType="/1/Peer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Header">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metas" ordered="false" upperBound="-1" eType="/0/MetaData" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetaData">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="Peer">
    <eClassifiers xsi:type="ecore:EClass" name="Peer" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="presentations" ordered="false" upperBound="-1" eType="/1/Presentation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logics" ordered="false" upperBound="-1" eType="/1/Logic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Presentation" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dClasses" ordered="false" upperBound="-1" eType="/1/DClass" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Logic" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dComponents" ordered="false" upperBound="-1" eType="/1/DComponent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DComponent" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsTo" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dMethods" ordered="false" upperBound="-1" eType="/1/DMethod" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DClass" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsTo" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsType" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dMethods" ordered="false" upperBound="-1" eType="/1/DMethod" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dProperties" ordered="false" upperBound="-1" eType="/1/DProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" ordered="false" upperBound="-1" eType="/2/Event" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="listeners" ordered="false" upperBound="-1" eType="/1/Listener" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsType" ordered="false" unique="false" lowerBound="1" eType="/1/MapsTypeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsTo" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dMethods" ordered="false" upperBound="-1" eType="/1/DMethod" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dParams" ordered="false" upperBound="-1" eType="/1/DParam" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DMethod" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsTo" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dParams" upperBound="-1" eType="/1/DParam" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false" eType="/1/Script" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DParam">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Script" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" unique="false" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Listener">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attacher" ordered="false" unique="false" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UsedInTagKind">
      <eLiterals name="event" value="1"/>
      <eLiterals name="listener" value="2"/>
      <eLiterals name="part" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MapsTypeKind">
      <eLiterals name="attribute" value="1"/>
      <eLiterals name="getMethod" value="2"/>
      <eLiterals name="setMethod" value="3"/>
      <eLiterals name="method" value="4"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="Interface">
    <eClassifiers xsi:type="ecore:EClass" name="ExtensibleElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="LocalSource" eSuperTypes="/2/Source">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" lowerBound="1" eType="/2/ExtensibleElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RemoteSource" eSuperTypes="/2/Source">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="structure" ordered="false" upperBound="-1" eType="/2/Structure" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false" upperBound="-1" eType="/2/Style" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" upperBound="-1" eType="/2/Content" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false" upperBound="-1" eType="/2/Behavior" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1" eType="/2/Part" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="wherePart" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false" eType="/2/Style" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" eType="/2/Content" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false" eType="/2/Behavior" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" ordered="false" upperBound="-1" eType="/2/Part" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="repeats" ordered="false" upperBound="-1" eType="/2/Repeat" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false" upperBound="-1" eType="/2/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" ordered="false" unique="false" upperBound="-1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" ordered="false" upperBound="-1" eType="/2/Part"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" ordered="false" upperBound="-1" eType="/2/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constants" ordered="false" upperBound="-1" eType="/2/Constant" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false" upperBound="-1" eType="/2/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" ordered="false" upperBound="-1" eType="/2/Reference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calls" ordered="false" upperBound="-1" eType="/2/Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterators" ordered="false" upperBound="-1" eType="/2/Iterator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Content" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1" eType="/2/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Behavior" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1" eType="/2/Rule" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Repeat">
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" ordered="false" lowerBound="1" eType="/2/Iterator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" ordered="false" lowerBound="1" upperBound="-1" eType="/2/Part" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1" eType="/2/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" eType="/2/Constant"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="export" ordered="false" unique="false" eType="/2/ExportKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" lowerBound="1" eType="/2/Condition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false" lowerBound="1" eType="/2/Action" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventCondition" eSuperTypes="/2/Condition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" lowerBound="1" eType="/2/Event" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualCondition" eSuperTypes="/2/Condition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="equal" ordered="false" lowerBound="1" eType="/2/Equal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpCondition" eSuperTypes="/2/Condition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="op" ordered="false" lowerBound="1" eType="/2/Operation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="Action_1" eSuperTypes="/2/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" eType="/2/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false" upperBound="-1" eType="/2/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calls" ordered="false" upperBound="-1" eType="/2/Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="restructures" ordered="false" upperBound="-1" eType="/2/Restructure" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action_2" eSuperTypes="/2/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="whenTrue" ordered="false" eType="/2/WhenTrue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="whenFalse" ordered="false" eType="/2/WhenFalse"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="byDefault" ordered="false" eType="/2/ByDefault"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Call">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" eType="/2/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false" lowerBound="1" eType="/2/Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" ordered="false" lowerBound="1" eType="/2/Reference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="call" ordered="false" lowerBound="1" eType="/2/Call"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="op" ordered="false" lowerBound="1" eType="/2/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" lowerBound="1" eType="/2/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstantParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" lowerBound="1" eType="/2/Constant"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorParameter" eSuperTypes="/2/Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" ordered="false" lowerBound="1" eType="/2/Iterator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Iterator" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstantIterator" eSuperTypes="/2/Iterator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" lowerBound="1" eType="/2/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyIterator" eSuperTypes="/2/Iterator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false" lowerBound="1" eType="/2/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallIterator" eSuperTypes="/2/Iterator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="call" ordered="false" lowerBound="1" eType="/2/Call" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextIterator" eSuperTypes="/2/Iterator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/3/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" ordered="false" unique="false" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parts" ordered="false" upperBound="-1" eType="/2/Part"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Equal" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" lowerBound="1" eType="/2/Event"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualToConstant" eSuperTypes="/2/Equal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" lowerBound="1" eType="/2/Constant"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualToProperty" eSuperTypes="/2/Equal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false" lowerBound="1" eType="/2/Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualToReference" eSuperTypes="/2/Equal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" ordered="false" lowerBound="1" eType="/2/Reference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EqualToOperation" eSuperTypes="/2/Equal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="op" ordered="false" lowerBound="1" eType="/2/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/3/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constants" ordered="false" upperBound="-1" eType="/2/Constant" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false" upperBound="-1" eType="/2/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" ordered="false" upperBound="-1" eType="/2/Reference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calls" ordered="false" upperBound="-1" eType="/2/Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ops" ordered="false" upperBound="-1" eType="/2/Operation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" ordered="false" upperBound="-1" eType="/2/Event" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Restructure" eSuperTypes="/2/ExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="how" ordered="false" unique="false" eType="/2/HowKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="atPart" ordered="false" eType="/2/Part"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wherePart" ordered="false" eType="/2/Part"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" eType="/2/Source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" ordered="false" eType="/4/Template" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Branch">
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false" upperBound="-1" eType="/2/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calls" ordered="false" upperBound="-1" eType="/2/Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="restructure" ordered="false" eType="/2/Restructure" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="op" ordered="false" eType="/2/Operation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="equal" ordered="false" eType="/2/Equal" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" eType="/2/Event" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhenTrue" eSuperTypes="/2/Branch"/>
    <eClassifiers xsi:type="ecore:EClass" name="WhenFalse" eSuperTypes="/2/Branch"/>
    <eClassifiers xsi:type="ecore:EClass" name="ByDefault" eSuperTypes="/2/Branch"/>
    <eClassifiers xsi:type="ecore:EEnum" name="HowKind">
      <eLiterals name="append" value="1"/>
      <eLiterals name="cascade" value="2"/>
      <eLiterals name="replace" value="3"/>
      <eLiterals name="union" value="4"/>
      <eLiterals name="delete" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ExportKind">
      <eLiterals name="hidden" value="1"/>
      <eLiterals name="optional" value="2"/>
      <eLiterals name="required" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="WhereKind">
      <eLiterals name="first" value="1"/>
      <eLiterals name="last" value="2"/>
      <eLiterals name="before" value="3"/>
      <eLiterals name="after" value="4"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
  <ecore:EPackage name="Template">
    <eClassifiers xsi:type="ecore:EClass" name="Template" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" eType="/3/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false" lowerBound="1" eType="/2/Behavior" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DClassTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dClass" ordered="false" lowerBound="1" eType="/1/DClass" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DComponentTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dComponent" ordered="false" lowerBound="1" eType="/1/DComponent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstantTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constant" ordered="false" lowerBound="1" eType="/2/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" lowerBound="1" eType="/2/Content" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" ordered="false" lowerBound="1" eType="/2/Interface" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="logic" ordered="false" lowerBound="1" eType="/1/Logic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PartTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" ordered="false" lowerBound="1" eType="/2/Part" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PeerTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="peer" ordered="false" lowerBound="1" eType="/1/Peer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PresentationTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="presentation" ordered="false" lowerBound="1" eType="/1/Presentation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false" lowerBound="1" eType="/2/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RestructureTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="restructure" ordered="false" lowerBound="1" eType="/2/Restructure" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuleTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" ordered="false" lowerBound="1" eType="/2/Rule" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScriptTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false" lowerBound="1" eType="/1/Script" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="structure" ordered="false" lowerBound="1" eType="/2/Structure" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StyleTemplate" eSuperTypes="/4/Template">
      <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false" lowerBound="1" eType="/2/Style" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
