extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/aeaa33414f6a36599953da71049f4c7fa5e12508/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
