extract:
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/AbstractKind.rsc ext.AbstractKind.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/AbstractName.rsc ext.AbstractName.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/AbstractType.rsc ext.AbstractType.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/CheckTypes.rsc ext.CheckTypes.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/ConvertType.rsc ext.ConvertType.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/TestChecker.rsc ext.TestChecker.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/TypeExceptions.rsc ext.TypeExceptions.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/TypeInstantiation.rsc ext.TypeInstantiation.bgf
	${tooldir}/rscd2bgf ${rascaldir}/rascal/types/TypeSignature.rsc ext.TypeSignature.bgf
	${tooldir}/mergebgf ext.*.bgf grammar.bgf

include ../../Makefile.grammar