<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Family">
  <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" ordered="false" upperBound="-1" eType="//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false" unique="false" lowerBound="1" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="closestFriend" ordered="false" lowerBound="1" eType="//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddresses" ordered="false" unique="false" upperBound="-1" eType="//String"/>
  </eClassifiers>
</ecore:EPackage>
