<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="UMLWithReuseContrats">
    <eClassifiers xsi:type="ecore:EClass" name="ReuseContract" eSuperTypes="/0/Dependency">
      <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" ordered="false" lowerBound="1" eType="/0/ProviderClause"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false" lowerBound="1" eType="/0/ReuserClause"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dependency">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningDependency" ordered="false" eType="/0/Dependency" eOpposite="/0/Dependency/subDependency"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subDependency" ordered="false" upperBound="-1" eType="/0/Dependency" containment="true" eOpposite="/0/Dependency/owningDependency"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProviderClause" eSuperTypes="/0/Package"/>
    <eClassifiers xsi:type="ecore:EClass" name="Package"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReuserClause" eSuperTypes="/0/Package"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeProvider" eSuperTypes="/0/ProviderClause">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcontract" ordered="false" lowerBound="1" eType="/0/ReuseContract" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BasicProvider" eSuperTypes="/0/ProviderClause"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeReuser" eSuperTypes="/0/ReuserClause">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subreuser" upperBound="-1" eType="/0/ReuserClause" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BasicReuser" eSuperTypes="/0/ReuserClause"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
