tooldir    = ~/projects/slps/shared/tools
gendir     = ../../../slps/shared/generators
dialectdir = ../../../slps/shared/edd
sdflibdir  = ~/projects/sdf-library/trunk/library/languages
hunter     = ~/projects/slps/topics/recovery/hunter/hunter.py
rascaldir  = ~/projects/_other/rascal/src/org/rascalmpl/library/lang
fldir      = ../../../slps/topics/fl

clean:
	rm -f *.bgf *.bnf *.html intermediate.lll tmp.xml *prepared* tgt.*

test:
	ls -1 *.bgf | xargs -n1 ${tooldir}/validate bgf
