<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IntegratingTroposActorConcept">
  <eClassifiers xsi:type="ecore:EClass" name="Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="//Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="occupy" ordered="false" lowerBound="1" eType="//Position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="play" ordered="false" upperBound="-1" eType="//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="//Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cover" ordered="false" upperBound="-1" eType="//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="//Actor"/>
</ecore:EPackage>
