extract:

fetch:
	curl https://xqgrammar.googlecode.com/svn/trunk/xqgrammar/src/main/antlr3/xqgrammar/XQ.g > fetched/XQ.g
	curl https://xqgrammar.googlecode.com/svn/trunk/xqgrammar/src/main/antlr3/xqgrammar/XMLexer.g > fetched/XMLexer.g
