<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="EG_MOF">
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionGraph">
      <eStructuralFeatures xsi:type="ecore:EReference" name="node" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Node" containment="true" eOpposite="/0/Node/executionGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeNested" ordered="false" lowerBound="1" eType="/0/Node" eOpposite="/0/Node/nested"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node">
      <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" ordered="false" upperBound="-1" eType="/0/Node" eOpposite="/0/Node/successor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="successor" ordered="false" upperBound="-1" eType="/0/Node" eOpposite="/0/Node/predecessor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executionGraph" ordered="false" lowerBound="1" eType="/0/ExecutionGraph" eOpposite="/0/ExecutionGraph/node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nested" ordered="false" upperBound="-1" eType="/0/ExecutionGraph" eOpposite="/0/ExecutionGraph/nodeNested"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="/0/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="/0/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="/0/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="Basic" eSuperTypes="/0/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Acquire" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Release" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Split" eSuperTypes="/0/Control"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
</xmi:XMI>
