<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="EAI">
    <eClassifiers xsi:type="ecore:EClass" name="FCMSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="EAISource" eSuperTypes="/0/FCMSource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resources" ordered="false" upperBound="-1" eType="/0/EAIResource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FCMSink"/>
    <eClassifiers xsi:type="ecore:EClass" name="EAISink" eSuperTypes="/0/FCMSink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resources" ordered="false" upperBound="-1" eType="/0/EAIResource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAIResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="EAIQueue" eSuperTypes="/0/EAIResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
