extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/4e5537b1174a7e9444e93f5305925920d51b523a/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
