extract:

fetch:
	rm -f fetched/*
	wget http://www.omg.org/spec/KDM/20090503/KDM.actionXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.buildXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.codeXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.conceptualXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.coreXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.dataXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.eventXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.kdmXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.platformXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.sourceXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.structureXMI.xsd
	wget http://www.omg.org/spec/KDM/20090503/KDM.uiXMI.xsd
	mv *.xsd fetched/
