<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="QoSStatement">
    <eClassifiers xsi:type="ecore:EClass" name="QoSStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relation" ordered="false" lowerBound="1" eType="/0/CoumpoundQoSStatement" eOpposite="/0/CoumpoundQoSStatement/statement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1" eType="/0/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SingleQoSStatement" eSuperTypes="/0/QoSStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contraint" ordered="false" lowerBound="1" eType="/0/QoSContraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoumpoundQoSStatement" eSuperTypes="/0/QoSStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statement" ordered="false" lowerBound="2" upperBound="-1" eType="/0/QoSStatement" containment="true" eOpposite="/0/QoSStatement/relation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="QoSContraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualification" ordered="false" lowerBound="1" eType="/0/QualificationKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QualificationKind" eSuperTypes="/0/QoSCharacteristic">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSCharacteristic"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
