<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="XSD">
    <eClassifiers xsi:type="ecore:EClass" name="XSDAnnotation" eSuperTypes="/0/XSDComponent /0/XSDRedefineContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationInformation" upperBound="-1" eType="/0/XSDDOMElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="userInformation" upperBound="-1" eType="/0/XSDDOMElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" upperBound="-1" eType="/0/DOMAttr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDAttributeDeclaration" eSuperTypes="/0/XSDFeature /0/XSDSchemaContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeDeclarationReference" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousTypeDefinition" ordered="false" eType="/0/XSDSimpleTypeDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinition" ordered="false" lowerBound="1" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedAttributeDeclaration" ordered="false" lowerBound="1" eType="/0/XSDAttributeDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDAttributeGroupContent" abstract="true" eSuperTypes="/0/XSDConcreteComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDAttributeGroupDefinition" eSuperTypes="/0/XSDRedefinableComponent /0/XSDAttributeGroupContent /0/XSDRedefineContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeGroupDefinitionReference" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/0/XSDAttributeGroupContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeUses" upperBound="-1" eType="/0/XSDAttributeUse"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeWildcardContent" ordered="false" eType="/0/XSDWildcard" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeWildcard" ordered="false" eType="/0/XSDWildcard"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedAttributeGroupDefinition" ordered="false" lowerBound="1" eType="/0/XSDAttributeGroupDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticWildcard" ordered="false" eType="/0/XSDWildcard" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDAttributeUse" eSuperTypes="/0/XSDComponent /0/XSDAttributeGroupContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/Value"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" ordered="false" unique="false" eType="/0/XSDConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="use" ordered="false" unique="false" eType="/0/XSDAttributeUseCategory"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeDeclaration" ordered="false" lowerBound="1" eType="/0/XSDAttributeDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" lowerBound="1" eType="/0/XSDAttributeDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDBoundedFacet" eSuperTypes="/0/XSDFundamentalFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDCardinalityFacet" eSuperTypes="/0/XSDFundamentalFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/XSDCardinality"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDComplexTypeContent" abstract="true" eSuperTypes="/0/XSDComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDComplexTypeDefinition" eSuperTypes="/0/XSDTypeDefinition /0/XSDScope">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationMethod" ordered="false" unique="false" eType="/0/XSDDerivationMethod"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" upperBound="-1" eType="/0/XSDComplexFinal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentTypeCategory" ordered="false" unique="false" eType="/0/XSDContentTypeCategory"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prohibitedSubstitutions" upperBound="-1" eType="/0/XSDProhibitedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalFinal" upperBound="-1" eType="/0/XSDComplexFinal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="block" upperBound="-1" eType="/0/XSDProhibitedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contentAnnotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseTypeDefinition" ordered="false" lowerBound="1" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" eType="/0/XSDComplexTypeContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contentType" ordered="false" eType="/0/XSDComplexTypeContent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeUses" upperBound="-1" eType="/0/XSDAttributeUse"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeContents" upperBound="-1" eType="/0/XSDAttributeGroupContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeWildcard" ordered="false" eType="/0/XSDWildcard"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeWildcardContent" ordered="false" eType="/0/XSDWildcard" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootTypeDefinition" ordered="false" lowerBound="1" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticParticle" ordered="false" eType="/0/XSDParticle" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticWildcard" ordered="false" eType="/0/XSDWildcard" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDComponent" abstract="true" eSuperTypes="/0/XSDConcreteComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDConcreteComponent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" ordered="false" unique="false" eType="/0/XSDDOMElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" ordered="false" eType="/0/XSDConcreteComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootContainer" ordered="false" lowerBound="1" eType="/0/XSDConcreteComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="schema" ordered="false" eType="/0/XSDSchema"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diagnostics" upperBound="-1" eType="/0/XSDDiagnostic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDConstrainingFacet" abstract="true" eSuperTypes="/0/XSDFacet"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDDiagnostic" eSuperTypes="/0/XSDConcreteComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" ordered="false" unique="false" eType="/0/XSDDiagnosticSeverity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" ordered="false" unique="false" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" ordered="false" unique="false" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="node" ordered="false" unique="false" eType="/0/DOMNode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotationURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="substitutions" upperBound="-1" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1" upperBound="-1" eType="/0/XSDConcreteComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="primaryComponent" ordered="false" lowerBound="1" eType="/0/XSDConcreteComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDElementDeclaration" eSuperTypes="/0/XSDFeature /0/XSDSchemaContent /0/XSDTerm">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nillable" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disallowedSubstitutions" upperBound="-1" eType="/0/XSDDisallowedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="substitutionGroupExclusions" upperBound="-1" eType="/0/XSDSubstitutionGroupExclusions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalFinal" upperBound="-1" eType="/0/XSDProhibitedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="block" upperBound="-1" eType="/0/XSDDisallowedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementDeclarationReference" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="circular" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="anonymousTypeDefinition" ordered="false" eType="/0/XSDTypeDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinition" ordered="false" lowerBound="1" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="identityConstraintDefinitions" upperBound="-1" eType="/0/XSDIdentityConstraintDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedElementDeclaration" ordered="false" lowerBound="1" eType="/0/XSDElementDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitutionGroupAffiliation" ordered="false" eType="/0/XSDElementDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitutionGroup" upperBound="-1" eType="/0/XSDElementDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDEnumerationFacet" eSuperTypes="/0/XSDRepeatableFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1" eType="/0/Value"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDFacet" abstract="true" eSuperTypes="/0/XSDComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="facetName" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveValue" ordered="false" unique="false" eType="/0/Value"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="simpleTypeDefinition" ordered="false" eType="/0/XSDSimpleTypeDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDFeature" abstract="true" eSuperTypes="/0/XSDNamedComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/Value"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" ordered="false" unique="false" eType="/0/XSDConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="form" ordered="false" unique="false" eType="/0/XSDForm"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="global" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureReference" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" ordered="false" eType="/0/XSDScope"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedFeature" ordered="false" lowerBound="1" eType="/0/XSDFeature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/XSDTypeDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDFixedFacet" abstract="true" eSuperTypes="/0/XSDConstrainingFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixed" ordered="false" unique="false" eType="/2/EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDFractionDigitsFacet" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDFundamentalFacet" abstract="true" eSuperTypes="/0/XSDFacet"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDIdentityConstraintDefinition" eSuperTypes="/0/XSDNamedComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identityConstraintCategory" ordered="false" unique="false" eType="/0/XSDIdentityConstraintCategory"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedKey" ordered="false" eType="/0/XSDIdentityConstraintDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selector" ordered="false" lowerBound="1" eType="/0/XSDXPathDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1" upperBound="-1" eType="/0/XSDXPathDefinition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDImport" eSuperTypes="/0/XSDSchemaDirective">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDInclude" eSuperTypes="/0/XSDSchemaCompositor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDLengthFacet" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMaxExclusiveFacet" eSuperTypes="/0/XSDMaxFacet"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMaxFacet" abstract="true" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/Value"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusive" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusive" ordered="false" unique="false" eType="/2/EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMaxInclusiveFacet" eSuperTypes="/0/XSDMaxFacet"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMaxLengthFacet" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMinExclusiveFacet" eSuperTypes="/0/XSDMinFacet"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMinFacet" abstract="true" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/Value"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusive" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusive" ordered="false" unique="false" eType="/2/EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMinInclusiveFacet" eSuperTypes="/0/XSDMinFacet"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDMinLengthFacet" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDModelGroup" eSuperTypes="/0/XSDTerm">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compositor" ordered="false" unique="false" eType="/0/XSDCompositor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/0/XSDParticle" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="particles" lowerBound="1" upperBound="-1" eType="/0/XSDParticle"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDModelGroupDefinition" eSuperTypes="/0/XSDRedefinableComponent /0/XSDParticleContent /0/XSDRedefineContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelGroupDefinitionReference" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelGroup" ordered="false" lowerBound="1" eType="/0/XSDModelGroup" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedModelGroupDefinition" ordered="false" lowerBound="1" eType="/0/XSDModelGroupDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDNamedComponent" abstract="true" eSuperTypes="/0/XSDComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliasName" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uRI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliasURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDNotationDeclaration" eSuperTypes="/0/XSDNamedComponent /0/XSDSchemaContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemIdentifier" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicIdentifier" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDNumericFacet" eSuperTypes="/0/XSDFundamentalFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDOrderedFacet" eSuperTypes="/0/XSDFundamentalFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/XSDOrdered"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDParticle" eSuperTypes="/0/XSDComplexTypeContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minOccurs" ordered="false" unique="false" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurs" ordered="false" unique="false" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false" lowerBound="1" eType="/0/XSDParticleContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="term" ordered="false" lowerBound="1" eType="/0/XSDTerm"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDParticleContent" abstract="true" eSuperTypes="/0/XSDConcreteComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDPatternFacet" eSuperTypes="/0/XSDRepeatableFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDRedefinableComponent" abstract="true" eSuperTypes="/0/XSDNamedComponent /0/XSDRedefineContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="circular" ordered="false" unique="false" eType="/2/EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDRedefineContent" abstract="true" eSuperTypes="/0/XSDSchemaContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDRedefine" eSuperTypes="/0/XSDSchemaCompositor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="/0/XSDAnnotation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/0/XSDRedefineContent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDRepeatableFacet" abstract="true" eSuperTypes="/0/XSDConstrainingFacet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="/0/XSDAnnotation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDSchema" eSuperTypes="/0/XSDScope">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="document" ordered="false" unique="false" eType="/0/XSDDOMDocument"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaLocation" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeFormDefault" ordered="false" unique="false" eType="/0/XSDForm"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementFormDefault" ordered="false" unique="false" eType="/0/XSDForm"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finalDefault" upperBound="-1" eType="/0/XSDProhibitedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockDefault" upperBound="-1" eType="/0/XSDDisallowedSubstitutions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/0/XSDSchemaContent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementDeclarations" upperBound="-1" eType="/0/XSDElementDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeDeclarations" upperBound="-1" eType="/0/XSDAttributeDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeGroupDefinitions" upperBound="-1" eType="/0/XSDAttributeGroupDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinitions" upperBound="-1" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelGroupDefinitions" upperBound="-1" eType="/0/XSDModelGroupDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="identityConstraintDefinitions" upperBound="-1" eType="/0/XSDIdentityConstraintDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="notationDeclarations" upperBound="-1" eType="/0/XSDNotationDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="/0/XSDAnnotation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allDiagnostics" upperBound="-1" eType="/0/XSDDiagnostic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencingDirectives" upperBound="-1" eType="/0/XSDSchemaDirective"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootVersion" ordered="false" lowerBound="1" eType="/0/XSDSchema"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="originalVersion" ordered="false" eType="/0/XSDSchema"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incorporatedVersions" upperBound="-1" eType="/0/XSDSchema" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="schemaForSchema" ordered="false" lowerBound="1" eType="/0/XSDSchema"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDSchemaCompositor" abstract="true" eSuperTypes="/0/XSDSchemaDirective">
      <eStructuralFeatures xsi:type="ecore:EReference" name="incorporatedSchema" ordered="false" eType="/0/XSDSchema"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDSchemaContent" abstract="true" eSuperTypes="/0/XSDConcreteComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDSchemaDirective" abstract="true" eSuperTypes="/0/XSDSchemaContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaLocation" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedSchema" ordered="false" eType="/0/XSDSchema"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDScope" abstract="true" eSuperTypes="/0/XSDComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDSimpleTypeDefinition" eSuperTypes="/0/XSDTypeDefinition /0/XSDComplexTypeContent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variety" ordered="false" unique="false" eType="/0/XSDVariety"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" upperBound="-1" eType="/0/XSDSimpleFinal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalFinal" upperBound="-1" eType="/0/XSDSimpleFinal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFacets" upperBound="-1" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/0/XSDSimpleTypeDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="facetContents" upperBound="-1" eType="/0/XSDConstrainingFacet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1" eType="/0/XSDConstrainingFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberTypeDefinitions" upperBound="-1" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fundamentalFacets" lowerBound="1" upperBound="-1" eType="/0/XSDFundamentalFacet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseTypeDefinition" ordered="false" lowerBound="1" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypeDefinition" ordered="false" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="itemTypeDefinition" ordered="false" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootTypeDefinition" ordered="false" lowerBound="1" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minFacet" ordered="false" eType="/0/XSDMinFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxFacet" ordered="false" eType="/0/XSDMaxFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxInclusiveFacet" ordered="false" eType="/0/XSDMaxInclusiveFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minInclusiveFacet" ordered="false" eType="/0/XSDMinInclusiveFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minExclusiveFacet" ordered="false" eType="/0/XSDMinExclusiveFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxExclusiveFacet" ordered="false" eType="/0/XSDMaxExclusiveFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lengthFacet" ordered="false" eType="/0/XSDLengthFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="whiteSpaceFacet" ordered="false" eType="/0/XSDWhiteSpaceFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationFacets" upperBound="-1" eType="/0/XSDEnumerationFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="patternFacets" upperBound="-1" eType="/0/XSDPatternFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cardinalityFacet" ordered="false" lowerBound="1" eType="/0/XSDCardinalityFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="numericFacet" ordered="false" lowerBound="1" eType="/0/XSDNumericFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxLengthFacet" ordered="false" eType="/0/XSDMaxLengthFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="minLengthFacet" ordered="false" eType="/0/XSDMinLengthFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="totalDigitsFacet" ordered="false" eType="/0/XSDTotalDigitsFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fractionDigitsFacet" ordered="false" eType="/0/XSDFractionDigitsFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="orderedFacet" ordered="false" lowerBound="1" eType="/0/XSDOrderedFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundedFacet" ordered="false" lowerBound="1" eType="/0/XSDBoundedFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveMaxFacet" ordered="false" eType="/0/XSDMaxFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveWhiteSpaceFacet" ordered="false" eType="/0/XSDWhiteSpaceFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveMaxLengthFacet" ordered="false" eType="/0/XSDMaxLengthFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveFractionDigitsFacet" ordered="false" eType="/0/XSDFractionDigitsFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectivePatternFacet" ordered="false" eType="/0/XSDPatternFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveEnumerationFacet" ordered="false" eType="/0/XSDEnumerationFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveTotalDigitsFacet" ordered="false" eType="/0/XSDTotalDigitsFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveMinLengthFacet" ordered="false" eType="/0/XSDMinLengthFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveLengthFacet" ordered="false" eType="/0/XSDLengthFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectiveMinFacet" ordered="false" eType="/0/XSDMinFacet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticFacets" upperBound="-1" eType="/0/XSDFacet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDTerm" abstract="true" eSuperTypes="/0/XSDComponent /0/XSDParticleContent"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSDTotalDigitsFacet" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDTypeDefinition" abstract="true" eSuperTypes="/0/XSDRedefinableComponent /0/XSDRedefineContent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="derivationAnnotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="/0/XSDAnnotation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootType" ordered="false" lowerBound="1" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" ordered="false" lowerBound="1" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="simpleType" ordered="false" eType="/0/XSDSimpleTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="complexType" ordered="false" eType="/0/XSDParticle"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDWhiteSpaceFacet" eSuperTypes="/0/XSDFixedFacet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/0/XSDWhiteSpace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDWildcard" eSuperTypes="/0/XSDTerm">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceConstraintCategory" ordered="false" unique="false" eType="/0/XSDNamespaceConstraintCategory"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceConstraint" upperBound="-1" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processContents" ordered="false" unique="false" eType="/0/XSDProcessContents"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalNamespaceConstraint" upperBound="-1" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1" eType="/0/XSDAnnotation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDXPathDefinition" eSuperTypes="/0/XSDComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variety" ordered="false" unique="false" eType="/0/XSDXPathVariety"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/XSDAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="DOMAttr"/>
    <eClassifiers xsi:type="ecore:EDataType" name="XSDDOMDocument"/>
    <eClassifiers xsi:type="ecore:EDataType" name="XSDDOMElement"/>
    <eClassifiers xsi:type="ecore:EDataType" name="DOMNode"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Value"/>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDAttributeUseCategory">
      <eLiterals name="prohibited" value="1"/>
      <eLiterals name="optional" value="2"/>
      <eLiterals name="required" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDCardinality">
      <eLiterals name="countablyInfinite" value="1"/>
      <eLiterals name="finite" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDComplexFinal">
      <eLiterals name="all" value="1"/>
      <eLiterals name="restriction" value="2"/>
      <eLiterals name="extension" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDCompositor">
      <eLiterals name="all" value="1"/>
      <eLiterals name="choice" value="2"/>
      <eLiterals name="sequence" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDConstraint">
      <eLiterals name="fixed" value="1"/>
      <eLiterals name="default" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDContentTypeCategory">
      <eLiterals name="elementOnly" value="1"/>
      <eLiterals name="mixed" value="2"/>
      <eLiterals name="simple" value="3"/>
      <eLiterals name="empty" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDDerivationMethod">
      <eLiterals name="extension" value="1"/>
      <eLiterals name="restriction" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDDiagnosticSeverity">
      <eLiterals name="fatal" value="1"/>
      <eLiterals name="warning" value="2"/>
      <eLiterals name="error" value="3"/>
      <eLiterals name="information" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDDisallowedSubstitutions">
      <eLiterals name="extension" value="1"/>
      <eLiterals name="substitution" value="2"/>
      <eLiterals name="all" value="3"/>
      <eLiterals name="restriction" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDForm">
      <eLiterals name="unqualified" value="1"/>
      <eLiterals name="qualified" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDIdentityConstraintCategory">
      <eLiterals name="keyref" value="1"/>
      <eLiterals name="unique" value="2"/>
      <eLiterals name="key" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDNamespaceConstraintCategory">
      <eLiterals name="set" value="1"/>
      <eLiterals name="not" value="2"/>
      <eLiterals name="any" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDOrdered">
      <eLiterals value="1"/>
      <eLiterals name="total" value="2"/>
      <eLiterals name="partial" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDProcessContents">
      <eLiterals name="skip" value="1"/>
      <eLiterals name="lax" value="2"/>
      <eLiterals name="strict" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDProhibitedSubstitutions">
      <eLiterals name="extension" value="1"/>
      <eLiterals name="restriction" value="2"/>
      <eLiterals name="all" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDSimpleFinal">
      <eLiterals name="list" value="1"/>
      <eLiterals name="restriction" value="2"/>
      <eLiterals name="all" value="3"/>
      <eLiterals name="union" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDSubstitutionGroupExclusions">
      <eLiterals name="restriction" value="1"/>
      <eLiterals name="extension" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDVariety">
      <eLiterals name="union" value="1"/>
      <eLiterals name="list" value="2"/>
      <eLiterals name="atomic" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDWhiteSpace">
      <eLiterals name="replace" value="1"/>
      <eLiterals name="collapse" value="2"/>
      <eLiterals name="preserve" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XSDXPathVariety">
      <eLiterals name="field" value="1"/>
      <eLiterals name="selector" value="2"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="messageproperties">
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/2/EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyAlias" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageType" ordered="false" unique="false" eType="/2/EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" ordered="false" unique="false" eType="/2/EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wsdlPart" ordered="false" lowerBound="1" eType="/5/Part"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="query" ordered="false" eType="/1/messagepropertiesQuery" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" eType="/2/EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="XSDElement" ordered="false" unique="false" eType="/2/EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="messagepropertiesQuery" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryLanguage" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="ecore">
    <eClassifiers xsi:type="ecore:EClass" name="EObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EBoolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EBooleanObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EInt"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EJavaObject"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EString"/>
  </ecore:EPackage>
  <ecore:EPackage name="partnerlinktype">
    <eClassifiers xsi:type="ecore:EClass" name="PartnerLinkType" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="/3/Role" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="portType" ordered="false" unique="false" eType="/2/EJavaObject"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="BPEL">
    <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryLanguage" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionLanguage" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppressJoinFailure" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableAccessSerializable" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerLinks" ordered="false" eType="/4/PartnerLinks" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" ordered="false" eType="/4/Variables" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultHandlers" ordered="false" eType="/4/FaultHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventHandlers" ordered="false" eType="/4/EventHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correlationSets" ordered="false" eType="/4/CorrelationSets" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1" eType="/4/BPELImport" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" ordered="false" eType="/4/Extensions" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exitOnStandardFault" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PartnerLink" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="myRole" ordered="false" eType="/3/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerRole" ordered="false" eType="/3/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PartnerLinkType" ordered="false" eType="/3/PartnerLinkType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initializePartnerRole" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FaultHandler" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="catch" upperBound="-1" eType="/4/Catch" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catchAll" ordered="false" eType="/4/CatchAll" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppressJoinFailure" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targets" ordered="false" eType="/4/Targets" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" ordered="false" eType="/4/Sources" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CorrelationSet" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="/1/Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Invoke" eSuperTypes="/4/PartnerActivity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputVariable" ordered="false" eType="/4/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputVariable" ordered="false" eType="/4/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compensationHandler" ordered="false" eType="/4/CompensationHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultHandler" ordered="false" eType="/4/FaultHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toPart" upperBound="-1" eType="/4/ToPart"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromPart" upperBound="-1" eType="/4/FromPart"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1" eType="/4/Source" eOpposite="/4/Source/Link"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1" eType="/4/Target" eOpposite="/4/Target/Link"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Catch" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultVariable" ordered="false" eType="/4/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultMessageType" ordered="false" eType="/5/Message"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultElement" ordered="false" eType="/0/XSDElementDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reply" eSuperTypes="/4/PartnerActivity /4/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/4/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toPart" upperBound="-1" eType="/4/ToPart"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PartnerActivity" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerLink" ordered="false" lowerBound="1" eType="/4/PartnerLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correlations" ordered="false" eType="/4/Correlations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="portType" ordered="false" lowerBound="1" eType="/5/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false" lowerBound="1" eType="/5/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Receive" eSuperTypes="/4/PartnerActivity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="createInstance" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" lowerBound="1" eType="/4/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromPart" upperBound="-1" eType="/4/FromPart"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="/4/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Throw" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultVariable" ordered="false" eType="/4/Variable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Wait" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="for" ordered="false" eType="/4/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="until" ordered="false" eType="/4/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Empty" eSuperTypes="/4/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1" upperBound="-1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" upperBound="-1" eType="/4/Case" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="otherwise" ordered="false" eType="/4/Otherwise" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" lowerBound="1" eType="/4/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" lowerBound="1" eType="/4/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pick" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="createInstance" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messages" lowerBound="1" upperBound="-1" eType="/4/OnMessage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alarm" upperBound="-1" eType="/4/OnAlarm" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1" upperBound="-1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" ordered="false" eType="/4/Links" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="completionCondition" ordered="false" eType="/4/CompletionCondition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OnAlarm" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="for" ordered="false" eType="/4/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="until" ordered="false" eType="/4/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="repeatEvery" ordered="false" eType="/4/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assign" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="copy" lowerBound="1" upperBound="-1" eType="/4/Copy" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validate" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Copy" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" lowerBound="1" eType="/4/To" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false" lowerBound="1" eType="/4/From" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keepSrcElementName" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Extension" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mustUnderstand" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Scope" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isolated" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultHandlers" ordered="false" eType="/4/FaultHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compensationHandler" ordered="false" eType="/4/CompensationHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" ordered="false" eType="/4/Variables" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correlationSets" ordered="false" eType="/4/CorrelationSets" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eventHandlers" ordered="false" eType="/4/EventHandler" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerLinks" ordered="false" eType="/4/PartnerLinks" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminationHandler" ordered="false" eType="/4/TerminationHandler" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Compensate" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="scope" ordered="false" eType="/2/EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompensationHandler" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="To" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/4/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" ordered="false" eType="/5/Part"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerLink" ordered="false" eType="/4/PartnerLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false" eType="/1/Property"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="query" ordered="false" eType="/4/BPELQuery" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="From" eSuperTypes="/4/To /4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opaque" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointReference" ordered="false" unique="false" eType="/4/EndpointReferenceRole"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsafeLiteral" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" eType="/4/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceRef" ordered="false" eType="/4/ServiceRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/XSDTypeDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OnMessage" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/4/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="portType" ordered="false" lowerBound="1" eType="/5/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerLink" ordered="false" lowerBound="1" eType="/4/PartnerLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correlations" ordered="false" eType="/4/Correlations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false" lowerBound="1" eType="/5/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromPart" upperBound="-1" eType="/4/FromPart"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false" unique="false" eType="/2/EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionLanguage" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opaque" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="/4/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Correlation" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initiate" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" ordered="false" unique="false" eType="/4/CorrelationPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="set" ordered="false" lowerBound="1" eType="/4/CorrelationSet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CorrelationPattern">
      <eLiterals name="outin" value="1"/>
      <eLiterals name="in" value="2"/>
      <eLiterals name="out" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EndpointReferenceRole">
      <eLiterals name="partnerRole" value="1"/>
      <eLiterals name="myRole" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventHandler" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="alarm" upperBound="-1" eType="/4/OnAlarm" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1" eType="/4/OnEvent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Link" ordered="false" lowerBound="1" eType="/4/Link" eOpposite="/4/Link/sources"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitionCondition" ordered="false" eType="/4/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Target" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Link" ordered="false" lowerBound="1" eType="/4/Link" eOpposite="/4/Link/targets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PartnerLinks" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/PartnerLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variables" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/Variable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CorrelationSets" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/CorrelationSet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Links" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/Link" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CatchAll" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Correlations" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/Correlation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageType" ordered="false" eType="/5/Message"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="XSDElement" ordered="false" eType="/0/XSDElementDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false" eType="/4/From"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Otherwise" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnknownExtensibilityAttribute" eSuperTypes="/5/UnknownExtensibilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OnEvent" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" eType="/4/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="partnerLink" ordered="false" lowerBound="1" eType="/4/PartnerLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correlations" ordered="false" eType="/4/Correlations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false" lowerBound="1" eType="/5/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="portType" ordered="false" lowerBound="1" eType="/5/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageType" ordered="false" lowerBound="1" eType="/5/Message"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromPart" upperBound="-1" eType="/4/FromPart"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="correlationSets" ordered="false" eType="/4/CorrelationSets" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BPELImport">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="importType" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rethrow" eSuperTypes="/4/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="/4/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Targets" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/Target" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="joinCondition" ordered="false" eType="/4/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sources" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/Source" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BPELQuery">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryLanguage" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceRef">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceScheme" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Extensions" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/4/Extension" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExtensionActivity" eSuperTypes="/4/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="FromPart">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" eType="/4/To"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ToPart">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false" eType="/4/From"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpaqueActivity" eSuperTypes="/4/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="ForEach" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallel" ordered="false" unique="false" eType="/2/EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="counterName" ordered="false" lowerBound="1" eType="/4/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="completionCondition" ordered="false" eType="/4/CompletionCondition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" ordered="false" lowerBound="1" eType="/4/Iterator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RepeatUntil" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" lowerBound="1" eType="/4/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TerminationHandler" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Validate" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1" eType="/4/Variable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="/4/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" eType="/4/Condition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" ordered="false" eType="/4/Then" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseIf" upperBound="-1" eType="/4/ElseIf" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" ordered="false" eType="/4/Else" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Then" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElseIf" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" eType="/4/Condition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Else" eSuperTypes="/4/BPELExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" ordered="false" lowerBound="1" eType="/4/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompletionCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="branches" ordered="false" eType="/4/Branches" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Branches" eSuperTypes="/4/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="countCompletedBranchesOnly" ordered="false" unique="false" eType="/2/EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BPELExtensibleElement" eSuperTypes="/5/WSDLExtensibleElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="documentation" ordered="false" eType="/4/Documentation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Documentation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lang" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Iterator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="finalCounterValue" ordered="false" eType="/4/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startCounterValue" ordered="false" eType="/4/Expression" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="WSDL">
    <eClassifiers xsi:type="ecore:EClass" name="WSDLElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentationElement" ordered="false" unique="false" eType="/5/WSDLDOMElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" ordered="false" unique="false" eType="/5/WSDLDOMElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortType" eSuperTypes="/5/WSDLElement /5/IPortType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOperations" upperBound="-1" eType="/5/Operation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="/5/WSDLElement /5/IOperation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" ordered="false" unique="false" eType="/5/OperationType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eInput" ordered="false" eType="/5/Input" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOutput" ordered="false" eType="/5/Output" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eFaults" upperBound="-1" eType="/5/Fault" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eParameterOrdering" upperBound="-1" eType="/5/Part"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="/5/WSDLElement /5/IMessage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eParts" upperBound="-1" eType="/5/Part" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="/5/WSDLElement /5/IPart">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinition" ordered="false" eType="/0/XSDTypeDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementDeclaration" ordered="false" eType="/0/XSDElementDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eMessage" ordered="false" eType="/5/Message"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="/5/WSDLExtensibleElement /5/IBinding">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ePortType" ordered="false" lowerBound="1" eType="/5/PortType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eBindingOperations" upperBound="-1" eType="/5/BindingOperation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingOperation" eSuperTypes="/5/WSDLExtensibleElement /5/IBindingOperation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOperation" ordered="false" lowerBound="1" eType="/5/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eBindingInput" ordered="false" eType="/5/BindingInput" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eBindingOutput" ordered="false" eType="/5/BindingOutput" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eBindingFaults" upperBound="-1" eType="/5/BindingFault" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="/5/WSDLExtensibleElement /5/IService">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxy" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ePorts" upperBound="-1" eType="/5/Port" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="/5/WSDLExtensibleElement /5/IPort">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eBinding" ordered="false" lowerBound="1" eType="/5/Binding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExtensibilityElement" eSuperTypes="/5/WSDLElement /5/IExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" ordered="false" unique="false" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" ordered="false" unique="false" eType="/5/QName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Definition" eSuperTypes="/5/WSDLExtensibleElement /5/IDefinition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" ordered="false" unique="false" eType="/5/QName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eImports" upperBound="-1" eType="/5/WSDLImport" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eTypes" ordered="false" eType="/5/Types" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eMessages" upperBound="-1" eType="/5/Message" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ePortTypes" upperBound="-1" eType="/5/PortType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eBindings" upperBound="-1" eType="/5/Binding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eServices" upperBound="-1" eType="/5/Service" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eNamespaces" upperBound="-1" eType="/5/Namespace" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WSDLImport" eSuperTypes="/5/WSDLElement /5/IImport">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationURI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eDefinition" ordered="false" eType="/5/Definition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eSchema" ordered="false" eType="/0/XSDSchema"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WSDLExtensibleElement" abstract="true" eSuperTypes="/5/WSDLElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="eExtensibilityElements" upperBound="-1" eType="/5/ExtensibilityElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="/5/MessageReference /5/WSDLElement /5/IInput"/>
    <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="/5/MessageReference /5/WSDLElement /5/IOutput"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fault" eSuperTypes="/5/MessageReference /5/WSDLElement /5/IFault"/>
    <eClassifiers xsi:type="ecore:EClass" name="BindingInput" eSuperTypes="/5/WSDLExtensibleElement /5/IBindingInput">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eInput" ordered="false" lowerBound="1" eType="/5/Input"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingOutput" eSuperTypes="/5/WSDLExtensibleElement /5/IBindingOutput">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOutput" ordered="false" lowerBound="1" eType="/5/Output"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingFault" eSuperTypes="/5/WSDLExtensibleElement /5/IBindingFault">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eFault" ordered="false" lowerBound="1" eType="/5/Fault"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="QName"/>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" ordered="false" unique="false" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="OperationType"/>
    <eClassifiers xsi:type="ecore:EClass" name="IPortType" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IOperation" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IInput" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IOutput" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IFault" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IMessage" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IPart" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IService" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IPort" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IBinding" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IBindingOperation" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IBindingInput" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IBindingOutput" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IBindingFault" abstract="true"/>
    <eClassifiers xsi:type="ecore:EDataType" name="WSDLDOMElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="IExtensibilityElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IDefinition" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IImport" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IList" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IMap" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IURL" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IExtensionRegistry" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Types" eSuperTypes="/5/WSDLExtensibleElement /5/ITypes"/>
    <eClassifiers xsi:type="ecore:EClass" name="IIterator" abstract="true"/>
    <eClassifiers xsi:type="ecore:EDataType" name="WSDLException"/>
    <eClassifiers xsi:type="ecore:EClass" name="ITypes" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnknownExtensibilityElement" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/5/UnknownExtensibilityElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSDSchemaExtensibilityElement" eSuperTypes="/5/ExtensibilityElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schema" ordered="false" eType="/0/XSDSchema" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="WSDLDOMDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageReference" abstract="true" eSuperTypes="/5/WSDLElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eMessage" ordered="false" lowerBound="1" eType="/5/Message"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
