extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/f766230cca454b30749204dc771cb6634f393d1c/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
