<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="AnyLogic">
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludeFromBuild" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisualModelElement" eSuperTypes="/0/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" ordered="false" lowerBound="1" eType="/0/Point" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" lowerBound="1" eType="/0/Point" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicFlag" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentationFlag" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="showLabel" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Point">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="/0/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="engineVersion" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaPackageName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activeObjectClasses" ordered="false" upperBound="-1" eType="/0/ActiveObjectClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="experiments" ordered="false" upperBound="-1" eType="/0/Experiment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActiveObjectClass" eSuperTypes="/0/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="clientAreaTopLeft" ordered="false" lowerBound="1" eType="/0/Point" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentationTopGroupPersistent" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconTopGroupPersistent" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="generic" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericParameters" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="agent" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="environmentDefinesInitialLocation" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" ordered="false" upperBound="-1" eType="/0/Connector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedObjects" ordered="false" upperBound="-1" eType="/0/EmbeddedObject" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="shapes" ordered="false" upperBound="-1" eType="/0/Shape" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="/0/VisualModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEmbeddedObject" ordered="false" lowerBound="1" eType="/0/EmbeddedObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceConnectableName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetEmbeddedObject" ordered="false" lowerBound="1" eType="/0/EmbeddedObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetConnectableName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="points" ordered="false" upperBound="-1" eType="/0/Point" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmbeddedObject" eSuperTypes="/0/VisualModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="presentation" ordered="false" lowerBound="1" eType="/0/EmbeddedObjectPresentation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activeObjectClass" ordered="false" lowerBound="1" eType="/0/ActiveObjectClassRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericParametersSubstitute" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false" upperBound="-1" eType="/0/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActiveObjectClassRef">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="/0/VisualModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="asObject" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="embeddedIcon" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmbeddedObjectPresentation" eSuperTypes="/0/Shape"/>
    <eClassifiers xsi:type="ecore:EClass" name="Experiment" eSuperTypes="/0/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimulationExperiment" eSuperTypes="/0/Experiment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activeObjectClass" ordered="false" lowerBound="1" eType="/0/ActiveObjectClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="clientAreaTopLeft" ordered="false" lowerBound="1" eType="/0/Point" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentationTopGroupPersistent" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconTopGroupPersistent" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="frame" ordered="false" lowerBound="1" eType="/0/Frame" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandLineArguments" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumMemory" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomSeed" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="seedValue" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vmArgs" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteAccuracy" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeAccuracy" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeAccuracy" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedTimeStep" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="shapes" ordered="false" upperBound="-1" eType="/0/Shape" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controls" ordered="false" upperBound="-1" eType="/0/Control" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false" upperBound="-1" eType="/0/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableAdaptiveFrameManagement" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableAntiAliasing" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enablePanning" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableZoom" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionMode" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuRatio" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="framesPerSecond" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="realTimeScale" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="uiProperties" ordered="false" upperBound="-1" eType="/0/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="useCalendar" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopOption" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialDate" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialTime" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finalDate" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finalTime" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelTimeUnit" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="/0/VisualModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="asObject" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="embeddedIcon" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillColor" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="textColor" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableExpression" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionCode" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelText" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" lowerBound="1" eType="/0/Font" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="/0/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Frame">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="/0/Shape">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" lowerBound="1" eType="/0/Font" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Font">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
