<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="fr">
    <eSubpackages name="obeo">
      <eSubpackages name="psm">
        <eSubpackages name="vb">
          <eSubpackages name="resources">
            <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsBefore" unique="false" upperBound="-1" eType="/1/String"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsAfter" unique="false" upperBound="-1" eType="/1/String"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="VB_LangElement" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/LocatedElement"/>
          </eSubpackages>
          <eSubpackages name="projects">
            <eSubpackages name="VB_1">
              <eSubpackages name="core">
                <eClassifiers xsi:type="ecore:EClass" name="VB_Content" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVersion" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasClass" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasBeginEnd" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="beginEndGlobalVariables" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/core/VB_GlobalVariable" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariables" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/core/VB_GlobalVariable" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_GlobalVariable" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_ContentElement" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_FileAttribute" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" lowerBound="1" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Option" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasEnablement" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="enablement" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/EnablementEnum"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Imports" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="imports" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Implements" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="implements" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Assembly" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="call" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Call" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Class" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement /0/obeo/psm/vb/projects/VB_1/core/VB_Type">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFriend" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVisibility" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasInherits" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="inherits" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Module" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Type" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Data" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_SimpleType" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Enum" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature" containment="true"/>
                </eClassifiers>
              </eSubpackages>
              <eSubpackages name="preprocessing">
                <eClassifiers xsi:type="ecore:EClass" name="VB_PreprocIf" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature" containment="true"/>
                </eClassifiers>
              </eSubpackages>
              <eSubpackages name="features">
                <eClassifiers xsi:type="ecore:EClass" name="VB_Feature" abstract="true" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_Data /0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Region" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Sub" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAnnotation" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Call" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFriend" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVisibility" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOverloads" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOverrides" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasHandles" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="handles" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Function" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFriend" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVisibility" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="return" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_DeclareFunction" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVisibility" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAuto" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="lib" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAlias" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" ordered="false" unique="false" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="return" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_DeclareSub" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVisibility" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAuto" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="lib" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAlias" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" ordered="false" unique="false" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Parameter" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_Data">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasQualifier" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/QualifierEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isArray" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arrayExpression" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasType" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasInitialValue" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Property" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShared" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isGetOnly" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSet" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLet" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Modifier" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Modifier" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Set" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Modifier">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasParameters" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Get" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Modifier">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasParameters" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/features/VB_Parameter" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Attribute" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Feature">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasVisibility" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/VisibilityEnum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasQualifier" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" ordered="false" unique="false" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/Qualifier_2Enum"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFriend" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWithEvents" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isShared" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="isArray" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arrayExpressions" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasType" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasInitialValue" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasNext" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                </eClassifiers>
              </eSubpackages>
              <eSubpackages name="graphicals">
                <eClassifiers xsi:type="ecore:EClass" name="VB_GraphicalElement" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_ContentElement /0/obeo/psm/vb/projects/VB_1/core/VB_Data">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/graphicals/VB_GraphicalField" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/graphicals/VB_GraphicalElement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_GraphicalField" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_GraphicalPropertySet" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/graphicals/VB_GraphicalField">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasArguments" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasBrackets" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/graphicals/VB_GraphicalField" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_GraphicalProperty" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/core/VB_Data /0/obeo/psm/vb/projects/VB_1/graphicals/VB_GraphicalField">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullDataRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
              </eSubpackages>
              <eSubpackages name="statements">
                <eClassifiers xsi:type="ecore:EClass" name="VB_Statement" abstract="true" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/features/VB_Modifier"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Call" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullDataRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_CallArgument" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_CallArgument" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_CallEmptyArgument" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/statements/VB_CallArgument"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_CallExpressionArgument" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/statements/VB_CallArgument">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasSeparator" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Case" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasSeparator" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_RawBody" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/statements/VB_Statement">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" eType="/1/String"/>
                </eClassifiers>
              </eSubpackages>
              <eSubpackages name="expressions">
                <eClassifiers xsi:type="ecore:EClass" name="VB_Expression" abstract="true" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_AssignmentExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullDataRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_TypeOfExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullDataRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_OperatorExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="leftHand" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="rightHand" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorName" ordered="false" unique="false" eType="/1/String"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_NewExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_FullTypeRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasArguments" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasInitialization" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="initializations" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_NotExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_NegativeExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_ParenthesisExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_TabValuesExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_ByValExpression" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Value" abstract="true" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_NegativeValue" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Value">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Value" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_VariableSystem" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Value">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/obeo/psm/vb/projects/VB_1/enumerations/NameEnum"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Literal" abstract="true" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Value">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Literal_Literal" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Literal"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Literal_Number" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Literal"/>
                <eClassifiers xsi:type="ecore:EClass" name="VB_Literal_Value" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Literal"/>
              </eSubpackages>
              <eSubpackages name="references">
                <eClassifiers xsi:type="ecore:EClass" name="VB_FullTypeRef" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_TypeRef" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_TypeRef" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/resources/VB_LangElement"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeValue" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_FullDataRef" eSuperTypes="/0/obeo/psm/vb/projects/VB_1/expressions/VB_Expression">
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="self" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_DataRef" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasRecSet" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="recSetMember" ordered="false" eType="/0/obeo/psm/vb/projects/VB_1/references/VB_DataRef" containment="true"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_DataRef" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="data" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/resources/VB_LangElement"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasArguments" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/0/obeo/psm/vb/projects/VB_1/statements/VB_CallArgument" containment="true"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasRefMarker" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasSubMarker" ordered="false" unique="false" lowerBound="1" eType="/1/Boolean"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EClass" name="VB_LabelRef" eSuperTypes="/0/obeo/psm/vb/resources/VB_LangElement">
                  <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" lowerBound="1" eType="/0/obeo/psm/vb/resources/VB_LangElement"/>
                  <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelValue" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
                </eClassifiers>
              </eSubpackages>
              <eSubpackages name="enumerations">
                <eClassifiers xsi:type="ecore:EEnum" name="EnablementEnum">
                  <eLiterals name="Off" value="1"/>
                  <eLiterals name="On" value="2"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EEnum" name="VisibilityEnum">
                  <eLiterals name="private" value="1"/>
                  <eLiterals name="protected" value="2"/>
                  <eLiterals name="public" value="3"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EEnum" name="QualifierEnum">
                  <eLiterals name="byRef" value="1"/>
                  <eLiterals name="byVal" value="2"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EEnum" name="Qualifier_2Enum">
                  <eLiterals name="static" value="1"/>
                  <eLiterals name="const" value="2"/>
                  <eLiterals name="dim" value="3"/>
                </eClassifiers>
                <eClassifiers xsi:type="ecore:EEnum" name="NameEnum">
                  <eLiterals name="trueLit" value="1"/>
                  <eLiterals name="falseLit" value="2"/>
                  <eLiterals name="nothing" value="3"/>
                </eClassifiers>
              </eSubpackages>
            </eSubpackages>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
</xmi:XMI>
