<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimplifiedMiningMart">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" eSuperTypes="//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" lowerBound="1" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false" lowerBound="1" upperBound="-1" eType="//Attribute" containment="true" eOpposite="//Attribute/class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false" lowerBound="1" eType="//Attribute" eOpposite="//Attribute/has"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="//StructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" ordered="false" lowerBound="1" eType="//Class" eOpposite="//Class/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" ordered="false" lowerBound="1" eType="//DataType" eOpposite="//DataType/attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept" eSuperTypes="//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnSet" eSuperTypes="//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAttribute" eSuperTypes="//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleRestriction" eSuperTypes="//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDataType" eSuperTypes="//DataType"/>
</ecore:EPackage>
