extract:

fetch:
	rm -f fetched/*
	wget http://www.omg.org/spec/KDM/20070301/BuildExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/ClassD.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/CommentExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/ConceptualExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/DataExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/DataSchemaExample.xmi.kdm 
	wget http://www.omg.org/spec/KDM/20070301/DirectivesExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/DispatchExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/Exceptions.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/HelloWorld.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/IMSExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/IncludeExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/InterfaceExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/InventoryExample.kdm
	wget http://www.omg.org/spec/KDM/20070301/InventoryExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/KDMFrameworkExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/Light.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/LinkedList.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/MacroExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/MicroKDM.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/Record.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/RecordFileExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/Stereotype.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/StructureExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/TemplateExample.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/Variants.xmi.kdm
	wget http://www.omg.org/spec/KDM/20070301/XMLExampleComplex.xmi.kdm
	mv *.kdm fetched/
