<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="GeoTrans">
    <eClassifiers xsi:type="ecore:EClass" name="GeoTransfos">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transfos" upperBound="-1" eType="/1/GeoTransfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GeoTransfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="freeze" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subGeoTransfos" upperBound="-1" eType="/1/GeoTransfo" containment="true" eOpposite="/1/GeoTransfo/superGeoTransfo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superGeoTransfo" ordered="false" lowerBound="1" eType="/1/GeoTransfo" eOpposite="/1/GeoTransfo/subGeoTransfos"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" eType="/1/Param" containment="true" eOpposite="/1/Param/geoTransfo"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Param">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="param" ordered="false" unique="false" lowerBound="1" eType="/0/Double"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="geoTransfo" ordered="false" lowerBound="1" eType="/1/GeoTransfo" eOpposite="/1/GeoTransfo/params"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
