fetch:
	wget http://www.ors.uoguelph.ca/docs/xul/xultu/elemref/refall_elemref.xml
	wget http://mozilla.doslash.org/xulschema/xulschema.zip
	unzip xulschema.zip
	rm xulschema.zip
	mv *.xml *.xsd *.xsl fetched/
	mv fetched/zoo.xml zoo.xml

include ../../../../Makefile.grammar
