extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/947921efca671a0c4cdddafd8c67570a7340fc90/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
