extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/e902641f3e0eeb61fd758d4908dce27a41ae26af/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
