extract:

fetch:
	curl https://raw.githubusercontent.com/laurentpetit/ccw/a8d869fa459bb5e024a4d3aa165de5e0e7ce220a/clojure-antlr-grammar/src/Clojure.g > fetched/Clojure.g
	curl https://raw.githubusercontent.com/laurentpetit/ccw/a8d869fa459bb5e024a4d3aa165de5e0e7ce220a/clojure-antlr-grammar/src/ClojurePartition.g > fetched/ClojurePartition.g
	curl https://raw.githubusercontent.com/laurentpetit/ccw/a8d869fa459bb5e024a4d3aa165de5e0e7ce220a/clojure-antlr-grammar/src/Test.java > fetched/Test.java
