extract:
	${tooldir}/rng2bgf ../source/extensions/resetinhibitorptnet.pntd ext.bgf
	${tooldir}/mergebgf ext.bgf ../ptnet/grammar.bgf ../ext-specialarcs/grammar.bgf grammar.bgf

include ../../Makefile.grammar
