extract:

fetch:
	wget http://www.h2database.com/html/grammar.html
	wget http://savage.net.au/SQL/sql-2003-2.bnf.html
	wget http://savage.net.au/SQL/sql-2003-2.bnf
	mv sql-2003-2.bnf fetched/

clean:
	rm -rf *.html *.1
