extract:
	${tooldir}/rscs2bgf RascalADT2BGF.rsc grammar.bgf

get:
	rm -f RascalADT2BGF.rsc
	wget --no-check-certificate http://raw.github.com/grammarware/slps/6837b95467ba32664170f3b8b91f79928e27e455/shared/rascal/src/extract/RascalADT2BGF.rsc

include ../../Makefile.grammar
