<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="CPL">
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="CPL" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subActions" upperBound="-1" eType="/0/SubAction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false" eType="/0/Outgoing" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false" eType="/0/Incoming" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeContainer" abstract="true" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" ordered="false" eType="/0/Node" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubAction" eSuperTypes="/0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Outgoing" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Incoming" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotPresent" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Otherwise" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchedAddress" eSuperTypes="/0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contains" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subDomainOf" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchedString" eSuperTypes="/0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contains" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchedLanguage" eSuperTypes="/0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="matches" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchedTime" eSuperTypes="/0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstart" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtend" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="until" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bySecond" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byMinute" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byHour" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byDay" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byMonthDay" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byYearDay" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byWeekNo" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="byMonth" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="wkst" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bySetPos" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchedPriority" eSuperTypes="/0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="less" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="greater" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="equal" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Busy" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="NoAnswer" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Redirection" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Failure" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Default" eSuperTypes="/0/NodeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="/0/Element"/>
    <eClassifiers xsi:type="ecore:EClass" name="Switch" abstract="true" eSuperTypes="/0/Node">
      <eStructuralFeatures xsi:type="ecore:EReference" name="notPresent" ordered="false" eType="/0/NotPresent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="otherwise" ordered="false" eType="/0/Otherwise" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AddressSwitch" eSuperTypes="/0/Switch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subField" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addresses" upperBound="-1" eType="/0/SwitchedAddress" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringSwitch" eSuperTypes="/0/Switch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="strings" upperBound="-1" eType="/0/SwitchedString" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LanguageSwitch" eSuperTypes="/0/Switch">
      <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1" eType="/0/SwitchedLanguage" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeSwitch" eSuperTypes="/0/Switch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tzid" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tzurl" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="times" upperBound="-1" eType="/0/SwitchedTime" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrioritySwitch" eSuperTypes="/0/Switch">
      <eStructuralFeatures xsi:type="ecore:EReference" name="priorities" upperBound="-1" eType="/0/SwitchedPriority" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="/0/Node /0/NodeContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="clear" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubCall" eSuperTypes="/0/Node">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="/0/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="SignallingAction" abstract="true" eSuperTypes="/0/Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="Proxy" eSuperTypes="/0/SignallingAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="recurse" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="busy" ordered="false" eType="/0/Busy" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="noAnswer" ordered="false" eType="/0/NoAnswer" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="redirection" ordered="false" eType="/0/Redirection" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="failure" ordered="false" eType="/0/Failure" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" ordered="false" eType="/0/Default" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Redirect" eSuperTypes="/0/SignallingAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="permanent" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reject" eSuperTypes="/0/SignallingAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" ordered="false" unique="false" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
