extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/eb554d4752bbf9f3d0229b1ea0403426e5798f72/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
