extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/d679591ac13477c12833d45a2148972aae33413c/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
