extract:
	${tooldir}/rscd2bgf fetched/language/CBGF.rsc ext.bgf
	${tooldir}/mergebgf ext.bgf aliases.bgf grammar.bgf

fetch:
	cp ${slpsdir}/shared/rascal/src/language/CBGF.rsc fetched/

include ../../../Makefile.grammar
