<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
  <ecore:EPackage name="HTML">
    <eClassifiers xsi:type="ecore:EClass" name="HTML">
      <eStructuralFeatures xsi:type="ecore:EReference" name="head" ordered="false" lowerBound="1" eType="/1/HEAD" containment="true" eOpposite="/1/HEAD/html"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/1/BODY" containment="true" eOpposite="/1/BODY/html"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HTMLElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false" upperBound="-1" eType="/1/HTMLElement" containment="true" eOpposite="/1/HTMLElement/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false" lowerBound="1" eType="/1/HTMLElement" eOpposite="/1/HTMLElement/children"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HEAD" eSuperTypes="/1/HTMLElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="headElements" ordered="false" upperBound="-1" eType="/1/HEADElement" containment="true" eOpposite="/1/HEADElement/head"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="html" ordered="false" lowerBound="1" eType="/1/HTML" eOpposite="/1/HTML/head"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HEADElement" abstract="true" eSuperTypes="/1/HTMLElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="head" ordered="false" lowerBound="1" eType="/1/HEAD" eOpposite="/1/HEAD/headElements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LINK" eSuperTypes="/1/HEADElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rel" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ahref" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TITLE" eSuperTypes="/1/HEADElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="BODY" eSuperTypes="/1/HTMLElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bgcolor" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alink" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vlink" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyElements" ordered="false" upperBound="-1" eType="/1/BODYElement" containment="true" eOpposite="/1/BODYElement/body"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="html" ordered="false" lowerBound="1" eType="/1/HTML" eOpposite="/1/HTML/body"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BODYElement" abstract="true" eSuperTypes="/1/HTMLElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false" lowerBound="1" eType="/1/BODY" eOpposite="/1/BODY/bodyElements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="H1" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="H2" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="H3" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="H4" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="EM" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="STRONG" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="I" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TT" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PRE" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="BIG" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SMALL" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SUB" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SUP" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="STRIKE" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="FONT" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="face" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IMG" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alt" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vspace" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hspace" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ismap" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usemap" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="border" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BR" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="clear" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MAP" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="AREA" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coords" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ahref" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="STYLE" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMBED" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vspace" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hspace" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="border" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NOEMBED" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SPAN" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ahref" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DIV" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="P" eSuperTypes="/1/BODYElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TABLEElement" abstract="true" eSuperTypes="/1/BODYElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bgcolor" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="background" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TABLE" eSuperTypes="/1/TABLEElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="border" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellspacing" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellpadding" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="trs" ordered="false" upperBound="-1" eType="/1/TR" containment="true" eOpposite="/1/TR/table"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TR" eSuperTypes="/1/TABLEElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valign" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="table" ordered="false" lowerBound="1" eType="/1/TABLE" eOpposite="/1/TABLE/trs"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tds" ordered="false" upperBound="-1" eType="/1/TD" containment="true" eOpposite="/1/TD/tr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TD" eSuperTypes="/1/TABLEElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="colspan" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowspan" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valign" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tr" ordered="false" lowerBound="1" eType="/1/TR" eOpposite="/1/TR/tds"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TH" eSuperTypes="/1/TD"/>
    <eClassifiers xsi:type="ecore:EClass" name="FORM">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="INPUT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxlength" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checked" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputValue" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TEXTAREA">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cols" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SELECT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OPTION">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionValue" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ListElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OL" eSuperTypes="/1/ListElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UL" eSuperTypes="/1/ListElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="LI" eSuperTypes="/1/ListElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="liValue" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DL"/>
    <eClassifiers xsi:type="ecore:EClass" name="DT"/>
    <eClassifiers xsi:type="ecore:EClass" name="DD"/>
    <eClassifiers xsi:type="ecore:EClass" name="APPLET">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="applet" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PARAM">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramValue" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OBJECT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classid" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="standby" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FRAMESET">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cols" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="framespacing" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="frameborder" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="border" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FRAME">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="marginwidth" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="marginheight" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scrolling" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="noresize" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NOFRAME"/>
    <eClassifiers xsi:type="ecore:EClass" name="IFRAME" eSuperTypes="/1/FRAME"/>
  </ecore:EPackage>
</xmi:XMI>
