extract:
	../../hunter.py src.8.2.txt config.edd ebnf-iso-2.raw.bgf
	${tooldir}/xbgf post-extract.xbgf ebnf-iso-2.raw.bgf ebnf-iso-2.ext.bgf
	${tooldir}/xbgf refactor.xbgf ebnf-iso-2.ext.bgf ebnf-iso-2.bgf

include ../../Makefile.include
