extract:
	${tooldir}/rscs2bgf ${rascaldir}/logic/syntax/Booleans.rsc ext.bool.bgf
	${tooldir}/rscs2bgf ${rascaldir}/logic/syntax/Propositions.rsc ext.prop.bgf
	${tooldir}/rscs2bgf ${rascaldir}/logic/syntax/Truths.rsc ext.truth.bgf
	${tooldir}/mergebgf ext.*.bgf grammar.bgf

include ../../Makefile.grammar
