extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/ae80778a0705e45fb91ebe4b3c42d428ab5f3f0e/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
