extract:

fetch:
	wget http://pic.dhe.ibm.com/infocenter/dmanager/v7r5/topic/com.ibm.dserver.reference.studio/Content/Business_Rules/_pubskel/Infocenter_Primary/ps_DS_Reference_Designer1915.html
	mv *.html fetched/
