<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="KM3">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="package" ordered="false" lowerBound="1" eType="/1/Package" eOpposite="/1/Package/contents"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="/1/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="/1/Classifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="/1/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1" eType="/1/EnumLiteral" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral" eSuperTypes="/1/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="/1/Classifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="supertypes" ordered="false" upperBound="-1" eType="/1/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatures" upperBound="-1" eType="/1/StructuralFeature" containment="true" eOpposite="/1/StructuralFeature/owner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false" unique="false" lowerBound="1" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false" unique="false" lowerBound="1" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="/1/Class" eOpposite="/1/Class/structuralFeatures"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/1/Classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="/1/StructuralFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="/1/StructuralFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isContainer" ordered="false" unique="false" lowerBound="1" eType="/0/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" ordered="false" eType="/1/Reference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/1/ModelElement" containment="true" eOpposite="/1/ModelElement/package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" ordered="false" lowerBound="1" eType="/1/Metamodel" eOpposite="/1/Metamodel/contents"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Metamodel" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/1/Package" containment="true" eOpposite="/1/Package/metamodel"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
