extract:

fetch:
	curl https://raw.githubusercontent.com/ewa/ad9510spi/master/ValueChangeDump.g > fetched/ValueChangeDump.g
	curl https://raw.githubusercontent.com/ewa/ad9510spi/master/InterpretVCDHeader.g > fetched/InterpretVCDHeader.g
