extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/aba2a8a3b5b8874f1637fcca2308a287d6076e0a/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
