<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="HAL">
    <eClassifiers xsi:type="ecore:EClass" name="HAL">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connexion" ordered="false" lowerBound="1" eType="/1/Connexion" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" ordered="false" upperBound="-1" eType="/1/Entry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connexion">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entry" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="autLab" ordered="false" lowerBound="1" eType="/1/AutLabType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tampons" ordered="false" upperBound="-1" eType="/1/TamponType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Article" abstract="true" eSuperTypes="/1/Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metaArt" ordered="false" lowerBound="1" eType="/1/MetaArtType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArticleRecent" eSuperTypes="/1/Article">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fichiers" ordered="false" lowerBound="1" eType="/1/DepotsType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArticleRetro" eSuperTypes="/1/Article">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateRedaction" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fichiers" ordered="false" lowerBound="1" eType="/1/AbstractDepot" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Notice" eSuperTypes="/1/Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metaArtNotice" ordered="false" lowerBound="1" eType="/1/MetaArtNoticeType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceBiblioType" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtRevueType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urldoi" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="journal" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annee" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkshopType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urldoi" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="titconf" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ville" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pays" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edcom" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annee" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edsci" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serie" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtOuvrageType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urldoi" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="titouv" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edcom" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annee" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edsci" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serie" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OuvrageType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urldoi" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="edcom" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annee" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TheseType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orgthe" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="niveau" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defencedate" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directeur" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codirecteur" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BrevetType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="datebrevet" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numbrevet" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pays" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AutreType" abstract="true" eSuperTypes="/1/ReferenceBiblioType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urldoi" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="annee" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtRevue" eSuperTypes="/1/ArtRevueType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtJournal" eSuperTypes="/1/ArtRevueType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Workshop" eSuperTypes="/1/WorkshopType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="/1/WorkshopType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Conference" eSuperTypes="/1/WorkshopType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtOuvrage" eSuperTypes="/1/ArtOuvrageType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Ouvrage" eSuperTypes="/1/OuvrageType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Brevet" eSuperTypes="/1/BrevetType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Autre" eSuperTypes="/1/AutreType"/>
    <eClassifiers xsi:type="ecore:EClass" name="These" eSuperTypes="/1/TheseType"/>
    <eClassifiers xsi:type="ecore:EClass" name="MetaType" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="langue" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refInterne" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idext" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEpj" ordered="false" unique="false" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEpl" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classification" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="collaboration" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="datevisible" ordered="false" unique="false" eType="/1/DateVisibleEnum"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="financement" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="researchteam" ordered="false" unique="false" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetaArtType" eSuperTypes="/1/MetaType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceBiblio" ordered="false" eType="/1/ReferenceBiblioType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetaArtNoticeType" eSuperTypes="/1/MetaType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceBiblio" ordered="false" lowerBound="1" eType="/1/ReferenceBiblioType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AutLabType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="auteurs" ordered="false" lowerBound="1" upperBound="-1" eType="/1/Auteur"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="laboratoires" ordered="false" lowerBound="1" upperBound="-1" eType="/1/Laboratoire"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Auteur">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prenom" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="autrePrenom" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlPerso" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lab" ordered="false" eType="/1/Laboratoire"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Laboratoire">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metas" ordered="false" lowerBound="1" eType="/1/AbstractMetaLab" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMetaLab" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="MetaLab" eSuperTypes="/1/AbstractMetaLab">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AffiliationType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="institution" ordered="false" unique="false" upperBound="-1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prive" ordered="false" unique="false" upperBound="-1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ecole" ordered="false" unique="false" upperBound="-1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="universite" ordered="false" unique="false" upperBound="-1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TamponType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DateVisibleEnum">
      <eLiterals name="15J" value="1"/>
      <eLiterals name="1M" value="2"/>
      <eLiterals name="3M" value="3"/>
      <eLiterals name="1A" value="4"/>
      <eLiterals name="2A" value="5"/>
      <eLiterals name="JAMAIS" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractDepot" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Depot" eSuperTypes="/1/AbstractDepot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" ordered="false" unique="false" lowerBound="1" eType="/1/FormatEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FormatEnum">
      <eLiterals name="PDF" value="1"/>
      <eLiterals name="TEX" value="2"/>
      <eLiterals name="DOC" value="3"/>
      <eLiterals name="RTF" value="4"/>
      <eLiterals name="TXT" value="5"/>
      <eLiterals name="PS" value="6"/>
      <eLiterals name="ANNEX" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DepotWeb" eSuperTypes="/1/AbstractDepot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" ordered="false" unique="false" lowerBound="1" eType="/1/FormatWebEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FormatWebEnum">
      <eLiterals name="XML" value="1"/>
      <eLiterals name="HTML" value="2"/>
      <eLiterals name="HTM" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractDepotType" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="DepotsType" eSuperTypes="/1/AbstractDepotType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="depots" ordered="false" lowerBound="1" upperBound="-1" eType="/1/AbstractDepot" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WebLink" eSuperTypes="/1/AbstractDepotType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiant" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" ordered="false" lowerBound="1" eType="/1/Server" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Server"/>
  </ecore:EPackage>
</xmi:XMI>
