extract:
	${tooldir}/sdf2bgf fetched/*.sdf ext.bgf
	${tooldir}/subgrammar ext.bgf Top-sort extracted/grammar.bgf

fetch:
	cp ${sdflibdir}/java/syntax/*.sdf fetched/

include ../../../Makefile.grammar
