<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="OCLTypes">
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" ordered="false" upperBound="-1" eType="/0/Type" eOpposite="/0/Type/subtype"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" ordered="false" upperBound="-1" eType="/0/Type" eOpposite="/0/Type/supertype"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionType" ordered="false" upperBound="-1" eType="/0/CollectionType" containment="true" eOpposite="/0/CollectionType/elementType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BasicType" abstract="true" eSuperTypes="/0/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceType" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false" lowerBound="1" eType="/0/Classifier" containment="true" eOpposite="/0/Classifier/instanceType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumType" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumLiteral" ordered="false" lowerBound="1" upperBound="-1" eType="/0/EnumLiteral" containment="true" eOpposite="/0/EnumLiteral/enumType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclAnyType" eSuperTypes="/0/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclTypeType" eSuperTypes="/0/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionType" abstract="true" eSuperTypes="/0/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" ordered="false" lowerBound="1" eType="/0/Type" eOpposite="/0/Type/collectionType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="/0/BasicType"/>
    <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="/0/BasicType"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="/0/BasicType"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="/0/BasicType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instanceType" ordered="false" eType="/0/InstanceType" eOpposite="/0/InstanceType/classifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumType" ordered="false" eType="/0/EnumType" eOpposite="/0/EnumType/enumLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="/0/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="/0/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="BagType" eSuperTypes="/0/CollectionType"/>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
