extract:
	../dartextract.py fetched/dartLangSpec.tex extract.glue

fetch:
	curl https://raw.githubusercontent.com/dart-lang/bleeding_edge/032b686dcfed10517cdc70827b98604766f939ce/dart/docs/language/dartLangSpec.tex > fetched/dartLangSpec.tex
