extract:

fetch:
	rm -f fetched/*.g4
	https://raw.githubusercontent.com/antlr/grammars-v4/master/html/HTMLLexer.g4 > fetched/HTMLLexer.g4
	https://raw.githubusercontent.com/antlr/grammars-v4/master/html/HTMLParser.g4 > fetched/HTMLParser.g4
