extract:
	${tooldir}/xsd2bgf fetched/SBVR-XML-Schema.xsd extracted/grammar.bgf

fetch:
	wget http://www.omg.org/spec/SBVR/20130601/SBVR-XML-Schema.xsd
	mv SBVR-XML-Schema.xsd fetched/

include ../../../../../../Makefile.grammar
