<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="QoSCharacteristic">
    <eClassifiers xsi:type="ecore:EClass" name="QoSCharacteristic">
      <eStructuralFeatures xsi:type="ecore:EReference" name="invariant" ordered="false" lowerBound="1" eType="/0/BooleanExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parallel_and_composition" ordered="false" lowerBound="1" eType="/0/MappingExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parallel_or_composition" ordered="false" lowerBound="1" eType="/0/MappingExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequential_composition" ordered="false" lowerBound="1" eType="/0/MappingExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" ordered="false" lowerBound="1" eType="/0/MappingExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statisticalAttribute" ordered="false" upperBound="-1" eType="/0/StatisticalAttributekindKind" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false" lowerBound="1" eType="/0/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domain" ordered="false" lowerBound="1" eType="/0/Domain"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MappingExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatisticalAttributekindKind"/>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="/0/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="direction" ordered="false" lowerBound="1" eType="/0/DirectionKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DirectionKind">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Numeric" eSuperTypes="/0/Domain"/>
    <eClassifiers xsi:type="ecore:EClass" name="Set" eSuperTypes="/0/Domain">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stringSet" lowerBound="1" upperBound="-1" eType="/0/StringSet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="/0/Domain"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" ordered="false" unique="false" lowerBound="1" upperBound="-1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
