extract:
	cd bezault        && make extract
	cd iso-25436-2006 && make extract

clean:
	cd bezault        && make clean
	cd iso-25436-2006 && make clean

test:
	cd bezault        && make test
	cd iso-25436-2006 && make test

